package com.apollo.shared;

import com.apollo.shared.pojos.GetSpace;

import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class ApolloSpaces {
        private static final String S3_BASE_URL = "https://yoapollo.s3.us-east-2.amazonaws.com/spaces/";

        public static final List<GetSpace> SPACES = Arrays.asList(
                        new GetSpace("1080° Snowboarding", "1080snowboarding", S3_BASE_URL + "1080snowboarding.jpg"),
                        new GetSpace("7 Days to Die", "7todie", S3_BASE_URL + "7todie.jpg"),
                        new GetSpace("A Boy and His Blob", "boyandhisblob", S3_BASE_URL + "boyandhisblob.jpg"),
                        new GetSpace("A Hat in Time", "hatintime", S3_BASE_URL + "hatintime.jpg"),
                        new GetSpace("A Plague Tale: Innocence", "plaguetaleinnocence",
                                        S3_BASE_URL + "plaguetaleinnocence.jpg"),
                        new GetSpace("A Short Hike", "shorthike", S3_BASE_URL + "shorthike.jpg"),
                        new GetSpace("A Way Out", "awayout", S3_BASE_URL + "awayout.jpg"),
                        new GetSpace("Abzû", "abzu", S3_BASE_URL + "abzu.jpg"),
                        new GetSpace("Ace Attorney", "aceattorney", S3_BASE_URL + "aceattorney.jpg"),
                        new GetSpace("Actraiser", "actraiser", S3_BASE_URL + "actraiser.jpg"),
                        new GetSpace("Advance Wars", "advancewars", S3_BASE_URL + "advancewars.jpg"),
                        new GetSpace("Adventure Quest", "adventurequest", S3_BASE_URL + "adventurequest.jpg"),
                        new GetSpace("After the Fall", "afterthefall", S3_BASE_URL + "afterthefall.jpg"),
                        new GetSpace("Age of Empires", "aoe", S3_BASE_URL + "aoe.jpg"),
                        new GetSpace("Age of Wonders", "ageofwonders", S3_BASE_URL + "ageofwonders.jpg"),
                        new GetSpace("AI: The Somnium Files", "aisomnium", S3_BASE_URL + "aisomnium.jpg"),
                        new GetSpace("Airborne Kingdom", "airbornekingdom", S3_BASE_URL + "airbornekingdom.jpg"),
                        new GetSpace("Alan Wake", "alanwake", S3_BASE_URL + "alanwake.jpg"),
                        new GetSpace("Alchemy Stars", "alchemystars", S3_BASE_URL + "alchemystars.jpg"),
                        new GetSpace("Alien Swarm", "alienswarm", S3_BASE_URL + "alienswarm.jpg"),
                        new GetSpace("Alien: Isolation", "alienisolation", S3_BASE_URL + "alienisolation.jpg"),
                        new GetSpace("Aliens vs. Predator", "avp", S3_BASE_URL + "avp.jpg"),
                        new GetSpace("Alundra", "alundra", S3_BASE_URL + "alundra.jpg"),
                        new GetSpace("American Truck Simulator", "americantrucksim",
                                        S3_BASE_URL + "americantrucksim.jpg"),
                        new GetSpace("Amnesia", "amnesia", S3_BASE_URL + "amnesia.jpg"),
                        new GetSpace("Among Us", "amongus", S3_BASE_URL + "amongus.jpg"),
                        new GetSpace("Amplitude", "amplitude", S3_BASE_URL + "amplitude.jpg"),
                        new GetSpace("Animal Crossing", "animalcrossing", S3_BASE_URL + "animalcrossing.jpg"),
                        new GetSpace("Anno 1800", "anno1800", S3_BASE_URL + "anno1800.jpg"),
                        new GetSpace("Anno 2205", "anno2205", S3_BASE_URL + "anno2205.jpg"),
                        new GetSpace("Another World", "anotherworld", S3_BASE_URL + "anotherworld.jpg"),
                        new GetSpace("Anthem", "anthem", S3_BASE_URL + "anthem.jpg"),
                        new GetSpace("Antichamber", "antichamber", S3_BASE_URL + "antichamber.jpg"),
                        new GetSpace("Ape Escape", "apeescape", S3_BASE_URL + "apeescape.jpg"),
                        new GetSpace("Apex Legends", "apex", S3_BASE_URL + "apex.jpg"),
                        new GetSpace("Aquaria", "aquaria", S3_BASE_URL + "aquaria.jpg"),
                        new GetSpace("Arc System Works", "arcsystemworks", S3_BASE_URL + "arcsystemworks.jpg"),
                        new GetSpace("Arcanum", "arcanum", S3_BASE_URL + "arcanum.jpg"),
                        new GetSpace("Archvale", "archvale", S3_BASE_URL + "archvale.jpg"),
                        new GetSpace("Ark: Survival Evolved", "arksurvival", S3_BASE_URL + "arksurvival.jpg"),
                        new GetSpace("Arma", "arma", S3_BASE_URL + "arma.jpg"),
                        new GetSpace("Arma 2", "arma2", S3_BASE_URL + "arma2.jpg"),
                        new GetSpace("Arma 3", "arma3", S3_BASE_URL + "arma3.jpg"),
                        new GetSpace("Armello", "armello", S3_BASE_URL + "armello.jpg"),
                        new GetSpace("Artful Escape", "artfulescape", S3_BASE_URL + "artfulescape.jpg"),
                        new GetSpace("Ashen", "ashen", S3_BASE_URL + "ashen.jpg"),
                        new GetSpace("Asheron's Call", "asheronscall", S3_BASE_URL + "asheronscall.jpg"),
                        new GetSpace("Assassin's Creed", "assassinscreed", S3_BASE_URL + "assassinscreed.jpg"),
                        new GetSpace("Astro Bot Rescue Mission", "astrobot", S3_BASE_URL + "astrobot.jpg"),
                        new GetSpace("Astrologaster", "astrologaster", S3_BASE_URL + "astrologaster.jpg"),
                        new GetSpace("Astroneer", "astroneer", S3_BASE_URL + "astroneer.jpg"),
                        new GetSpace("Atelier Ryza", "atelierryza", S3_BASE_URL + "atelierryza.jpg"),
                        new GetSpace("Atomicrops", "atomicrops", S3_BASE_URL + "atomicrops.jpg"),
                        new GetSpace("Audiosurf", "audiosurf", S3_BASE_URL + "audiosurf.jpg"),
                        new GetSpace("Axiom Verge", "axiomverge", S3_BASE_URL + "axiomverge.jpg"),
                        new GetSpace("Axiom Verge 2", "axiomverge2", S3_BASE_URL + "axiomverge2.jpg"),
                        new GetSpace("Azure Striker Gunvolt", "azuregunvolt", S3_BASE_URL + "azuregunvolt.jpg"),
                        new GetSpace("Baba Is You", "babaisyou", S3_BASE_URL + "babaisyou.jpg"),
                        new GetSpace("Back 4 Blood", "back4blood", S3_BASE_URL + "back4blood.jpg"),
                        new GetSpace("Backbone", "backbone", S3_BASE_URL + "backbone.jpg"),
                        new GetSpace("Bad North", "badnorth", S3_BASE_URL + "badnorth.jpg"),
                        new GetSpace("Bad Rats", "badrats", S3_BASE_URL + "badrats.jpg"),
                        new GetSpace("Baldur's Gate 3", "bg3", S3_BASE_URL + "bg3.jpg"),
                        new GetSpace("Ball Guy Adventures", "ballguy", S3_BASE_URL + "ballguy.jpg"),
                        new GetSpace("Balloon Fight", "balloonfight", S3_BASE_URL + "balloonfight.jpg"),
                        new GetSpace("Banjo-Kazooie", "banjokazooie", S3_BASE_URL + "banjokazooie.jpg"),
                        new GetSpace("Banjo-Tooie", "banjotooie", S3_BASE_URL + "banjotooie.jpg"),
                        new GetSpace("Bard's Tale", "bardstale", S3_BASE_URL + "bardstale.jpg"),
                        new GetSpace("Bastion", "bastion", S3_BASE_URL + "bastion.jpg"),
                        new GetSpace("Batman: Arkham Knight", "batmanak", S3_BASE_URL + "batmanak.jpg"),
                        new GetSpace("Battle Chef Brigade", "battlechefbrigade", S3_BASE_URL + "battlechefbrigade.jpg"),
                        new GetSpace("Battleblock Theater", "battleblocktheater",
                                        S3_BASE_URL + "battleblocktheater.jpg"),
                        new GetSpace("Battlefield", "battlefield", S3_BASE_URL + "battlefield.jpg"),
                        new GetSpace("Battletech", "battletech", S3_BASE_URL + "battletech.jpg"),
                        new GetSpace("Battlezone", "battlezone", S3_BASE_URL + "battlezone.jpg"),
                        new GetSpace("Beat Saber", "beatsaber", S3_BASE_URL + "beatsaber.jpg"),
                        new GetSpace("Before Your Eyes", "beforeyoureyes", S3_BASE_URL + "beforeyoureyes.jpg"),
                        new GetSpace("Bejeweled", "bejeweled", S3_BASE_URL + "bejeweled.jpg"),
                        new GetSpace("Bendy and the Ink Machine", "bendy", S3_BASE_URL + "bendy.jpg"),
                        new GetSpace("Besiege", "besiege", S3_BASE_URL + "besiege.jpg"),
                        new GetSpace("Beyond Good & Evil", "beyondgoodevil", S3_BASE_URL + "beyondgoodevil.jpg"),
                        new GetSpace("Beyond: Two Souls", "beyondtwosouls", S3_BASE_URL + "beyondtwosouls.jpg"),
                        new GetSpace("Big Brain Academy", "bigbrainacademy", S3_BASE_URL + "bigbrainacademy.jpg"),
                        new GetSpace("Binary Domain", "binarydomain", S3_BASE_URL + "binarydomain.jpg"),
                        new GetSpace("Biomutant", "biomutant", S3_BASE_URL + "biomutant.jpg"),
                        new GetSpace("Bioshock", "bioshock", S3_BASE_URL + "bioshock.jpg"),
                        new GetSpace("Bioshock 2", "bioshock2", S3_BASE_URL + "bioshock2.jpg"),
                        new GetSpace("BioShock Infinite", "bioshockinfinite", S3_BASE_URL + "bioshockinfinite.jpg"),
                        new GetSpace("Bit.Trip Runner", "bittrip", S3_BASE_URL + "bittrip.jpg"),
                        new GetSpace("Black & White", "blackandwhite", S3_BASE_URL + "blackandwhite.jpg"),
                        new GetSpace("Black Desert Online", "blackdesert", S3_BASE_URL + "blackdesert.jpg"),
                        new GetSpace("Black Mesa", "blackmesa", S3_BASE_URL + "blackmesa.jpg"),
                        new GetSpace("Blackthorn", "blackthorn", S3_BASE_URL + "blackthorn.jpg"),
                        new GetSpace("Blade & Soul", "bladeandsoul", S3_BASE_URL + "bladeandsoul.jpg"),
                        new GetSpace("Blasphemous", "blasphemous", S3_BASE_URL + "blasphemous.jpg"),
                        new GetSpace("Blaster Master", "blastermaster", S3_BASE_URL + "blastermaster.jpg"),
                        new GetSpace("BlazBlue", "blazblue", S3_BASE_URL + "blazblue.jpg"),
                        new GetSpace("Bloodborne", "bloodborne", S3_BASE_URL + "bloodborne.jpg"),
                        new GetSpace("Bloodstained: Ritual of the Night", "bloodstained",
                                        S3_BASE_URL + "bloodstained.jpg"),
                        new GetSpace("Bloons Tower Defense", "btd", S3_BASE_URL + "btd.jpg"),
                        new GetSpace("Blue Dragon", "bluedragon", S3_BASE_URL + "bluedragon.jpg"),
                        new GetSpace("Body Harvest", "bodyharvest", S3_BASE_URL + "bodyharvest.jpg"),
                        new GetSpace("Boktai", "boktai", S3_BASE_URL + "boktai.jpg"),
                        new GetSpace("Bomber Crew", "bombercrew", S3_BASE_URL + "bombercrew.jpg"),
                        new GetSpace("Bomberman", "bomberman", S3_BASE_URL + "bomberman.jpg"),
                        new GetSpace("Boneworks", "boneworks", S3_BASE_URL + "boneworks.jpg"),
                        new GetSpace("Boogerman", "boogerman", S3_BASE_URL + "boogerman.jpg"),
                        new GetSpace("Boom Blox", "boomblox", S3_BASE_URL + "boomblox.jpg"),
                        new GetSpace("Borderlands", "borderlands", S3_BASE_URL + "borderlands.jpg"),
                        new GetSpace("Borderlands 2", "borderlands2", S3_BASE_URL + "borderlands2.jpg"),
                        new GetSpace("Borderlands 3", "borderlands3", S3_BASE_URL + "borderlands3.jpg"),
                        new GetSpace("Braid", "braid", S3_BASE_URL + "braid.jpg"),
                        new GetSpace("Breath of Fire", "breathoffire", S3_BASE_URL + "breathoffire.jpg"),
                        new GetSpace("Bridge Constructor Portal", "bridgeportal", S3_BASE_URL + "bridgeportal.jpg"),
                        new GetSpace("Broforce", "broforce", S3_BASE_URL + "broforce.jpg"),
                        new GetSpace("Broken Sword", "brokensword", S3_BASE_URL + "brokensword.jpg"),
                        new GetSpace("Brutal Legend", "brutallegend", S3_BASE_URL + "brutallegend.jpg"),
                        new GetSpace("Bug Fables", "bugfables", S3_BASE_URL + "bugfables.jpg"),
                        new GetSpace("Bugsnax", "bugsnax", S3_BASE_URL + "bugsnax.jpg"),
                        new GetSpace("Bulletstorm", "bulletstorm", S3_BASE_URL + "bulletstorm.jpg"),
                        new GetSpace("Bully", "bully", S3_BASE_URL + "bully.jpg"),
                        new GetSpace("Bunny Must Die!", "bunnymustdie", S3_BASE_URL + "bunnymustdie.jpg"),
                        new GetSpace("Burnout Series", "burnout", S3_BASE_URL + "burnout.jpg"),
                        new GetSpace("Caesar III", "caesar3", S3_BASE_URL + "caesar3.jpg"),
                        new GetSpace("Call of Cthulhu", "callofcthulhu", S3_BASE_URL + "callofcthulhu.jpg"),
                        new GetSpace("Call of Duty", "cod", S3_BASE_URL + "cod.jpg"),
                        new GetSpace("Candy Crush Saga", "candycrush", S3_BASE_URL + "candycrush.jpg"),
                        new GetSpace("Cannon Fodder", "cannonfodder", S3_BASE_URL + "cannonfodder.jpg"),
                        new GetSpace("Captain Toad: Treasure Tracker", "captaintoad", S3_BASE_URL + "captaintoad.jpg"),
                        new GetSpace("Car Mechanic Simulator", "carmechsim", S3_BASE_URL + "carmechsim.jpg"),
                        new GetSpace("Carmageddon", "carmageddon", S3_BASE_URL + "carmageddon.jpg"),
                        new GetSpace("Carrion", "carrion", S3_BASE_URL + "carrion.jpg"),
                        new GetSpace("Castle Crashers", "castlecrashers", S3_BASE_URL + "castlecrashers.jpg"),
                        new GetSpace("Castlevania", "castlevania", S3_BASE_URL + "castlevania.jpg"),
                        new GetSpace("Cataclysm: Dark Days Ahead", "cataclysm", S3_BASE_URL + "cataclysm.jpg"),
                        new GetSpace("Catherine", "catherine", S3_BASE_URL + "catherine.jpg"),
                        new GetSpace("Caveblazers", "caveblazers", S3_BASE_URL + "caveblazers.jpg"),
                        new GetSpace("Celeste", "celeste", S3_BASE_URL + "celeste.jpg"),
                        new GetSpace("Chaos;Head", "chaoshead", S3_BASE_URL + "chaoshead.jpg"),
                        new GetSpace("Chex Quest", "chexquest", S3_BASE_URL + "chexquest.jpg"),
                        new GetSpace("Chibi-Robo!", "chibirobo", S3_BASE_URL + "chibirobo.jpg"),
                        new GetSpace("Chicory: A Colorful Tale", "chicory", S3_BASE_URL + "chicory.jpg"),
                        new GetSpace("Child of Eden", "childofeden", S3_BASE_URL + "childofeden.jpg"),
                        new GetSpace("Children of Morta", "childrenofmorta", S3_BASE_URL + "childrenofmorta.jpg"),
                        new GetSpace("Chivalry 2", "chivalry2", S3_BASE_URL + "chivalry2.jpg"),
                        new GetSpace("Chocobo Racing", "chocoboracing", S3_BASE_URL + "chocoboracing.jpg"),
                        new GetSpace("Choo-Choo Charles", "choochoocharles", S3_BASE_URL + "choochoocharles.jpg"),
                        new GetSpace("Chrome Hounds", "chromehounds", S3_BASE_URL + "chromehounds.jpg"),
                        new GetSpace("Chrono Cross", "chronocross", S3_BASE_URL + "chronocross.jpg"),
                        new GetSpace("Chrono Trigger", "chronotrigger", S3_BASE_URL + "chronotrigger.jpg"),
                        new GetSpace("Chulip", "chulip", S3_BASE_URL + "chulip.jpg"),
                        new GetSpace("Cities Skylines", "citiesskylines", S3_BASE_URL + "citiesskylines.jpg"),
                        new GetSpace("Citizen Sleeper", "citizensleeper", S3_BASE_URL + "citizensleeper.jpg"),
                        new GetSpace("City of Heroes", "cityofheroes", S3_BASE_URL + "cityofheroes.jpg"),
                        new GetSpace("Civilization Series", "civ", S3_BASE_URL + "civ.jpg"),
                        new GetSpace("Cladun", "cladun", S3_BASE_URL + "cladun.jpg"),
                        new GetSpace("Clash of Clans", "coc", S3_BASE_URL + "coc.jpg"),
                        new GetSpace("Clash Royale", "clashroyale", S3_BASE_URL + "clashroyale.jpg"),
                        new GetSpace("Clive Barker's Undying", "undying", S3_BASE_URL + "undying.jpg"),
                        new GetSpace("Clock Tower", "clocktower", S3_BASE_URL + "clocktower.jpg"),
                        new GetSpace("ClusterTruck", "clustertruck", S3_BASE_URL + "clustertruck.jpg"),
                        new GetSpace("Cobra Kai: The Karate Kid Saga Continues", "cobrakai",
                                        S3_BASE_URL + "cobrakai.jpg"),
                        new GetSpace("Cogmind", "cogmind", S3_BASE_URL + "cogmind.jpg"),
                        new GetSpace("Comix Zone", "comixzone", S3_BASE_URL + "comixzone.jpg"),
                        new GetSpace("Command & Conquer", "commandconquer", S3_BASE_URL + "commandconquer.jpg"),
                        new GetSpace("Commandos", "commandos", S3_BASE_URL + "commandos.jpg"),
                        new GetSpace("Company of Heroes", "companyofheroes", S3_BASE_URL + "companyofheroes.jpg"),
                        new GetSpace("Condemned: Criminal Origins", "condemned", S3_BASE_URL + "condemned.jpg"),
                        new GetSpace("Conker's Bad Fur Day", "conker", S3_BASE_URL + "conker.jpg"),
                        new GetSpace("Control", "control", S3_BASE_URL + "control.jpg"),
                        new GetSpace("Convoy", "convoy", S3_BASE_URL + "convoy.jpg"),
                        new GetSpace("Cookie Clicker", "cookieclicker", S3_BASE_URL + "cookieclicker.jpg"),
                        new GetSpace("Cooking Mama", "cookingmama", S3_BASE_URL + "cookingmama.jpg"),
                        new GetSpace("Corpse Party", "corpseparty", S3_BASE_URL + "corpseparty.jpg"),
                        new GetSpace("Costume Quest", "costumequest", S3_BASE_URL + "costumequest.jpg"),
                        new GetSpace("Costume Quest 2", "costumequest2", S3_BASE_URL + "costumequest2.jpg"),
                        new GetSpace("Costume Quest 2", "cs", S3_BASE_URL + "cs.jpg"),
                        new GetSpace("Crackdown", "crackdown", S3_BASE_URL + "crackdown.jpg"),
                        new GetSpace("Crash Bandicoot", "crashbandicoot", S3_BASE_URL + "crashbandicoot.jpg"),
                        new GetSpace("Crayola Scoot", "crayolascoot", S3_BASE_URL + "crayolascoot.jpg"),
                        new GetSpace("Creature in the Well", "creaturewell", S3_BASE_URL + "creaturewell.jpg"),
                        new GetSpace("Crimsonland", "crimsonland", S3_BASE_URL + "crimsonland.jpg"),
                        new GetSpace("Croc: Legend of the Gobbos", "croc", S3_BASE_URL + "croc.jpg"),
                        new GetSpace("CrossCode", "crosscode", S3_BASE_URL + "crosscode.jpg"),
                        new GetSpace("Crossy Road", "crossyroad", S3_BASE_URL + "crossyroad.jpg"),
                        new GetSpace("Crowfall", "crowfall", S3_BASE_URL + "crowfall.jpg"),
                        new GetSpace("Cruelty Squad", "crueltysquad", S3_BASE_URL + "crueltysquad.jpg"),
                        new GetSpace("Crypt of the NecroDancer", "cryptnecrodancer",
                                        S3_BASE_URL + "cryptnecrodancer.jpg"),
                        new GetSpace("Crysis", "crysis", S3_BASE_URL + "crysis.jpg"),
                        new GetSpace("Cultist Simulator", "cultistsim", S3_BASE_URL + "cultistsim.jpg"),
                        new GetSpace("Cuphead", "cuphead", S3_BASE_URL + "cuphead.jpg"),
                        new GetSpace("Cursed to Golf", "cursedtogolf", S3_BASE_URL + "cursedtogolf.jpg"),
                        new GetSpace("Cyberpunk 2077", "cyberpunk2077", S3_BASE_URL + "cyberpunk2077.jpg"),
                        new GetSpace("Daemon X Machina", "daemonxmachina", S3_BASE_URL + "daemonxmachina.jpg"),
                        new GetSpace("Dakar Desert Rally", "dakarrally", S3_BASE_URL + "dakarrally.jpg"),
                        new GetSpace("Dandy Dungeon", "dandydungeon", S3_BASE_URL + "dandydungeon.jpg"),
                        new GetSpace("Danganronpa", "danganronpa", S3_BASE_URL + "danganronpa.jpg"),
                        new GetSpace("Dark Souls 1", "darksouls1", S3_BASE_URL + "darksouls1.jpg"),
                        new GetSpace("Dark Souls 2", "darksouls2", S3_BASE_URL + "darksouls2.jpg"),
                        new GetSpace("Dark Souls 3", "darksouls3", S3_BASE_URL + "darksouls3.jpg"),
                        new GetSpace("Darkest Dungeon", "darkestdungeon", S3_BASE_URL + "darkestdungeon.jpg"),
                        new GetSpace("Darksiders", "darksiders", S3_BASE_URL + "darksiders.jpg"),
                        new GetSpace("Darkwood", "darkwood", S3_BASE_URL + "darkwood.jpg"),
                        new GetSpace("Das Boot", "dasboot", S3_BASE_URL + "dasboot.jpg"),
                        new GetSpace("Dauntless", "dauntless", S3_BASE_URL + "dauntless.jpg"),
                        new GetSpace("Dawn of War", "dawnofwar", S3_BASE_URL + "dawnofwar.jpg"),
                        new GetSpace("Day of the Tentacle", "dott", S3_BASE_URL + "dott.jpg"),
                        new GetSpace("DayZ", "dayz", S3_BASE_URL + "dayz.jpg"),
                        new GetSpace("Dead by Daylight", "dbd", S3_BASE_URL + "dbd.jpg"),
                        new GetSpace("Dead Cells", "deadcells", S3_BASE_URL + "deadcells.jpg"),
                        new GetSpace("Deadly Premonition", "deadlypremonition", S3_BASE_URL + "deadlypremonition.jpg"),
                        new GetSpace("Dear Esther", "dearesther", S3_BASE_URL + "dearesther.jpg"),
                        new GetSpace("Death Stranding", "deathstranding", S3_BASE_URL + "deathstranding.jpg"),
                        new GetSpace("Deathloop", "deathloop", S3_BASE_URL + "deathloop.jpg"),
                        new GetSpace("Death's Door", "deathsdoor", S3_BASE_URL + "deathsdoor.jpg"),
                        new GetSpace("Deathtrap Dungeon", "deathtrapdungeon", S3_BASE_URL + "deathtrapdungeon.jpg"),
                        new GetSpace("Deep Rock Galactic", "deeprockgalactic", S3_BASE_URL + "deeprockgalactic.jpg"),
                        new GetSpace("Def Jam: Fight for NY", "defjamny", S3_BASE_URL + "defjamny.jpg"),
                        new GetSpace("Defiants", "defiants", S3_BASE_URL + "defiants.jpg"),
                        new GetSpace("Demetrios", "demetrios", S3_BASE_URL + "demetrios.jpg"),
                        new GetSpace("Demons Souls", "demonssouls", S3_BASE_URL + "demonssouls.jpg"),
                        new GetSpace("Demon's Tilt", "demonstilt", S3_BASE_URL + "demonstilt.jpg"),
                        new GetSpace("Descenders", "descenders", S3_BASE_URL + "descenders.jpg"),
                        new GetSpace("Desperados III", "desperados3", S3_BASE_URL + "desperados3.jpg"),
                        new GetSpace("Destiny 2", "destiny2", S3_BASE_URL + "destiny2.jpg"),
                        new GetSpace("Detroit: Become Human", "becomehuman", S3_BASE_URL + "becomehuman.jpg"),
                        new GetSpace("Deus Ex", "deusex", S3_BASE_URL + "deus-ex.jpg"),
                        new GetSpace("Devil Daggers", "devildaggers", S3_BASE_URL + "devildaggers.jpg"),
                        new GetSpace("Devil May Cry", "dmc", S3_BASE_URL + "dmc.jpg"),
                        new GetSpace("Diablo", "diablo", S3_BASE_URL + "diablo.jpg"),
                        new GetSpace("Dicey Dungeons", "diceydungeons", S3_BASE_URL + "diceydungeons.jpg"),
                        new GetSpace("Diddy Kong Racing", "diddykongracing", S3_BASE_URL + "diddykongracing.jpg"),
                        new GetSpace("Dig Dug", "digdug", S3_BASE_URL + "digdug.jpg"),
                        new GetSpace("Disco Elysium", "discoelysium", S3_BASE_URL + "discoelysium.jpg"),
                        new GetSpace("Dishonored", "dishonored", S3_BASE_URL + "dishonored.jpg"),
                        new GetSpace("Divekick", "divekick", S3_BASE_URL + "divekick.jpg"),
                        new GetSpace("Divinity: Dragon Commander", "dragoncommander",
                                        S3_BASE_URL + "dragoncommander.jpg"),
                        new GetSpace("Divinity: Original Sin 2", "divinity2", S3_BASE_URL + "divinity2.jpg"),
                        new GetSpace("Doctor Who: The Edge of Time", "doctorwhoedge",
                                        S3_BASE_URL + "doctorwhoedge.jpg"),
                        new GetSpace("Doki Doki Literature Club", "dokidoki", S3_BASE_URL + "dokidoki.jpg"),
                        new GetSpace("Donkey Kong Country", "dkc", S3_BASE_URL + "dkc.jpg"),
                        new GetSpace("Don't Starve", "dontstarve", S3_BASE_URL + "dontstarve.jpg"),
                        new GetSpace("DOOM 64", "doom64", S3_BASE_URL + "doom64.jpg"),
                        new GetSpace("Doom Eternal", "doom", S3_BASE_URL + "doom.jpg"),
                        new GetSpace("Doorways: Holy Mountains of Flesh", "doorways", S3_BASE_URL + "doorways.jpg"),
                        new GetSpace("Dota 2", "dota2", S3_BASE_URL + "dota2.jpg"),
                        new GetSpace("Dota Underlords", "dotaunderlords", S3_BASE_URL + "dotaunderlords.jpg"),
                        new GetSpace("Dragon Age", "dragonage", S3_BASE_URL + "dragonage.jpg"),
                        new GetSpace("Dragon Ball FighterZ", "dbfighterz", S3_BASE_URL + "dbfighterz.jpg"),
                        new GetSpace("Dragon Quest", "dragonquest", S3_BASE_URL + "dragonquest.jpg"),
                        new GetSpace("DragonFable", "dragonfable", S3_BASE_URL + "dragonfable.jpg"),
                        new GetSpace("Dragon's Crown", "dragonscrown", S3_BASE_URL + "dragonscrown.jpg"),
                        new GetSpace("Dragon's Dogma", "dragonsdogma", S3_BASE_URL + "dragonsdogma.jpg"),
                        new GetSpace("Drakengard", "drakengard", S3_BASE_URL + "drakengard.jpg"),
                        new GetSpace("Drawful", "drawful", S3_BASE_URL + "drawful.jpg"),
                        new GetSpace("Dreadnought", "dreadnought", S3_BASE_URL + "dreadnought.jpg"),
                        new GetSpace("Dungeon Defenders", "dungeondefenders", S3_BASE_URL + "dungeondefenders.jpg"),
                        new GetSpace("Dungeon of the Endless", "dungeonendless", S3_BASE_URL + "dungeonendless.jpg"),
                        new GetSpace("Dustforce", "dustforce", S3_BASE_URL + "dustforce.jpg"),
                        new GetSpace("Dying Light", "dyinglight", S3_BASE_URL + "dyinglight.jpg"),
                        new GetSpace("Dyson Sphere Program", "dysonsphere", S3_BASE_URL + "dysonsphere.jpg"),
                        new GetSpace("EA FC", "eafc", S3_BASE_URL + "eafc.jpg"),
                        new GetSpace("Earthbound", "earthbound", S3_BASE_URL + "earthbound.jpg"),
                        new GetSpace("EarthBound Beginnings", "mothereb", S3_BASE_URL + "mothereb.jpg"),
                        new GetSpace("Eastward", "eastward", S3_BASE_URL + "eastward.jpg"),
                        new GetSpace("Ecco the Dolphin", "ecco", S3_BASE_URL + "ecco.jpg"),
                        new GetSpace("Eco", "eco", S3_BASE_URL + "eco.jpg"),
                        new GetSpace("El Shaddai: Ascension of the Metatron", "elshaddai",
                                        S3_BASE_URL + "elshaddai.jpg"),
                        new GetSpace("Elden Ring", "eldenring", S3_BASE_URL + "eldenring.jpg"),
                        new GetSpace("Elex", "elex", S3_BASE_URL + "elex.jpg"),
                        new GetSpace("Elite Beat Agents", "elitebeatagents", S3_BASE_URL + "elitebeatagents.jpg"),
                        new GetSpace("Elite Dangerous", "elitedangerous", S3_BASE_URL + "elitedangerous.jpg"),
                        new GetSpace("Eliza", "eliza", S3_BASE_URL + "eliza.jpg"),
                        new GetSpace("Empire Earth", "empireearth", S3_BASE_URL + "empireearth.jpg"),
                        new GetSpace("Enclave", "enclave", S3_BASE_URL + "enclave.jpg"),
                        new GetSpace("Endless Dungeon", "endlessdungeon", S3_BASE_URL + "endlessdungeon.jpg"),
                        new GetSpace("Endless Legend", "endlesslegend", S3_BASE_URL + "endlesslegend.jpg"),
                        new GetSpace("Endless Ocean", "endlessocean", S3_BASE_URL + "endlessocean.jpg"),
                        new GetSpace("Endless Space", "endlessspace", S3_BASE_URL + "endlessspace.jpg"),
                        new GetSpace("Enslaved: Odyssey to the West", "enslaved", S3_BASE_URL + "enslaved.jpg"),
                        new GetSpace("Enter the Gungeon", "enterthegungeon", S3_BASE_URL + "enterthegungeon.jpg"),
                        new GetSpace("Epic Mickey", "epicmickey", S3_BASE_URL + "epicmickey.jpg"),
                        new GetSpace("Eternal Darkness: Sanity's Requiem", "eternaldarkness",
                                        S3_BASE_URL + "eternaldarkness.jpg"),
                        new GetSpace("Europa Universalis IV", "eu4", S3_BASE_URL + "eu4.jpg"),
                        new GetSpace("EVE Online", "eveonline", S3_BASE_URL + "eveonline.jpg"),
                        new GetSpace("Evergarden", "evergarden", S3_BASE_URL + "evergarden.jpg"),
                        new GetSpace("Everhood", "everhood", S3_BASE_URL + "everhood.jpg"),
                        new GetSpace("EverQuest", "everquest", S3_BASE_URL + "everquest.jpg"),
                        new GetSpace("Everybody's Golf", "everybodysgolf", S3_BASE_URL + "everybodysgolf.jpg"),
                        new GetSpace("Everything", "everything", S3_BASE_URL + "everything.jpg"),
                        new GetSpace("Evil Genius", "evilgenius", S3_BASE_URL + "evilgenius.jpg"),
                        new GetSpace("F.E.A.R.", "fear", S3_BASE_URL + "fear.jpg"),
                        new GetSpace("Fable", "fable", S3_BASE_URL + "fable.jpg"),
                        new GetSpace("Fable II", "fable2", S3_BASE_URL + "fable2.jpg"),
                        new GetSpace("Facade", "facade", S3_BASE_URL + "facade.jpg"),
                        new GetSpace("Factorio", "factorio", S3_BASE_URL + "factorio.jpg"),
                        new GetSpace("Fae Tactics", "faetactis", S3_BASE_URL + "faetactis.jpg"),
                        new GetSpace("Fall Guys", "fallguys", S3_BASE_URL + "fallguys.jpg"),
                        new GetSpace("Fallout", "fallout", S3_BASE_URL + "fallout.jpg"),
                        new GetSpace("Fantasy Life", "fantasylife", S3_BASE_URL + "fantasylife.jpg"),
                        new GetSpace("Far Cry 3", "farcry3", S3_BASE_URL + "farcry3.jpg"),
                        new GetSpace("Far: Lone Sails", "farlone", S3_BASE_URL + "farlone.jpg"),
                        new GetSpace("Fatal Frame", "fatalframe", S3_BASE_URL + "fatalframe.jpg"),
                        new GetSpace("Fate", "fate", S3_BASE_URL + "fate.jpg"),
                        new GetSpace("Fate/Grand Order", "fategrandorder", S3_BASE_URL + "fategrandorder.jpg"),
                        new GetSpace("Fear Effect", "feareffect", S3_BASE_URL + "feareffect.jpg"),
                        new GetSpace("FEZ", "fez", S3_BASE_URL + "fez.jpg"),
                        new GetSpace("Final Fantasy", "ff", S3_BASE_URL + "ff.jpg"),
                        new GetSpace("Fire Emblem", "fireemblem", S3_BASE_URL + "fireemblem.jpg"),
                        new GetSpace("Firewatch", "firewatch", S3_BASE_URL + "firewatch.jpg"),
                        new GetSpace("Fist of the North Star", "fistofnorthstar", S3_BASE_URL + "fistofnorthstar.jpg"),
                        new GetSpace("Five Nights at Freddy's", "fnaf", S3_BASE_URL + "fnaf.jpg"),
                        new GetSpace("Flashback", "flashback", S3_BASE_URL + "flashback.jpg"),
                        new GetSpace("Floor Kids", "floorkids", S3_BASE_URL + "floorkids.jpg"),
                        new GetSpace("Flow", "flow", S3_BASE_URL + "flow.jpg"),
                        new GetSpace("Flower", "flower", S3_BASE_URL + "flower.jpg"),
                        new GetSpace("Flying Dragon", "flyingdragon", S3_BASE_URL + "flyingdragon.jpg"),
                        new GetSpace("For Honor", "forhonor", S3_BASE_URL + "forhonor.jpg"),
                        new GetSpace("Forager", "forager", S3_BASE_URL + "forager.jpg"),
                        new GetSpace("Forgotton Anne", "forgottonanne", S3_BASE_URL + "forgottonanne.jpg"),
                        new GetSpace("Fortnite", "fortnite", S3_BASE_URL + "fortnite.jpg"),
                        new GetSpace("Forza", "forza", S3_BASE_URL + "forza.jpg"),
                        new GetSpace("Freedom Wars", "freedomwars", S3_BASE_URL + "freedomwars.jpg"),
                        new GetSpace("Freelancer", "freelancer", S3_BASE_URL + "freelancer.jpg"),
                        new GetSpace("Frequency", "frequency", S3_BASE_URL + "frequency.jpg"),
                        new GetSpace("Front Mission", "frontmission", S3_BASE_URL + "frontmission.jpg"),
                        new GetSpace("Frostpunk", "frostpunk", S3_BASE_URL + "frostpunk.jpg"),
                        new GetSpace("Frozen Synapse", "frozensynapse", S3_BASE_URL + "frozensynapse.jpg"),
                        new GetSpace("FTL: Faster Than Light", "ftl", S3_BASE_URL + "ftl.jpg"),
                        new GetSpace("Full Throttle", "fullthrottle", S3_BASE_URL + "fullthrottle.jpg"),
                        new GetSpace("Furi", "furi", S3_BASE_URL + "furi.jpg"),
                        new GetSpace("F-Zero", "fzero", S3_BASE_URL + "fzero.jpg"),
                        new GetSpace("Galaga", "galaga", S3_BASE_URL + "galaga.jpg"),
                        new GetSpace("Galaxy Fight: Universal Warriors", "galaxyfight",
                                        S3_BASE_URL + "galaxyfight.jpg"),
                        new GetSpace("Gang Beasts", "gangbeasts", S3_BASE_URL + "gangbeasts.jpg"),
                        new GetSpace("Garou: Mark of the Wolves", "garou", S3_BASE_URL + "garou.jpg"),
                        new GetSpace("Garry's Mod", "gmod", S3_BASE_URL + "gmod.jpg"),
                        new GetSpace("Gato Roboto", "gatoroboto", S3_BASE_URL + "gatoroboto.jpg"),
                        new GetSpace("G-Darius", "gdarius", S3_BASE_URL + "gdarius.jpg"),
                        new GetSpace("Gears Tactics", "gearstactics", S3_BASE_URL + "gearstactics.jpg"),
                        new GetSpace("Genital Jousting", "genitaljousting", S3_BASE_URL + "genitaljousting.jpg"),
                        new GetSpace("Genshin Impact", "genshinimpact", S3_BASE_URL + "genshinimpact.jpg"),
                        new GetSpace("Geometry Dash", "geometrydash", S3_BASE_URL + "geometrydash.jpg"),
                        new GetSpace("Getting Over It", "gettingoverit", S3_BASE_URL + "gettingoverit.jpg"),
                        new GetSpace("Ghost of Tsushima", "tsushima", S3_BASE_URL + "tsushima.jpg"),
                        new GetSpace("Ghostrunner", "ghostrunner", S3_BASE_URL + "ghostrunner.jpg"),
                        new GetSpace("Ghosts 'n Goblins", "ghostsngoblins", S3_BASE_URL + "ghostsngoblins.jpg"),
                        new GetSpace("Ghostwire: Tokyo", "ghostwiretokyo", S3_BASE_URL + "ghostwiretokyo.jpg"),
                        new GetSpace("Giants: Citizen Kabuto", "giantscitizenkabuto",
                                        S3_BASE_URL + "giantscitizenkabuto.jpg"),
                        new GetSpace("Gitaroo Man", "gitarooman", S3_BASE_URL + "gitarooman.jpg"),
                        new GetSpace("Glass Masquerade", "glassmasquerade", S3_BASE_URL + "glassmasquerade.jpg"),
                        new GetSpace("Goat Simulator", "goatsim", S3_BASE_URL + "goatsim.jpg"),
                        new GetSpace("God of War", "gow", S3_BASE_URL + "gow.jpg"),
                        new GetSpace("GoldenEye 007", "goldeneye007", S3_BASE_URL + "goldeneye007.jpg"),
                        new GetSpace("Golf Story", "golfstory", S3_BASE_URL + "golfstory.jpg"),
                        new GetSpace("Golf With Your Friends", "golfwithfriends", S3_BASE_URL + "golfwithfriends.jpg"),
                        new GetSpace("Gorogoa", "gorogoa", S3_BASE_URL + "gorogoa.jpg"),
                        new GetSpace("Gradius", "gradius", S3_BASE_URL + "gradius.jpg"),
                        new GetSpace("Grand Theft Auto", "gta", S3_BASE_URL + "gta.jpg"),
                        new GetSpace("Grandia", "grandia", S3_BASE_URL + "grandia.jpg"),
                        new GetSpace("Graveyard Keeper", "graveyardkeeper", S3_BASE_URL + "graveyardkeeper.jpg"),
                        new GetSpace("Gravity Rush", "gravityrush", S3_BASE_URL + "gravityrush.jpg"),
                        new GetSpace("Grew Landstalker", "grewlandstalker", S3_BASE_URL + "grewlandstalker.jpg"),
                        new GetSpace("Grim Dawn", "grimdawn", S3_BASE_URL + "grimdawn.jpg"),
                        new GetSpace("Grim Fandango", "grimfandango", S3_BASE_URL + "grimfandango.jpg"),
                        new GetSpace("Gris", "gris", S3_BASE_URL + "gris.jpg"),
                        new GetSpace("Grow Home", "growhome", S3_BASE_URL + "growhome.jpg"),
                        new GetSpace("Gubble", "gubble", S3_BASE_URL + "gubble.jpg"),
                        new GetSpace("Guild Wars", "guildwars", S3_BASE_URL + "guildwars.jpg"),
                        new GetSpace("Guilty Gear", "guiltygear", S3_BASE_URL + "guiltygear.jpg"),
                        new GetSpace("Guilty Gear Strive", "guiltygearstrive", S3_BASE_URL + "guiltygearstrive.jpg"),
                        new GetSpace("Guitar Hero", "guitarhero", S3_BASE_URL + "guitarhero.jpg"),
                        new GetSpace("Gunfire Reborn", "gunfirereborn", S3_BASE_URL + "gunfirereborn.jpg"),
                        new GetSpace("Gunpoint", "gunpoint", S3_BASE_URL + "gunpoint.jpg"),
                        new GetSpace("Gunstar Heroes", "gunstarheroes", S3_BASE_URL + "gunstarheroes.jpg"),
                        new GetSpace("Guntastic", "guntastic", S3_BASE_URL + "guntastic.jpg"),
                        new GetSpace("Hacknet", "hacknet", S3_BASE_URL + "hacknet.jpg"),
                        new GetSpace("Hades", "hades", S3_BASE_URL + "hades.jpg"),
                        new GetSpace("Haiku the Robot", "haikutherobot", S3_BASE_URL + "haikutherobot.jpg"),
                        new GetSpace("Half-Life", "halflife", S3_BASE_URL + "halflife.jpg"),
                        new GetSpace("Half-Life 2", "halflife2", S3_BASE_URL + "halflife2.jpg"),
                        new GetSpace("Half-Life: Alyx", "halflifealyx", S3_BASE_URL + "halflifealyx.jpg"),
                        new GetSpace("Halo", "halo", S3_BASE_URL + "halo.jpg"),
                        new GetSpace("Hand of Fate", "handoffate", S3_BASE_URL + "handoffate.jpg"),
                        new GetSpace("Harvest Moon", "harvestmoon", S3_BASE_URL + "harvestmoon.jpg"),
                        new GetSpace("Hatsune Miku: Project DIVA", "projectdiva", S3_BASE_URL + "projectdiva.jpg"),
                        new GetSpace("Haven", "haven", S3_BASE_URL + "haven.jpg"),
                        new GetSpace("Heart Machine", "heartmachine", S3_BASE_URL + "heartmachine.jpg"),
                        new GetSpace("Heart of Darkness", "heartofdarkness", S3_BASE_URL + "heartofdarkness.jpg"),
                        new GetSpace("Hearthstone", "hearthstone", S3_BASE_URL + "hearthstone.jpg"),
                        new GetSpace("Hearts of Iron", "heartsofiron", S3_BASE_URL + "heartsofiron.jpg"),
                        new GetSpace("Heaven's Vault", "heavensvault", S3_BASE_URL + "heavensvault.jpg"),
                        new GetSpace("Heavy Rain", "heavyrain", S3_BASE_URL + "heavyrain.jpg"),
                        new GetSpace("Hellblade: Senua's Sacrifice", "hellblade", S3_BASE_URL + "hellblade.jpg"),
                        new GetSpace("Helldivers", "helldivers", S3_BASE_URL + "helldivers.jpg"),
                        new GetSpace("Helltaker", "helltaker", S3_BASE_URL + "helltaker.jpg"),
                        new GetSpace("Her Story", "herstory", S3_BASE_URL + "herstory.jpg"),
                        new GetSpace("Hermitage: Strange Case Files", "hermitage", S3_BASE_URL + "hermitage.jpg"),
                        new GetSpace("Hero Siege", "herosiege", S3_BASE_URL + "herosiege.jpg"),
                        new GetSpace("Heroes of Hammerwatch", "heroeshammerwatch",
                                        S3_BASE_URL + "heroeshammerwatch.jpg"),
                        new GetSpace("Heroes of Might and Magic III", "homm3", S3_BASE_URL + "homm3.jpg"),
                        new GetSpace("Heroes of the Storm", "hots", S3_BASE_URL + "hots.jpg"),
                        new GetSpace("Hexcells", "hexcells", S3_BASE_URL + "hexcells.jpg"),
                        new GetSpace("Hidden Agenda", "hiddenagenda", S3_BASE_URL + "hiddenagenda.jpg"),
                        new GetSpace("Hidden Folks", "hiddenfolks", S3_BASE_URL + "hiddenfolks.jpg"),
                        new GetSpace("Hitman", "hitman", S3_BASE_URL + "hitman.jpg"),
                        new GetSpace("Hob", "hob", S3_BASE_URL + "hob.jpg"),
                        new GetSpace("Hokko Life", "hokkolife", S3_BASE_URL + "hokkolife.jpg"),
                        new GetSpace("Hollow Knight", "hk", S3_BASE_URL + "hk.jpg"),
                        new GetSpace("Hollow Knight: Silksong", "hksilksong", S3_BASE_URL + "hksilksong.jpg"),
                        new GetSpace("Homeworld", "homeworld", S3_BASE_URL + "homeworld.jpg"),
                        new GetSpace("Horizon Zero Dawn", "hzd", S3_BASE_URL + "hzd.jpg"),
                        new GetSpace("Hot Wheels Unleashed", "hotwheelsunleashed",
                                        S3_BASE_URL + "hotwheelsunleashed.jpg"),
                        new GetSpace("Hotline Miami", "hotlinemiami", S3_BASE_URL + "hotlinemiami.jpg"),
                        new GetSpace("House Flipper", "houseflipper", S3_BASE_URL + "houseflipper.jpg"),
                        new GetSpace("Human: Fall Flat", "humanfallflat", S3_BASE_URL + "humanfallflat.jpg"),
                        new GetSpace("Humankind", "humankind", S3_BASE_URL + "humankind.jpg"),
                        new GetSpace("Hunt: Showdown", "huntshowdown", S3_BASE_URL + "huntshowdown.jpg"),
                        new GetSpace("Hyper Light Drifter", "hyperlightdrifter", S3_BASE_URL + "hyperlightdrifter.jpg"),
                        new GetSpace("Hypnospace Outlaw", "hypnospaceoutlaw", S3_BASE_URL + "hypnospaceoutlaw.jpg"),
                        new GetSpace("I Am Bread", "iambread", S3_BASE_URL + "iambread.jpg"),
                        new GetSpace("I Wanna Be The Guy", "iwannabetheguy", S3_BASE_URL + "iwannabetheguy.jpg"),
                        new GetSpace("Ib", "ib", S3_BASE_URL + "ib.jpg"),
                        new GetSpace("Iconoclasts", "iconoclasts", S3_BASE_URL + "iconoclasts.jpg"),
                        new GetSpace("Ikaruga", "ikaruga", S3_BASE_URL + "ikaruga.jpg"),
                        new GetSpace("Ikenfell", "ikenfell", S3_BASE_URL + "ikenfell.jpg"),
                        new GetSpace("Illusion of Gaia", "illusiongaia", S3_BASE_URL + "illusiongaia.jpg"),
                        new GetSpace("Immortals Fenyx Rising", "immortalsfenyx", S3_BASE_URL + "immortalsfenyx.jpg"),
                        new GetSpace("Imperator: Rome", "imperatorrome", S3_BASE_URL + "imperatorrome.jpg"),
                        new GetSpace("In Other Waters", "inotherwaters", S3_BASE_URL + "inotherwaters.jpg"),
                        new GetSpace("I-Ninja", "ininja", S3_BASE_URL + "ininja.jpg"),
                        new GetSpace("Injustice", "injustice", S3_BASE_URL + "injustice.jpg"),
                        new GetSpace("Inscryption", "inscryption", S3_BASE_URL + "inscryption.jpg"),
                        new GetSpace("Inside", "inside", S3_BASE_URL + "inside.jpg"),
                        new GetSpace("Into the Breach", "intothebreach", S3_BASE_URL + "intothebreach.jpg"),
                        new GetSpace("Invisible Inc.", "invisibleinc", S3_BASE_URL + "invisibleinc.jpg"),
                        new GetSpace("It Takes Two", "itt", S3_BASE_URL + "itt.jpg"),
                        new GetSpace("Jackbox Party Pack", "jackbox", S3_BASE_URL + "jackbox.jpg"),
                        new GetSpace("Jalopy", "jalopy", S3_BASE_URL + "jalopy.jpg"),
                        new GetSpace("Journey", "journey", S3_BASE_URL + "journey.jpg"),
                        new GetSpace("Katamari Series", "katamari", S3_BASE_URL + "katamari.jpg"),
                        new GetSpace("Katana ZERO", "katanazero", S3_BASE_URL + "katanazero.jpg"),
                        new GetSpace("Keep Talking and Nobody Explodes", "keeptalking",
                                        S3_BASE_URL + "keeptalking.jpg"),
                        new GetSpace("Kena: Bridge of Spirits", "kena", S3_BASE_URL + "kena.jpg"),
                        new GetSpace("Kenshi", "kenshi", S3_BASE_URL + "kenshi.jpg"),
                        new GetSpace("Kerbal Space Program", "ksp", S3_BASE_URL + "ksp.jpg"),
                        new GetSpace("Kingdom Hearts", "kingdomhearts", S3_BASE_URL + "kingdomhearts.jpg"),
                        new GetSpace("Kingdoms and Castles", "kingdomscastles", S3_BASE_URL + "kingdomscastles.jpg"),
                        new GetSpace("Kingdoms of Amalur", "amalur", S3_BASE_URL + "amalur.jpg"),
                        new GetSpace("Kirby", "kirby", S3_BASE_URL + "kirby.jpg"),
                        new GetSpace("Klonoa", "klonoa", S3_BASE_URL + "klonoa.jpg"),
                        new GetSpace("Knockout City", "knockoutcity", S3_BASE_URL + "knockoutcity.jpg"),
                        new GetSpace("L.A. Noire", "lanoire", S3_BASE_URL + "lanoire.jpg"),
                        new GetSpace("Lakeview Cabin Collection", "lakeviewcabin", S3_BASE_URL + "lakeviewcabin.jpg"),
                        new GetSpace("La-Mulana", "lamulana", S3_BASE_URL + "lamulana.jpg"),
                        new GetSpace("Layers of Fear", "layersoffear", S3_BASE_URL + "layersoffear.jpg"),
                        new GetSpace("League of Legends", "lol", S3_BASE_URL + "lol.jpg"),
                        new GetSpace("Left 4 Dead", "l4d", S3_BASE_URL + "l4d.jpg"),
                        new GetSpace("Legacy of Kain", "legacyofkain", S3_BASE_URL + "legacyofkain.jpg"),
                        new GetSpace("Legend of Zelda: Breath of the Wild", "botw", S3_BASE_URL + "botw.jpg"),
                        new GetSpace("Legend of Zelda: Tears of the Kingdom", "totk", S3_BASE_URL + "totk.jpg"),
                        new GetSpace("LEGO Star Wars", "legostarwars", S3_BASE_URL + "legostarwars.jpg"),
                        new GetSpace("Lethal League", "lethalleague", S3_BASE_URL + "lethalleague.jpg"),
                        new GetSpace("Life is Strange", "lifeisstrange", S3_BASE_URL + "lifeisstrange.jpg"),
                        new GetSpace("Little Inferno", "littleinferno", S3_BASE_URL + "littleinferno.jpg"),
                        new GetSpace("Little Nightmares II", "littlenightmares2",
                                        S3_BASE_URL + "littlenightmares2.jpg"),
                        new GetSpace("LittleBigPlanet", "littlebigplanet", S3_BASE_URL + "littlebigplanet.jpg"),
                        new GetSpace("Lobotomy Corporation", "lobotomycorp", S3_BASE_URL + "lobotomycorp.jpg"),
                        new GetSpace("Lone Echo", "loneecho", S3_BASE_URL + "loneecho.jpg"),
                        new GetSpace("Loop Hero", "loophero", S3_BASE_URL + "loophero.jpg"),
                        new GetSpace("Lost in Random", "lostinrandom", S3_BASE_URL + "lostinrandom.jpg"),

                        new GetSpace("Machinarium", "machinarium", S3_BASE_URL + "machinarium.jpg"),
                        new GetSpace("Madden", "madden", S3_BASE_URL + "madden.jpg"),
                        new GetSpace("Mafia", "mafia", S3_BASE_URL + "mafia.jpg"),
                        new GetSpace("Magicka", "magicka", S3_BASE_URL + "magicka.jpg"),
                        new GetSpace("Maneater", "maneater", S3_BASE_URL + "maneater.jpg"),
                        new GetSpace("Manifold Garden", "manifoldgarden", S3_BASE_URL + "manifoldgarden.jpg"),
                        new GetSpace("Mario", "mario", S3_BASE_URL + "mario.jpg"),
                        new GetSpace("Mark of the Ninja", "markofninja", S3_BASE_URL + "markofninja.jpg"),
                        new GetSpace("Mass Effect", "masseffect", S3_BASE_URL + "masseffect.jpg"),
                        new GetSpace("Max Payne", "maxpayne", S3_BASE_URL + "maxpayne.jpg"),
                        new GetSpace("Mechwarrior", "mechwarrior", S3_BASE_URL + "mechwarrior.jpg"),
                        new GetSpace("Medieval Dynasty", "medievaldynasty", S3_BASE_URL + "medievaldynasty.jpg"),
                        new GetSpace("Mega Man", "megaman", S3_BASE_URL + "megaman.jpg"),
                        new GetSpace("Metal Gear", "metalgear", S3_BASE_URL + "metalgear.jpg"),
                        new GetSpace("Metal Slug", "metalslug", S3_BASE_URL + "metalslug.jpg"),
                        new GetSpace("Metro Exodus", "metroexodus", S3_BASE_URL + "metroexodus.jpg"),
                        new GetSpace("Metroid Dread", "metroiddread", S3_BASE_URL + "metroiddread.jpg"),
                        new GetSpace("Microsoft Flight Simulator", "msflightsim", S3_BASE_URL + "msflightsim.jpg"),
                        new GetSpace("Minecraft", "minecraft", S3_BASE_URL + "minecraft.jpg"),
                        new GetSpace("Minit", "minit", S3_BASE_URL + "minit.jpg"),
                        new GetSpace("Mirror's Edge", "mirrorsedge", S3_BASE_URL + "mirrorsedge.jpg"),
                        new GetSpace("MLB The Show", "theshow", S3_BASE_URL + "theshow.jpg"),
                        new GetSpace("Monster Hunter", "monsterhunter", S3_BASE_URL + "monsterhunter.jpg"),
                        new GetSpace("Monster Train", "monstertrain", S3_BASE_URL + "monstertrain.jpg"),
                        new GetSpace("Moonlighter", "moonlighter", S3_BASE_URL + "moonlighter.jpg"),
                        new GetSpace("Mordhau", "mordhau", S3_BASE_URL + "mordhau.jpg"),
                        new GetSpace("Mortal Kombat", "mk", S3_BASE_URL + "mk.jpg"),
                        new GetSpace("Mount and Blade", "mnb", S3_BASE_URL + "mnb.jpg"),
                        new GetSpace("Moving Out", "movingout", S3_BASE_URL + "movingout.jpg"),
                        new GetSpace("Mudrunner", "mudrunner", S3_BASE_URL + "mudrunner.jpg"),
                        new GetSpace("Mundaun", "mundaun", S3_BASE_URL + "mundaun.jpg"),
                        new GetSpace("My Friend Pedro", "myfriendpedro", S3_BASE_URL + "myfriendpedro.jpg"),
                        new GetSpace("My Summer Car", "mysummercar", S3_BASE_URL + "mysummercar.jpg"),
                        new GetSpace("My Time at Portia", "mytimeatportia", S3_BASE_URL + "mytimeatportia.jpg"),
                        new GetSpace("NBA2K", "nba2k", S3_BASE_URL + "nba2k.jpg"),
                        new GetSpace("New World", "newworld", S3_BASE_URL + "newworld.jpg"),
                        new GetSpace("NHL", "eanhl", S3_BASE_URL + "eanhl.jpg"),
                        new GetSpace("NieR Replicant", "nierreplicant", S3_BASE_URL + "nierreplicant.jpg"),
                        new GetSpace("NieR: Automata", "nierautomata", S3_BASE_URL + "nierautomata.jpg"),
                        new GetSpace("Night in the Woods", "nitw", S3_BASE_URL + "nitw.jpg"),
                        new GetSpace("Ninety-Nine Nights", "99nights", S3_BASE_URL + "99nights.jpg"),
                        new GetSpace("Nioh", "nioh", S3_BASE_URL + "nioh.jpg"),
                        new GetSpace("Nioh 2", "nioh2", S3_BASE_URL + "nioh2.jpg"),
                        new GetSpace("No Man's Sky", "nms", S3_BASE_URL + "nms.jpg"),
                        new GetSpace("No More Heroes", "nomoroheroes", S3_BASE_URL + "nomoroheroes.jpg"),
                        new GetSpace("Noita", "noita", S3_BASE_URL + "noita.jpg"),
                        new GetSpace("Octodad", "octodad", S3_BASE_URL + "octodad.jpg"),
                        new GetSpace("Oddworld", "oddworld", S3_BASE_URL + "oddworld.jpg"),
                        new GetSpace("Okami", "okami", S3_BASE_URL + "okami.jpg"),
                        new GetSpace("One Finger Death Punch", "onefingerdeathpunch",
                                        S3_BASE_URL + "onefingerdeathpunch.jpg"),
                        new GetSpace("Opus Magnum", "opusmagnum", S3_BASE_URL + "opusmagnum.jpg"),
                        new GetSpace("Ori and the Blind Forest", "oriblindforest", S3_BASE_URL + "oriblindforest.jpg"),
                        new GetSpace("Ori and the Will of the Wisps", "oriwisps", S3_BASE_URL + "oriwisps.jpg"),
                        new GetSpace("Outer Wilds", "outerwilds", S3_BASE_URL + "outerwilds.jpg"),
                        new GetSpace("Outer Worlds", "outerworlds", S3_BASE_URL + "outerworlds.jpg"),
                        new GetSpace("Outlast", "outlast", S3_BASE_URL + "outlast.jpg"),
                        new GetSpace("Outriders", "outriders", S3_BASE_URL + "outriders.jpg"),
                        new GetSpace("Overcooked", "overcooked", S3_BASE_URL + "overcooked.jpg"),
                        new GetSpace("Overwatch", "overwatch", S3_BASE_URL + "overwatch.jpg"),
                        new GetSpace("Oxenfree", "oxenfree", S3_BASE_URL + "oxenfree.jpg"),
                        new GetSpace("Papers Please", "papersplease", S3_BASE_URL + "papersplease.jpg"),
                        new GetSpace("Path of Exile", "pathofexile", S3_BASE_URL + "pathofexile.jpg"),
                        new GetSpace("Payday", "payday", S3_BASE_URL + "payday.jpg"),
                        new GetSpace("Peggle", "peggle", S3_BASE_URL + "peggle.jpg"),
                        new GetSpace("Penumbra", "penumbra", S3_BASE_URL + "penumbra.jpg"),
                        new GetSpace("Persona", "persona", S3_BASE_URL + "persona.jpg"),
                        new GetSpace("Phasmophobia", "phasmophobia", S3_BASE_URL + "phasmophobia.jpg"),
                        new GetSpace("Phoenix Wright", "phoenixwright", S3_BASE_URL + "phoenixwright.jpg"),
                        new GetSpace("Pillars of Eternity", "pillarsofeternity", S3_BASE_URL + "pillarsofeternity.jpg"),
                        new GetSpace("Plague Inc.", "plagueinc", S3_BASE_URL + "plagueinc.jpg"),
                        new GetSpace("Planescape: Torment", "planescape", S3_BASE_URL + "planescape.jpg"),
                        new GetSpace("Planetside", "planetside", S3_BASE_URL + "planetside.jpg"),
                        new GetSpace("Plants vs. Zombies", "pvz", S3_BASE_URL + "pvz.jpg"),
                        new GetSpace("Pokemon", "pokemon", S3_BASE_URL + "pokemon.jpg"),
                        new GetSpace("Portal", "portal", S3_BASE_URL + "portal.jpg"),
                        new GetSpace("Prey", "prey", S3_BASE_URL + "prey.jpg"),
                        new GetSpace("Prison Architect", "prisonarchitect", S3_BASE_URL + "prisonarchitect.jpg"),
                        new GetSpace("Project Winter", "projectwinter", S3_BASE_URL + "projectwinter.jpg"),
                        new GetSpace("Prototype", "prototype", S3_BASE_URL + "prototype.jpg"),
                        new GetSpace("Psychonauts 2", "psychonauts2", S3_BASE_URL + "psychonauts2.jpg"),
                        new GetSpace("PUBG", "pubg", S3_BASE_URL + "pubg.jpg"),
                        new GetSpace("Pyre", "pyre", S3_BASE_URL + "pyre.jpg"),
                        new GetSpace("Quake", "quake", S3_BASE_URL + "quake.jpg"),
                        new GetSpace("Quantum Break", "quantumbreak", S3_BASE_URL + "quantumbreak.jpg"),
                        new GetSpace("Quiplash", "quiplash", S3_BASE_URL + "quiplash.jpg"),
                        new GetSpace("Race the Sun", "racethesun", S3_BASE_URL + "racethesun.jpg"),
                        new GetSpace("Rainbow Six Siege", "r6", S3_BASE_URL + "r6.jpg"),
                        new GetSpace("Rayman", "rayman", S3_BASE_URL + "rayman.jpg"),
                        new GetSpace("Realm of the Mad God", "rotmg", S3_BASE_URL + "rotmg.jpg"),
                        new GetSpace("Recore", "recore", S3_BASE_URL + "recore.jpg"),
                        new GetSpace("Red Dead Redemption", "rdr", S3_BASE_URL + "rdr.jpg"),
                        new GetSpace("Redout", "redout", S3_BASE_URL + "redout.jpg"),
                        new GetSpace("Renowned Explorers", "renownedexplorers", S3_BASE_URL + "renownedexplorers.jpg"),
                        new GetSpace("Republika", "republika", S3_BASE_URL + "republika.jpg"),
                        new GetSpace("Resident Evil", "residentevil", S3_BASE_URL + "residentevil.jpg"),
                        new GetSpace("Retro City Rampage", "retrocityrampage", S3_BASE_URL + "retrocityrampage.jpg"),
                        new GetSpace("Returnal", "returnal", S3_BASE_URL + "returnal.jpg"),
                        new GetSpace("Rimworld", "rimworld", S3_BASE_URL + "rimworld.jpg"),
                        new GetSpace("Risk of Rain", "riskofrain", S3_BASE_URL + "riskofrain.jpg"),
                        new GetSpace("Roblox", "roblox", S3_BASE_URL + "roblox.jpg"),
                        new GetSpace("Rock Band", "rockband", S3_BASE_URL + "rockband.jpg"),
                        new GetSpace("Rocket Arena", "rocketarena", S3_BASE_URL + "rocketarena.jpg"),
                        new GetSpace("Rocket League", "rocketleague", S3_BASE_URL + "rocketleague.jpg"),
                        new GetSpace("Rodina", "rodina", S3_BASE_URL + "rodina.jpg"),
                        new GetSpace("Rogue Legacy", "roguelegacy", S3_BASE_URL + "roguelegacy.jpg"),
                        new GetSpace("Roguelands", "roguelands", S3_BASE_URL + "roguelands.jpg"),
                        new GetSpace("Roller Coaster Tycoon", "rct", S3_BASE_URL + "rct.jpg"),
                        new GetSpace("Rounds", "rounds", S3_BASE_URL + "rounds.jpg"),
                        new GetSpace("Runescape", "runescape", S3_BASE_URL + "runescape.jpg"),
                        new GetSpace("Rust", "rust", S3_BASE_URL + "rust.jpg"),
                        new GetSpace("Ryse: Son of Rome", "ryse", S3_BASE_URL + "ryse.jpg"),
                        new GetSpace("S.T.A.L.K.E.R.", "stalker", S3_BASE_URL + "stalker.jpg"),
                        new GetSpace("Saint's Row", "saintsrow", S3_BASE_URL + "saintsrow.jpg"),
                        new GetSpace("Salt and Sanctuary", "saltandsanctuary", S3_BASE_URL + "saltandsanctuary.jpg"),
                        new GetSpace("Satisfactory", "satisfactory", S3_BASE_URL + "satisfactory.jpg"),
                        new GetSpace("Scribblenauts", "scribblenauts", S3_BASE_URL + "scribblenauts.jpg"),
                        new GetSpace("Sea of Thieves", "seaofthieves", S3_BASE_URL + "seaofthieves.jpg"),
                        new GetSpace("Sekiro", "sekiro", S3_BASE_URL + "sekiro.jpg"),
                        new GetSpace("Senran Kagura", "senrankagura", S3_BASE_URL + "senrankagura.jpg"),
                        new GetSpace("Shadow of the Colossus", "sotc", S3_BASE_URL + "sotc.jpg"),
                        new GetSpace("Shadow Tactics", "shadowtactics", S3_BASE_URL + "shadowtactics.jpg"),
                        new GetSpace("Shadowrun", "shadowrun", S3_BASE_URL + "shadowrun.jpg"),
                        new GetSpace("Shantae", "shantae", S3_BASE_URL + "shantae.jpg"),
                        new GetSpace("Shovel Knight", "shovelknight", S3_BASE_URL + "shovelknight.jpg"),
                        new GetSpace("Skyrim", "skyrim", S3_BASE_URL + "skyrim.jpg"),
                        new GetSpace("Slay the Spire", "slaythespire", S3_BASE_URL + "slaythespire.jpg"),
                        new GetSpace("Sleeping Dogs", "sleepingdogs", S3_BASE_URL + "sleepingdogs.jpg"),
                        new GetSpace("Slime Rancher", "slimerancher", S3_BASE_URL + "slimerancher.jpg"),
                        new GetSpace("Super Smash Bros", "smash", S3_BASE_URL + "smash.jpg"),
                        new GetSpace("Smite", "smite", S3_BASE_URL + "smite.jpg"),
                        new GetSpace("Snake Pass", "snakepass", S3_BASE_URL + "snakepass.jpg"),
                        new GetSpace("Sniper Elite", "sniperelite", S3_BASE_URL + "sniperelite.jpg"),
                        new GetSpace("Soma", "soma", S3_BASE_URL + "soma.jpg"),
                        new GetSpace("Sonic the Hedgehog", "sonic", S3_BASE_URL + "sonic.jpg"),
                        new GetSpace("Spider-Man", "spiderman", S3_BASE_URL + "spiderman.jpg"),
                        new GetSpace("Splitgate", "splitgate", S3_BASE_URL + "splitgate.jpg"),
                        new GetSpace("Spore", "spore", S3_BASE_URL + "spore.jpg"),
                        new GetSpace("Star Citizen", "starcitizen", S3_BASE_URL + "starcitizen.jpg"),
                        new GetSpace("Star Wars Battlefront", "swbattlefront", S3_BASE_URL + "swbattlefront.jpg"),
                        new GetSpace("StarCraft", "starcraft", S3_BASE_URL + "starcraft.jpg"),
                        new GetSpace("Stardew Valley", "stardewvalley", S3_BASE_URL + "stardewvalley.jpg"),
                        new GetSpace("Stellar Blade", "stellarblade", S3_BASE_URL + "stellarblade.jpg"),
                        new GetSpace("Stellaris", "stellaris", S3_BASE_URL + "stellaris.jpg"),
                        new GetSpace("Stranded Deep", "strandeddeep", S3_BASE_URL + "strandeddeep.jpg"),
                        new GetSpace("Stray", "stray", S3_BASE_URL + "stray.jpg"),
                        new GetSpace("Street Fighter", "streetfighter", S3_BASE_URL + "streetfighter.jpg"),
                        new GetSpace("Subnautica", "subnautica", S3_BASE_URL + "subnautica.jpg"),
                        new GetSpace("Subnautica: Below Zero", "subnauticabz", S3_BASE_URL + "subnauticabz.jpg"),
                        new GetSpace("Sunless Sea", "sunlesssea", S3_BASE_URL + "sunlesssea.jpg"),
                        new GetSpace("Super Hexagon", "superhexagon", S3_BASE_URL + "superhexagon.jpg"),
                        new GetSpace("Super Meat Boy", "supermeatboy", S3_BASE_URL + "supermeatboy.jpg"),
                        new GetSpace("Surgeon Simulator", "surgeonsim", S3_BASE_URL + "surgeonsim.jpg"),
                        new GetSpace("SWAT 4", "swat4", S3_BASE_URL + "swat4.jpg"),
                        new GetSpace("Tacoma", "tacoma", S3_BASE_URL + "tacoma.jpg"),
                        new GetSpace("Tales of Arise", "talesofarise", S3_BASE_URL + "talesofarise.jpg"),
                        new GetSpace("Team Fortress 2", "tf2", S3_BASE_URL + "tf2.jpg"),
                        new GetSpace("Teardown", "teardown", S3_BASE_URL + "teardown.jpg"),
                        new GetSpace("Tekken", "tekken", S3_BASE_URL + "tekken.jpg"),
                        new GetSpace("Temtem", "temtem", S3_BASE_URL + "temtem.jpg"),
                        new GetSpace("Terraria", "terraria", S3_BASE_URL + "terraria.jpg"),
                        new GetSpace("Tetris", "tetris", S3_BASE_URL + "tetris.jpg"),
                        new GetSpace("The Banner Saga", "bannersaga", S3_BASE_URL + "bannersaga.jpg"),
                        new GetSpace("The Beginner's Guide", "beginnersguide", S3_BASE_URL + "beginnersguide.jpg"),
                        new GetSpace("The Binding of Isaac", "bindingofisaac", S3_BASE_URL + "bindingofisaac.jpg"),
                        new GetSpace("The Blackout Club", "blackoutclub", S3_BASE_URL + "blackoutclub.jpg"),
                        new GetSpace("The Council", "thecouncil", S3_BASE_URL + "thecouncil.jpg"),
                        new GetSpace("The Escapists", "escapists", S3_BASE_URL + "escapists.jpg"),
                        new GetSpace("The Evil Within", "evilwithin", S3_BASE_URL + "evilwithin.jpg"),
                        new GetSpace("The First Descendant", "firstdescendant", S3_BASE_URL + "firstdescendant.jpg"),
                        new GetSpace("The Forest", "theforest", S3_BASE_URL + "theforest.jpg"),
                        new GetSpace("The Incredible Machine", "incrediblemachine",
                                        S3_BASE_URL + "incrediblemachine.jpg"),
                        new GetSpace("The Last of Us", "tlou", S3_BASE_URL + "tlou.jpg"),
                        new GetSpace("The Long Dark", "longdark", S3_BASE_URL + "longdark.jpg"),
                        new GetSpace("The Medium", "themedium", S3_BASE_URL + "themedium.jpg"),
                        new GetSpace("The Messenger", "themessenger", S3_BASE_URL + "themessenger.jpg"),
                        new GetSpace("The Pathless", "pathless", S3_BASE_URL + "pathless.jpg"),
                        new GetSpace("The Pedestrian", "pedestrian", S3_BASE_URL + "pedestrian.jpg"),
                        new GetSpace("The Room", "theroom", S3_BASE_URL + "theroom.jpg"),
                        new GetSpace("The Saboteur", "saboteur", S3_BASE_URL + "saboteur.jpg"),
                        new GetSpace("The Sims", "sims", S3_BASE_URL + "sims.jpg"),
                        new GetSpace("The Stanley Parable", "stanleyparable", S3_BASE_URL + "stanleyparable.jpg"),
                        new GetSpace("The Talos Principle", "talosprinciple", S3_BASE_URL + "talosprinciple.jpg"),
                        new GetSpace("The Vanishing of Ethan Carter", "ethancarter", S3_BASE_URL + "ethancarter.jpg"),
                        new GetSpace("The Witcher", "witcher", S3_BASE_URL + "witcher.jpg"),
                        new GetSpace("The Witcher II", "witcher2", S3_BASE_URL + "witcher2.jpg"),
                        new GetSpace("The Witcher III", "witcher3", S3_BASE_URL + "witcher3.jpg"),
                        new GetSpace("The Witness", "witness", S3_BASE_URL + "witness.jpg"),
                        new GetSpace("Thief", "thief", S3_BASE_URL + "thief.jpg"),
                        new GetSpace("This War of Mine", "thiswarofmine", S3_BASE_URL + "thiswarofmine.jpg"),
                        new GetSpace("Thronebreaker", "thronebreaker", S3_BASE_URL + "thronebreaker.jpg"),
                        new GetSpace("Timberborn", "timberborn", S3_BASE_URL + "timberborn.jpg"),
                        new GetSpace("Titanfall", "titanfall", S3_BASE_URL + "titanfall.jpg"),
                        new GetSpace("Titanfall 2", "titanfall2", S3_BASE_URL + "titanfall2.jpg"),
                        new GetSpace("To the Moon", "tothemoon", S3_BASE_URL + "tothemoon.jpg"),
                        new GetSpace("Torchlight", "torchlight", S3_BASE_URL + "torchlight.jpg"),
                        new GetSpace("Total War: Three Kingdoms", "threekingdoms", S3_BASE_URL + "threekingdoms.jpg"),
                        new GetSpace("Touhou Project", "touhou", S3_BASE_URL + "touhou.jpg"),
                        new GetSpace("Transistor", "transistor", S3_BASE_URL + "transistor.jpg"),
                        new GetSpace("Trials", "trials", S3_BASE_URL + "trials.jpg"),
                        new GetSpace("Tunic", "tunic", S3_BASE_URL + "tunic.jpg"),
                        new GetSpace("Turnip Boy Commits Tax Evasion", "turnipboy", S3_BASE_URL + "turnipboy.jpg"),
                        new GetSpace("Twelve Minutes", "12minutes", S3_BASE_URL + "12minutes.jpg"),
                        new GetSpace("Uncharted", "uncharted", S3_BASE_URL + "uncharted.jpg"),
                        new GetSpace("Undertale", "undertale", S3_BASE_URL + "undertale.jpg"),
                        new GetSpace("Unpacking", "unpacking", S3_BASE_URL + "unpacking.jpg"),
                        new GetSpace("Unravel", "unravel", S3_BASE_URL + "unravel.jpg"),
                        new GetSpace("Untitled Goose Game", "goosegame", S3_BASE_URL + "goosegame.jpg"),
                        new GetSpace("Valheim", "valheim", S3_BASE_URL + "valheim.jpg"),
                        new GetSpace("Valkyria Chronicles", "valkyriachronicles",
                                        S3_BASE_URL + "valkyriachronicles.jpg"),
                        new GetSpace("Valorant", "valorant", S3_BASE_URL + "valorant.jpg"),
                        new GetSpace("Vampire Survivors", "vampiresurvivors", S3_BASE_URL + "vampiresurvivors.jpg"),
                        new GetSpace("Vampire: The Masquerade - Bloodlines", "vtmb", S3_BASE_URL + "vtmb.jpg"),
                        new GetSpace("Vanquish", "vanquish", S3_BASE_URL + "vanquish.jpg"),
                        new GetSpace("Void Bastards", "voidbastards", S3_BASE_URL + "voidbastards.jpg"),
                        new GetSpace("Warframe", "warframe", S3_BASE_URL + "warframe.jpg"),
                        new GetSpace("Warhammer 4000: Space Marine", "wh4k", S3_BASE_URL + "wh4k.jpg"),
                        new GetSpace("Wasteland", "wasteland", S3_BASE_URL + "wasteland.jpg"),
                        new GetSpace("We Happy Few", "wehappyfew", S3_BASE_URL + "wehappyfew.jpg"),
                        new GetSpace("What Remains of Edith Finch", "edithfinch", S3_BASE_URL + "edithfinch.jpg"),
                        new GetSpace("Where the Water Tastes Like Wine", "waterlikewine",
                                        S3_BASE_URL + "waterlikewine.jpg"),
                        new GetSpace("Wilmot's Warehouse", "wilmotswarehouse", S3_BASE_URL + "wilmotswarehouse.jpg"),
                        new GetSpace("Wingspan", "wingspan", S3_BASE_URL + "wingspan.jpg"),
                        new GetSpace("Wipeout", "wipeout", S3_BASE_URL + "wipeout.jpg"),
                        new GetSpace("World of Goo", "worldofgoo", S3_BASE_URL + "worldofgoo.jpg"),
                        new GetSpace("World of Warcraft", "wow", S3_BASE_URL + "wow.jpg"),
                        new GetSpace("Worms", "worms", S3_BASE_URL + "worms.jpg"),
                        new GetSpace("Xcom", "xcom", S3_BASE_URL + "xcom.jpg"),
                        new GetSpace("XCOM 2", "xcom2", S3_BASE_URL + "xcom2.jpg"),
                        new GetSpace("Yooka-Laylee", "yookalaylee", S3_BASE_URL + "yookalaylee.jpg"),
                        new GetSpace("Yume Nikki", "yumenikki", S3_BASE_URL + "yumenikki.jpg"),
                        new GetSpace("Zero Escape", "zeroescape", S3_BASE_URL + "zeroescape.jpg"),
                        new GetSpace("Zomboid", "zomboid", S3_BASE_URL + "zomboid.jpg"),
                        new GetSpace("Morrowind", "morrowind", S3_BASE_URL + "morrowind.jpg"),
                        new GetSpace("Oblivion", "oblivion", S3_BASE_URL + "oblivion.jpg"),
                        new GetSpace("Elder Scrolls Online", "tesonline", S3_BASE_URL + "tesonline.jpg"),
                        new GetSpace("Dragon Ball Sparking Zero", "sparkingzero", S3_BASE_URL + "sparkingzero.jpg"),
                        new GetSpace("League of Legends Esports", "lolesports", S3_BASE_URL + "lolesports.jpg"),
                        new GetSpace("Valorant Esports", "valorantesports", S3_BASE_URL + "valorantesports.jpg"));

        public static Map<String, GetSpace> SPACE_MAP = SPACES.stream()
                        .collect(Collectors.toMap(space -> space.id, space -> space));
}