package com.apollo.shared;

import com.apollo.shared.pojos.GetSpace;

import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class ApolloSpaces {
        private static final String S3_BASE_URL = "https://yoapollo.s3.us-east-2.amazonaws.com/spaces/";

        public static final List<GetSpace> SPACES = Arrays.asList(
                        new GetSpace("7 Days to Die", "7todie", S3_BASE_URL + "7todie.webp"),
                        new GetSpace("A Hat in Time", "ahatintime", S3_BASE_URL + "ahatintime.webp"),
                        new GetSpace("A Plague Tale: Innocence", "aplaguetale", S3_BASE_URL + "aplaguetale.webp"),
                        new GetSpace("A Way Out", "awayout", S3_BASE_URL + "awayout.webp"),
                        new GetSpace("Ace Attorney", "aceattorney", S3_BASE_URL + "aceattorney.webp"),
                        new GetSpace("Adventure Quest", "adventurequest", S3_BASE_URL + "adventurequest.webp"),
                        new GetSpace("Age of Empires", "aoe", S3_BASE_URL + "aoe.webp"),
                        new GetSpace("Age of Wonders", "ageofwonders", S3_BASE_URL + "ageofwonders.webp"),
                        new GetSpace("Alan Wake", "alanwake", S3_BASE_URL + "alanwake.webp"),
                        new GetSpace("Alien: Isolation", "alienisolation", S3_BASE_URL + "alienisolation.webp"),
                        new GetSpace("Aliens vs. Predator", "avp", S3_BASE_URL + "avp.webp"),
                        new GetSpace("American Truck Simulator", "americantrucksim",
                                        S3_BASE_URL + "americantrucksim.webp"),
                        new GetSpace("Among Us", "amongus", S3_BASE_URL + "amongus.webp"),
                        new GetSpace("Animal Crossing", "animalcrossing", S3_BASE_URL + "animalcrossing.webp"),
                        new GetSpace("Anno 1800", "anno1800", S3_BASE_URL + "anno1800.webp"),
                        new GetSpace("Antichamber", "antichamber", S3_BASE_URL + "antichamber.webp"),
                        new GetSpace("Apex Legends", "apex", S3_BASE_URL + "apex.webp"),
                        new GetSpace("Ark: Survival Evolved", "arksurvival", S3_BASE_URL + "arksurvival.webp"),
                        new GetSpace("Arma 3", "arma3", S3_BASE_URL + "arma3.webp"),
                        new GetSpace("Armello", "armello", S3_BASE_URL + "armello.webp"),
                        new GetSpace("Assassin's Creed", "assassinscreed", S3_BASE_URL + "assassinscreed.webp"),
                        new GetSpace("Astro Bot", "astrobot", S3_BASE_URL + "astrobot.webp"),
                        new GetSpace("Astroneer", "astroneer", S3_BASE_URL + "astroneer.webp"),
                        new GetSpace("Atelier Ryza", "atelierryza", S3_BASE_URL + "atelierryza.webp"),
                        new GetSpace("Baba Is You", "babaisyou", S3_BASE_URL + "babaisyou.webp"),
                        new GetSpace("Back 4 Blood", "back4blood", S3_BASE_URL + "back4blood.webp"),
                        new GetSpace("Balatro", "balatro", S3_BASE_URL + "balatro.webp"),
                        new GetSpace("Baldur's Gate 3", "bg3", S3_BASE_URL + "bg3.webp"),
                        new GetSpace("Banana", "banana", S3_BASE_URL + "banana.webp"),
                        new GetSpace("Batman: Arkham Knight", "batmanak", S3_BASE_URL + "batmanak.webp"),
                        new GetSpace("Battleblock Theater", "battleblock", S3_BASE_URL + "battleblock.webp"),
                        new GetSpace("Battlefield", "battlefield", S3_BASE_URL + "battlefield.webp"),
                        new GetSpace("Battletech", "battletech", S3_BASE_URL + "battletech.webp"),
                        new GetSpace("Beat Saber", "beatsaber", S3_BASE_URL + "beatsaber.webp"),
                        new GetSpace("Besiege", "besiege", S3_BASE_URL + "besiege.webp"),
                        new GetSpace("Beyond: Two Souls", "beyondtwosouls", S3_BASE_URL + "beyondtwosouls.webp"),
                        new GetSpace("Biomutant", "biomutant", S3_BASE_URL + "biomutant.webp"),
                        new GetSpace("Bioshock", "bioshock", S3_BASE_URL + "bioshock.webp"),
                        new GetSpace("Black Desert Online", "blackdesert", S3_BASE_URL + "blackdesert.webp"),
                        new GetSpace("Black Mesa", "blackmesa", S3_BASE_URL + "blackmesa.webp"),
                        new GetSpace("Black Myth: Wukong", "wukong", S3_BASE_URL + "wukong.webp"),
                        new GetSpace("Blasphemous 2", "blasphemous", S3_BASE_URL + "blasphemous.webp"),
                        new GetSpace("Bloodborne", "bloodborne", S3_BASE_URL + "bloodborne.webp"),
                        new GetSpace("Bloons Tower Defense", "btd", S3_BASE_URL + "btd.webp"),
                        new GetSpace("Borderlands", "borderlands", S3_BASE_URL + "borderlands.webp"),
                        new GetSpace("Bully", "bully", S3_BASE_URL + "bully.webp"),
                        new GetSpace("Call of Duty", "cod", S3_BASE_URL + "cod.webp"),
                        new GetSpace("Car Mechanic Simulator", "carmechsim", S3_BASE_URL + "carmechsim.webp"),
                        new GetSpace("Castle Crashers", "castlecrashers", S3_BASE_URL + "castlecrashers.webp"),
                        new GetSpace("Castlevania", "castlevania", S3_BASE_URL + "castlevania.webp"),
                        new GetSpace("Celeste", "celeste", S3_BASE_URL + "celeste.webp"),
                        new GetSpace("Children of Morta", "childrenofmorta", S3_BASE_URL + "childrenofmorta.webp"),
                        new GetSpace("Chivalry 2", "chivalry2", S3_BASE_URL + "chivalry2.webp"),
                        new GetSpace("Cities Skylines", "citiesskylines", S3_BASE_URL + "citiesskylines.webp"),
                        new GetSpace("Civilization Series", "civ", S3_BASE_URL + "civ.webp"),
                        new GetSpace("Clash of Clans", "coc", S3_BASE_URL + "coc.webp"),
                        new GetSpace("Clash Royale", "clashroyale", S3_BASE_URL + "clashroyale.webp"),
                        new GetSpace("Company of Heroes", "companyofheroes", S3_BASE_URL + "companyofheroes.webp"),
                        new GetSpace("Control", "control", S3_BASE_URL + "control.webp"),
                        new GetSpace("Crash Bandicoot", "crashbandicoot", S3_BASE_URL + "crashbandicoot.webp"),
                        new GetSpace("Crypt of the NecroDancer", "cryptnecrodancer",
                                        S3_BASE_URL + "cryptnecrodancer.webp"),
                        new GetSpace("Crysis", "crysis", S3_BASE_URL + "crysis.webp"),
                        new GetSpace("Cuphead", "cuphead", S3_BASE_URL + "cuphead.webp"),
                        new GetSpace("Cyberpunk 2077", "cyberpunk2077", S3_BASE_URL + "cyberpunk2077.webp"),
                        new GetSpace("Dark Souls 1", "darksouls", S3_BASE_URL + "darksouls.webp"),
                        new GetSpace("Dark Souls 2", "darksouls2", S3_BASE_URL + "darksouls2.webp"),
                        new GetSpace("Dark Souls 3", "darksouls3", S3_BASE_URL + "darksouls3.webp"),
                        new GetSpace("Darkest Dungeon", "darkestdungeon", S3_BASE_URL + "darkestdungeon.webp"),
                        new GetSpace("Darksiders", "darksiders", S3_BASE_URL + "darksiders.webp"),
                        new GetSpace("Darkwood", "darkwood", S3_BASE_URL + "darkwood.webp"),
                        new GetSpace("DayZ", "dayz", S3_BASE_URL + "dayz.webp"),
                        new GetSpace("Dead by Daylight", "dbd", S3_BASE_URL + "dbd.webp"),
                        new GetSpace("Death Stranding", "deathstranding", S3_BASE_URL + "deathstranding.webp"),
                        new GetSpace("Deathloop", "deathloop", S3_BASE_URL + "deathloop.webp"),
                        new GetSpace("Deep Rock Galactic", "deeprockgalactic", S3_BASE_URL + "deeprockgalactic.webp"),
                        new GetSpace("Demons Souls", "demonssouls", S3_BASE_URL + "demonssouls.webp"),
                        new GetSpace("Descenders", "descenders", S3_BASE_URL + "descenders.webp"),
                        new GetSpace("Destiny 2", "destiny2", S3_BASE_URL + "destiny2.webp"),
                        new GetSpace("Detroit: Become Human", "becomehuman", S3_BASE_URL + "becomehuman.webp"),
                        new GetSpace("Deus Ex", "deus-ex", S3_BASE_URL + "deus-ex.webp"),
                        new GetSpace("Devil May Cry", "dmc", S3_BASE_URL + "dmc.webp"),
                        new GetSpace("Diablo", "diablo", S3_BASE_URL + "diablo.webp"),
                        new GetSpace("Disco Elysium", "discoelysium", S3_BASE_URL + "discoelysium.webp"),
                        new GetSpace("Dishonored 2", "dishonored", S3_BASE_URL + "dishonored.webp"),
                        new GetSpace("Divinity: Original Sin 2", "divinity2", S3_BASE_URL + "divinity2.webp"),
                        new GetSpace("Don't Starve Together", "dontstarve", S3_BASE_URL + "dontstarve.webp"),
                        new GetSpace("Doom Eternal", "doom", S3_BASE_URL + "doom.webp"),
                        new GetSpace("Dota 2", "dota2", S3_BASE_URL + "dota2.webp"),
                        new GetSpace("Dragon Age", "dragonage", S3_BASE_URL + "dragonage.webp"),
                        new GetSpace("Dragon Ball FighterZ", "dbfighterz", S3_BASE_URL + "dbfighterz.webp"),
                        new GetSpace("Dragon Ball Sparking Zero", "sparkingzero", S3_BASE_URL + "sparkingzero.webp"),
                        new GetSpace("Dragon Quest", "dragonquest", S3_BASE_URL + "dragonquest.webp"),
                        new GetSpace("DragonFable", "dragonfable", S3_BASE_URL + "dragonfable.webp"),
                        new GetSpace("Dragon's Dogma", "dragonsdogma", S3_BASE_URL + "dragonsdogma.webp"),
                        new GetSpace("Dungeon Defenders", "dungeondefenders", S3_BASE_URL + "dungeondefenders.webp"),
                        new GetSpace("Dying Light", "dyinglight", S3_BASE_URL + "dyinglight.webp"),
                        new GetSpace("Dyson Sphere Program", "dysonsphere", S3_BASE_URL + "dysonsphere.webp"),
                        new GetSpace("EA FC", "eafc", S3_BASE_URL + "eafc.webp"),
                        new GetSpace("Eco", "eco", S3_BASE_URL + "eco.webp"),
                        new GetSpace("Elden Ring", "eldenring", S3_BASE_URL + "eldenring.webp"),
                        new GetSpace("Elder Scrolls Online", "tesonline", S3_BASE_URL + "tesonline.webp"),
                        new GetSpace("Elex", "elex", S3_BASE_URL + "elex.webp"),
                        new GetSpace("Elite Dangerous", "elitedangerous", S3_BASE_URL + "elitedangerous.webp"),
                        new GetSpace("Enderal: Forgotten Stories", "enderal", S3_BASE_URL + "enderal.webp"),
                        new GetSpace("Endless Space", "endlessspace", S3_BASE_URL + "endlessspace.webp"),
                        new GetSpace("Enter the Gungeon", "enterthegungeon", S3_BASE_URL + "enterthegungeon.webp"),
                        new GetSpace("Eternal Return", "eternalreturn", S3_BASE_URL + "eternalreturn.webp"),
                        new GetSpace("Europa Universalis IV", "eu4", S3_BASE_URL + "eu4.webp"),
                        new GetSpace("EVE Online", "eveonline", S3_BASE_URL + "eveonline.webp"),
                        new GetSpace("Factorio", "factorio", S3_BASE_URL + "factorio.webp"),
                        new GetSpace("Fall Guys", "fallguys", S3_BASE_URL + "fallguys.webp"),
                        new GetSpace("Fallout", "fallout", S3_BASE_URL + "fallout.webp"),
                        new GetSpace("Far Cry", "farcry", S3_BASE_URL + "farcry.webp"),
                        new GetSpace("Final Fantasy", "ff", S3_BASE_URL + "ff.webp"),
                        new GetSpace("Fire Emblem", "fireemblem", S3_BASE_URL + "fireemblem.webp"),
                        new GetSpace("Five Nights at Freddy's", "fnaf", S3_BASE_URL + "fnaf.webp"),
                        new GetSpace("For Honor", "forhonor", S3_BASE_URL + "forhonor.webp"),
                        new GetSpace("Forager", "forager", S3_BASE_URL + "forager.webp"),
                        new GetSpace("Fortnite", "fortnite", S3_BASE_URL + "fortnite.webp"),
                        new GetSpace("Forza", "forza", S3_BASE_URL + "forza.webp"),
                        new GetSpace("Frostpunk", "frostpunk", S3_BASE_URL + "frostpunk.webp"),
                        new GetSpace("FTL: Faster Than Light", "ftl", S3_BASE_URL + "ftl.webp"),
                        new GetSpace("Gang Beasts", "gangbeasts", S3_BASE_URL + "gangbeasts.webp"),
                        new GetSpace("Garry's Mod", "gmod", S3_BASE_URL + "gmod.webp"),
                        new GetSpace("Genshin Impact", "genshinimpact", S3_BASE_URL + "genshinimpact.webp"),
                        new GetSpace("Geometry Dash", "geometrydash", S3_BASE_URL + "geometrydash.webp"),
                        new GetSpace("Getting Over It", "gettingoverit", S3_BASE_URL + "gettingoverit.webp"),
                        new GetSpace("Ghost of Tsushima", "tsushima", S3_BASE_URL + "tsushima.webp"),
                        new GetSpace("Ghostwire: Tokyo", "ghostwiretokyo", S3_BASE_URL + "ghostwiretokyo.webp"),
                        new GetSpace("Goat Simulator", "goatsim", S3_BASE_URL + "goatsim.webp"),
                        new GetSpace("God of War", "gow", S3_BASE_URL + "gow.webp"),
                        new GetSpace("Grand Theft Auto", "gta", S3_BASE_URL + "gta.webp"),
                        new GetSpace("Graveyard Keeper", "graveyardkeeper", S3_BASE_URL + "graveyardkeeper.webp"),
                        new GetSpace("Grim Dawn", "grimdawn", S3_BASE_URL + "grimdawn.webp"),
                        new GetSpace("Gris", "gris", S3_BASE_URL + "gris.webp"),
                        new GetSpace("Guild Wars", "guildwars", S3_BASE_URL + "guildwars.webp"),
                        new GetSpace("Guilty Gear", "guiltygear", S3_BASE_URL + "guiltygear.webp"),
                        new GetSpace("Guitar Hero", "guitarhero", S3_BASE_URL + "guitarhero.webp"),
                        new GetSpace("Gunfire Reborn", "gunfirereborn", S3_BASE_URL + "gunfirereborn.webp"),
                        new GetSpace("Hades", "hades", S3_BASE_URL + "hades.webp"),
                        new GetSpace("Half-Life", "halflife", S3_BASE_URL + "halflife.webp"),
                        new GetSpace("Halo", "halo", S3_BASE_URL + "halo.webp"),
                        new GetSpace("Hearthstone", "hearthstone", S3_BASE_URL + "hearthstone.webp"),
                        new GetSpace("Hearts of Iron", "heartsofiron", S3_BASE_URL + "heartsofiron.webp"),
                        new GetSpace("Heavy Rain", "heavyrain", S3_BASE_URL + "heavyrain.webp"),
                        new GetSpace("Hellblade: Senua's Sacrifice", "hellblade", S3_BASE_URL + "hellblade.webp"),
                        new GetSpace("Helldivers 2", "helldivers", S3_BASE_URL + "helldivers.webp"),
                        new GetSpace("Hero Siege", "herosiege", S3_BASE_URL + "herosiege.webp"),
                        new GetSpace("Heroes of Might and Magic", "homm", S3_BASE_URL + "homm.webp"),
                        new GetSpace("Heroes of the Storm", "hots", S3_BASE_URL + "hots.webp"),
                        new GetSpace("Hero's Land", "herosland", S3_BASE_URL + "herosland.webp"),
                        new GetSpace("Hitman", "hitman", S3_BASE_URL + "hitman.webp"),
                        new GetSpace("Hollow Knight", "hk", S3_BASE_URL + "hk.webp"),
                        new GetSpace("Horizon Forbidden West", "hfw", S3_BASE_URL + "hfw.webp"),
                        new GetSpace("Horizon Zero Dawn", "hzd", S3_BASE_URL + "hzd.webp"),
                        new GetSpace("Hotline Miami", "hotlinemiami", S3_BASE_URL + "hotlinemiami.webp"),
                        new GetSpace("House Flipper", "houseflipper", S3_BASE_URL + "houseflipper.webp"),
                        new GetSpace("Human: Fall Flat", "hff", S3_BASE_URL + "hff.webp"),
                        new GetSpace("Humankind", "humankind", S3_BASE_URL + "humankind.webp"),
                        new GetSpace("Hunt: Showdown 1896", "huntshowdown", S3_BASE_URL + "huntshowdown.webp"),
                        new GetSpace("Imperator: Rome", "imperatorrome", S3_BASE_URL + "imperatorrome.webp"),
                        new GetSpace("Injustice", "injustice", S3_BASE_URL + "injustice.webp"),
                        new GetSpace("Inscryption", "inscryption", S3_BASE_URL + "inscryption.webp"),
                        new GetSpace("Inside the Backrooms", "insidethebackrooms",
                                        S3_BASE_URL + "insidethebackrooms.webp"),
                        new GetSpace("It Takes Two", "itt", S3_BASE_URL + "itt.webp"),
                        new GetSpace("Katamari Series", "katamari", S3_BASE_URL + "katamari.webp"),
                        new GetSpace("Kenshi", "kenshi", S3_BASE_URL + "kenshi.webp"),
                        new GetSpace("Kerbal Space Program", "ksp", S3_BASE_URL + "ksp.webp"),
                        new GetSpace("Kingdom Hearts", "kingdomhearts", S3_BASE_URL + "kingdomhearts.webp"),
                        new GetSpace("Kingdoms and Castles", "kac", S3_BASE_URL + "kac.webp"),
                        new GetSpace("Kirby", "kirby", S3_BASE_URL + "kirby.webp"),
                        new GetSpace("Knockout City", "kocity", S3_BASE_URL + "kocity.webp"),
                        new GetSpace("L.A. Noire", "lanoire", S3_BASE_URL + "lanoire.webp"),
                        new GetSpace("League of Legends", "lol", S3_BASE_URL + "lol.webp"),
                        new GetSpace("Left 4 Dead", "l4d", S3_BASE_URL + "l4d.webp"),
                        new GetSpace("Legend of Zelda: Breath of the Wild", "botw", S3_BASE_URL + "botw.webp"),
                        new GetSpace("Legend of Zelda: Tears of the Kingdom", "totk", S3_BASE_URL + "totk.webp"),
                        new GetSpace("LEGO Star Wars", "legostarwars", S3_BASE_URL + "legostarwars.webp"),
                        new GetSpace("Life is Strange", "lifeisstrange", S3_BASE_URL + "lifeisstrange.webp"),
                        new GetSpace("Like a Dragon: Infinite Wealth", "likeadragon", S3_BASE_URL + "likeadragon.webp"),
                        new GetSpace("Little Nightmares II", "ln2", S3_BASE_URL + "ln2.webp"),
                        new GetSpace("LittleBigPlanet", "lbp", S3_BASE_URL + "lbp.webp"),
                        new GetSpace("Lobotomy Corporation", "lobotomycorp", S3_BASE_URL + "lobotomycorp.webp"),
                        new GetSpace("Loop Hero", "loophero", S3_BASE_URL + "loophero.webp"),
                        new GetSpace("Madden", "madden", S3_BASE_URL + "madden.webp"),
                        new GetSpace("Mafia", "mafia", S3_BASE_URL + "mafia.webp"),
                        new GetSpace("Mario", "mario", S3_BASE_URL + "mario.webp"),
                        new GetSpace("Mass Effect", "masseffect", S3_BASE_URL + "masseffect.webp"),
                        new GetSpace("Max Payne", "maxpayne", S3_BASE_URL + "maxpayne.webp"),
                        new GetSpace("Medieval Dynasty", "meddynasty", S3_BASE_URL + "meddynasty.webp"),
                        new GetSpace("Mega Man", "megaman", S3_BASE_URL + "megaman.webp"),
                        new GetSpace("Metal Gear", "mg", S3_BASE_URL + "mg.webp"),
                        new GetSpace("Metal Slug", "metalslug", S3_BASE_URL + "metalslug.webp"),
                        new GetSpace("Metaphor: ReFantazio", "refantazio", S3_BASE_URL + "refantazio.webp"),
                        new GetSpace("Metro Exodus", "metroexodus", S3_BASE_URL + "metroexodus.webp"),
                        new GetSpace("Microsoft Flight Simulator", "msflightsim", S3_BASE_URL + "msflightsim.webp"),
                        new GetSpace("Minecraft", "minecraft", S3_BASE_URL + "minecraft.webp"),
                        new GetSpace("Mirror's Edge", "mirrorsedge", S3_BASE_URL + "mirrorsedge.webp"),
                        new GetSpace("MLB The Show", "theshow", S3_BASE_URL + "theshow.webp"),
                        new GetSpace("Monster Hunter", "monsterhunter", S3_BASE_URL + "monsterhunter.webp"),
                        new GetSpace("Monster Train", "monstertrain", S3_BASE_URL + "monstertrain.webp"),
                        new GetSpace("Mordhau", "mordhau", S3_BASE_URL + "mordhau.webp"),
                        new GetSpace("Morrowind", "morrowind", S3_BASE_URL + "morrowind.webp"),
                        new GetSpace("Mortal Kombat", "mk", S3_BASE_URL + "mk.webp"),
                        new GetSpace("Mount and Blade", "mnb", S3_BASE_URL + "mnb.webp"),
                        new GetSpace("Mudrunner", "mudrunner", S3_BASE_URL + "mudrunner.webp"),
                        new GetSpace("My Summer Car", "mysummercar", S3_BASE_URL + "mysummercar.webp"),
                        new GetSpace("My Time at Portia", "mytimeatportia", S3_BASE_URL + "mytimeatportia.webp"),
                        new GetSpace("NBA2K", "nba2k", S3_BASE_URL + "nba2k.webp"),
                        new GetSpace("Neva", "neva", S3_BASE_URL + "neva.webp"),
                        new GetSpace("New World: Aeternum", "newworld", S3_BASE_URL + "newworld.webp"),
                        new GetSpace("NHL", "eanhl", S3_BASE_URL + "eanhl.webp"),
                        new GetSpace("NieR Replicant", "nierreplicant", S3_BASE_URL + "nierreplicant.webp"),
                        new GetSpace("NieR: Automata", "nierautomata", S3_BASE_URL + "nierautomata.webp"),
                        new GetSpace("Nioh", "nioh", S3_BASE_URL + "nioh.webp"),
                        new GetSpace("No Man's Sky", "nms", S3_BASE_URL + "nms.webp"),
                        new GetSpace("Noita", "noita", S3_BASE_URL + "noita.webp"),
                        new GetSpace("Oblivion", "oblivion", S3_BASE_URL + "oblivion.webp"),
                        new GetSpace("Okami", "okami", S3_BASE_URL + "okami.webp"),
                        new GetSpace("Ori", "ori", S3_BASE_URL + "ori.webp"),
                        new GetSpace("Outer Wilds", "outerwilds", S3_BASE_URL + "outerwilds.webp"),
                        new GetSpace("Outer Worlds", "outerworlds", S3_BASE_URL + "outerworlds.webp"),
                        new GetSpace("Overcooked", "overcooked", S3_BASE_URL + "overcooked.webp"),
                        new GetSpace("Overwatch 2", "ow2", S3_BASE_URL + "overwatch.webp"),
                        new GetSpace("Path of Exile", "pathofexile", S3_BASE_URL + "pathofexile.webp"),
                        new GetSpace("Payday", "payday", S3_BASE_URL + "payday.webp"),
                        new GetSpace("Persona", "persona", S3_BASE_URL + "persona.webp"),
                        new GetSpace("Pillars of Eternity", "pillarsofeternity",
                                        S3_BASE_URL + "pillarsofeternity.webp"),
                        new GetSpace("Plague Inc.", "plagueinc", S3_BASE_URL + "plagueinc.webp"),
                        new GetSpace("Planetside 2", "planetside", S3_BASE_URL + "planetside.webp"),
                        new GetSpace("Plants vs. Zombies", "pvz", S3_BASE_URL + "pvz.webp"),
                        new GetSpace("Pokemon", "pokemon", S3_BASE_URL + "pokemon.webp"),
                        new GetSpace("Portal", "portal", S3_BASE_URL + "portal.webp"),
                        new GetSpace("Prey", "prey", S3_BASE_URL + "prey.webp"),
                        new GetSpace("Prison Architect", "prisonarchitect", S3_BASE_URL + "prisonarchitect.webp"),
                        new GetSpace("Project Zomboid", "zomboid", S3_BASE_URL + "zomboid.webp"),
                        new GetSpace("PUBG", "pubg", S3_BASE_URL + "pubg.webp"),
                        new GetSpace("Quake", "quake", S3_BASE_URL + "quake.webp"),
                        new GetSpace("Rainbow Six Siege", "r6", S3_BASE_URL + "r6.webp"),
                        new GetSpace("Realm of the Mad God", "rotmg", S3_BASE_URL + "rotmg.webp"),
                        new GetSpace("Red Dead Redemption", "rdr", S3_BASE_URL + "rdr.webp"),
                        new GetSpace("Resident Evil", "residentevil", S3_BASE_URL + "residentevil.webp"),
                        new GetSpace("Rimworld", "rimworld", S3_BASE_URL + "rimworld.webp"),
                        new GetSpace("Risk of Rain", "riskofrain", S3_BASE_URL + "riskofrain.webp"),
                        new GetSpace("Roblox", "roblox", S3_BASE_URL + "roblox.webp"),
                        new GetSpace("Rock Band", "rockband", S3_BASE_URL + "rockband.webp"),
                        new GetSpace("Rocket League", "rocketleague", S3_BASE_URL + "rocketleague.webp"),
                        new GetSpace("Rogue Legacy", "roguelegacy", S3_BASE_URL + "roguelegacy.webp"),
                        new GetSpace("RollerCoaster Tycoon", "rct", S3_BASE_URL + "rct.webp"),
                        new GetSpace("Runescape", "runescape", S3_BASE_URL + "runescape.webp"),
                        new GetSpace("Rust", "rust", S3_BASE_URL + "rust.webp"),
                        new GetSpace("Saint's Row", "saintsrow", S3_BASE_URL + "saintsrow.webp"),
                        new GetSpace("Satisfactory", "satisfactory", S3_BASE_URL + "satisfactory.webp"),
                        new GetSpace("Sea of Thieves", "seaofthieves", S3_BASE_URL + "seaofthieves.webp"),
                        new GetSpace("Sekiro", "sekiro", S3_BASE_URL + "sekiro.webp"),
                        new GetSpace("Shadow of Mordor", "som", S3_BASE_URL + "som.webp"),
                        new GetSpace("Shadow of the Colossus", "sotc", S3_BASE_URL + "sotc.webp"),
                        new GetSpace("Shadow of War", "sow", S3_BASE_URL + "sow.webp"),
                        new GetSpace("Silent Hill 2", "silenthill", S3_BASE_URL + "silenthill.webp"),
                        new GetSpace("Skyrim", "skyrim", S3_BASE_URL + "skyrim.webp"),
                        new GetSpace("Slay the Spire", "slaythespire", S3_BASE_URL + "slaythespire.webp"),
                        new GetSpace("Sleeping Dogs", "sleepingdogs", S3_BASE_URL + "sleepingdogs.webp"),
                        new GetSpace("Slime Rancher", "slimerancher", S3_BASE_URL + "slimerancher.webp"),
                        new GetSpace("Smite", "smite", S3_BASE_URL + "smite.webp"),
                        new GetSpace("Sniper Elite", "sniperelite", S3_BASE_URL + "sniperelite.webp"),
                        new GetSpace("Sonic the Hedgehog", "sonic", S3_BASE_URL + "sonic.webp"),
                        new GetSpace("Spider-Man", "spiderman", S3_BASE_URL + "spiderman.webp"),
                        new GetSpace("Spore", "spore", S3_BASE_URL + "spore.webp"),
                        new GetSpace("Stalker", "stalker", S3_BASE_URL + "stalker.webp"),
                        new GetSpace("Star Citizen", "starcitizen", S3_BASE_URL + "starcitizen.webp"),
                        new GetSpace("Star Wars Battlefront", "swbattlefront", S3_BASE_URL + "swbattlefront.webp"),
                        new GetSpace("StarCraft", "starcraft", S3_BASE_URL + "starcraft.webp"),
                        new GetSpace("Stardew Valley", "stardewvalley", S3_BASE_URL + "stardewvalley.webp"),
                        new GetSpace("Stellar Blade", "stellarblade", S3_BASE_URL + "stellarblade.webp"),
                        new GetSpace("Stellaris", "stellaris", S3_BASE_URL + "stellaris.webp"),
                        new GetSpace("Stray", "stray", S3_BASE_URL + "stray.webp"),
                        new GetSpace("Street Fighter", "streetfighter", S3_BASE_URL + "streetfighter.webp"),
                        new GetSpace("Subnautica", "subnautica", S3_BASE_URL + "subnautica.webp"),
                        new GetSpace("Sun Haven", "sunhaven", S3_BASE_URL + "sunhaven.webp"),
                        new GetSpace("Super Smash Bros", "smash", S3_BASE_URL + "smash.webp"),
                        new GetSpace("Tale of Immortal", "taleofimmortal", S3_BASE_URL + "taleofimmortal.webp"),
                        new GetSpace("Tales of Arise", "talesofarise", S3_BASE_URL + "talesofarise.webp"),
                        new GetSpace("Team Fortress 2", "tf2", S3_BASE_URL + "tf2.webp"),
                        new GetSpace("Teardown", "teardown", S3_BASE_URL + "teardown.webp"),
                        new GetSpace("Tekken", "tekken", S3_BASE_URL + "tekken.webp"),
                        new GetSpace("Terraria", "terraria", S3_BASE_URL + "terraria.webp"),
                        new GetSpace("The Binding of Isaac", "tboi", S3_BASE_URL + "tboi.webp"),
                        new GetSpace("The Escapists", "escapists", S3_BASE_URL + "escapists.webp"),
                        new GetSpace("The Evil Within", "evilwithin", S3_BASE_URL + "evilwithin.webp"),
                        new GetSpace("The First Descendant", "firstdescendant", S3_BASE_URL + "firstdescendant.webp"),
                        new GetSpace("The Forest", "theforest", S3_BASE_URL + "theforest.webp"),
                        new GetSpace("The Last of Us", "tlou", S3_BASE_URL + "tlou.webp"),
                        new GetSpace("The Long Dark", "longdark", S3_BASE_URL + "longdark.webp"),
                        new GetSpace("The Lord of the Rings: Return to Moria", "lotrmoria",
                                        S3_BASE_URL + "lotrmoria.webp"),
                        new GetSpace("The Outlast Trials", "outlasttrials", S3_BASE_URL + "outlasttrials.webp"),
                        new GetSpace("The Sims", "sims", S3_BASE_URL + "sims.webp"),
                        new GetSpace("The Stanley Parable", "stanleyparable", S3_BASE_URL + "stanleyparable.webp"),
                        new GetSpace("The Talos Principle", "talosprinciple", S3_BASE_URL + "talosprinciple.webp"),
                        new GetSpace("The Witcher", "witcher", S3_BASE_URL + "witcher.webp"),
                        new GetSpace("The Witcher II", "witcher2", S3_BASE_URL + "witcher2.webp"),
                        new GetSpace("The Witcher III", "witcher3", S3_BASE_URL + "witcher3.webp"),
                        new GetSpace("The Witness", "witness", S3_BASE_URL + "witness.webp"),
                        new GetSpace("This War of Mine", "warofmine", S3_BASE_URL + "warofmine.webp"),
                        new GetSpace("Timberborn", "timberborn", S3_BASE_URL + "timberborn.webp"),
                        new GetSpace("Titanfall 2", "titanfall", S3_BASE_URL + "titanfall.webp"),
                        new GetSpace("Torchlight", "torchlight", S3_BASE_URL + "torchlight.webp"),
                        new GetSpace("Total War", "totalwar", S3_BASE_URL + "totalwar.webp"),
                        new GetSpace("Tunic", "tunic", S3_BASE_URL + "tunic.webp"),
                        new GetSpace("Uncharted", "uncharted", S3_BASE_URL + "uncharted.webp"),
                        new GetSpace("Uncharted Waters Origin", "unchartedwaters",
                                        S3_BASE_URL + "unchartedwaters.webp"),
                        new GetSpace("Undertale", "undertale", S3_BASE_URL + "undertale.webp"),
                        new GetSpace("Untitled Goose Game", "goosegame", S3_BASE_URL + "goosegame.webp"),
                        new GetSpace("Valheim", "valheim", S3_BASE_URL + "valheim.webp"),
                        new GetSpace("Valorant", "val", S3_BASE_URL + "valorant.webp"),
                        new GetSpace("Vampire Survivors", "vampiresurvivors", S3_BASE_URL + "vampiresurvivors.webp"),
                        new GetSpace("Warframe", "warframe", S3_BASE_URL + "warframe.webp"),
                        new GetSpace("Warhammer 40K: Space Marine", "wh40k", S3_BASE_URL + "wh40k.webp"),
                        new GetSpace("Wasteland", "wasteland", S3_BASE_URL + "wasteland.webp"),
                        new GetSpace("What Remains of Edith Finch", "edithfinch", S3_BASE_URL + "edithfinch.webp"),
                        new GetSpace("World of Warcraft", "wow", S3_BASE_URL + "wow.webp"),
                        new GetSpace("XCOM 2", "xcom2", S3_BASE_URL + "xcom2.webp"),
                        new GetSpace("League of Legends Esports", "lolesports", S3_BASE_URL + "lolesports.webp"),
                        new GetSpace("Valorant Esports", "valesports", S3_BASE_URL + "valorantesports.webp"),
                        new GetSpace("Counter Strike Esports", "csesports", S3_BASE_URL + "csesports.webp"),
                        // New Esports
                        new GetSpace("Honor of Kings Esports", "honesports", S3_BASE_URL + "honesports.webp"),
                        new GetSpace("PUBG Mobile Esports", "pubgmobileesports",
                                        S3_BASE_URL + "pubgmobileesports.webp"),
                        new GetSpace("PUBG: Battlegrounds Esports", "pubgesports", S3_BASE_URL + "pubgesports.webp"),
                        new GetSpace("Fortnite Esports", "fortniteesports", S3_BASE_URL + "fortniteesports.webp"),
                        new GetSpace("Rainbow Six Siege Esports", "r6esports", S3_BASE_URL + "r6esports.webp"),
                        new GetSpace("Mobile Legends Esports", "mlbbesports", S3_BASE_URL + "mlbbesports.webp"),
                        new GetSpace("Call of Duty Esports", "codesports", S3_BASE_URL + "codesports.webp"),
                        new GetSpace("Apex Legends Esports", "apexesports", S3_BASE_URL + "apexesports.webp"),
                        new GetSpace("Rocket League Esports", "rocketleagueesports",
                                        S3_BASE_URL + "rocketleagueesports.webp"),
                        new GetSpace("Teamfight Tactics Esports", "tftesports", S3_BASE_URL + "tftesports.webp"),
                        new GetSpace("CrossFire Esports", "cfesports", S3_BASE_URL + "cfesports.webp"),
                        new GetSpace("Free Fire Esports", "freefiresports", S3_BASE_URL + "freefiresports.webp"),
                        new GetSpace("Street Fighter Esports", "sfesports", S3_BASE_URL + "sfesports.webp"),
                        new GetSpace("EA Sports FC Esports", "eafcesports", S3_BASE_URL + "eafcesports.webp"),
                        new GetSpace("Call of Duty: Warzone Esports", "warzoneesports",
                                        S3_BASE_URL + "warzoneesports.webp"),
                        new GetSpace("Overwatch Esports", "owesports", S3_BASE_URL + "owesports.webp"),
                        new GetSpace("Arena of Valor Esports", "aovesports", S3_BASE_URL + "aovesports.webp"),
                        new GetSpace("Pokemon Esports", "pokemonesports", S3_BASE_URL + "pokemonesports.webp"),
                        new GetSpace("StarCraft II Esports", "sc2esports", S3_BASE_URL + "sc2esports.webp"),
                        new GetSpace("Halo Esports", "haloesports", S3_BASE_URL + "haloesports.webp"),
                        new GetSpace("Tekken Esports", "tekkenesports", S3_BASE_URL + "tekkenesports.webp"),
                        new GetSpace("Magic: The Gathering Esports", "mtgesports", S3_BASE_URL + "mtgesports.webp"),
                        new GetSpace("NBA 2K Esports", "nba2kesports", S3_BASE_URL + "nba2kesports.webp"),
                        new GetSpace("Clash of Clans Esports", "cocesports", S3_BASE_URL + "cocesports.webp"),
                        new GetSpace("Madden NFL Esports", "maddenesports", S3_BASE_URL + "maddenesports.webp"),
                        new GetSpace("Rennsport Esports", "rennsportesports", S3_BASE_URL + "rennsportesports.webp"),
                        new GetSpace("World of Warcraft Esports", "wowesports", S3_BASE_URL + "wowesports.webp"),
                        new GetSpace("Identity V Esports", "idvesports", S3_BASE_URL + "idvesports.webp"),
                        new GetSpace("Super Smash Bros Esports", "smashesports", S3_BASE_URL + "smashesports.webp"),
                        new GetSpace("Hearthstone Esports", "hearthstoneesports",
                                        S3_BASE_URL + "hearthstoneesports.webp"),
                        new GetSpace("Heroes of the Storm Esports", "hotsesports", S3_BASE_URL + "hotsesports.webp"),
                        new GetSpace("Smite Esports", "smiteesports", S3_BASE_URL + "smiteesports.webp"),
                        new GetSpace("Brawl Stars Esports", "brawlstarsesports",
                                        S3_BASE_URL + "brawlstarsesports.webp"),
                        new GetSpace("Clash Royale Esports", "clashroyaleesports",
                                        S3_BASE_URL + "clashroyaleesports.webp"));

        public static Map<String, GetSpace> SPACE_MAP = SPACES.stream()
                        .collect(Collectors.toMap(space -> space.id, space -> space));
}