package com.apollo.shared;

import com.apollo.shared.pojos.GetSpace;

import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class ApolloSpaces {
        private static final String S3_BASE_URL = "https://yoapollo.s3.us-east-2.amazonaws.com/spaces/";

        public static final List<GetSpace> SPACES = Arrays.asList(
                        new GetSpace("7 Days to Die", "7todie", S3_BASE_URL + "7todie.jpg"),
                        new GetSpace("A Hat in Time", "ahatintime", S3_BASE_URL + "ahatintime.jpg"),
                        new GetSpace("A Plague Tale: Innocence", "aplaguetale", S3_BASE_URL + "aplaguetale.jpg"),
                        new GetSpace("A Way Out", "awayout", S3_BASE_URL + "awayout.jpg"),
                        new GetSpace("Ace Attorney", "aceattorney", S3_BASE_URL + "aceattorney.jpg"),
                        new GetSpace("Adventure Quest", "adventurequest", S3_BASE_URL + "adventurequest.jpg"),
                        new GetSpace("Age of Empires", "aoe", S3_BASE_URL + "aoe.jpg"),
                        new GetSpace("Age of Wonders", "ageofwonders", S3_BASE_URL + "ageofwonders.jpg"),
                        new GetSpace("Alan Wake", "alanwake", S3_BASE_URL + "alanwake.jpg"),
                        new GetSpace("Alien: Isolation", "alienisolation", S3_BASE_URL + "alienisolation.jpg"),
                        new GetSpace("Aliens vs. Predator", "avp", S3_BASE_URL + "avp.jpg"),
                        new GetSpace("American Truck Simulator", "americantrucksim",
                                        S3_BASE_URL + "americantrucksim.jpg"),
                        new GetSpace("Among Us", "amongus", S3_BASE_URL + "amongus.jpg"),
                        new GetSpace("Animal Crossing", "animalcrossing", S3_BASE_URL + "animalcrossing.jpg"),
                        new GetSpace("Anno 1800", "anno1800", S3_BASE_URL + "anno1800.jpg"),
                        new GetSpace("Antichamber", "antichamber", S3_BASE_URL + "antichamber.jpg"),
                        new GetSpace("Apex Legends", "apex", S3_BASE_URL + "apex.jpg"),
                        new GetSpace("Ark: Survival Evolved", "arksurvival", S3_BASE_URL + "arksurvival.jpg"),
                        new GetSpace("Arma 3", "arma3", S3_BASE_URL + "arma3.jpg"),
                        new GetSpace("Armello", "armello", S3_BASE_URL + "armello.jpg"),
                        new GetSpace("Assassin's Creed", "assassinscreed", S3_BASE_URL + "assassinscreed.jpg"),
                        new GetSpace("Astro Bot", "astrobot", S3_BASE_URL + "astrobot.jpg"),
                        new GetSpace("Astroneer", "astroneer", S3_BASE_URL + "astroneer.jpg"),
                        new GetSpace("Atelier Ryza", "atelierryza", S3_BASE_URL + "atelierryza.jpg"),
                        new GetSpace("Baba Is You", "babaisyou", S3_BASE_URL + "babaisyou.jpg"),
                        new GetSpace("Back 4 Blood", "back4blood", S3_BASE_URL + "back4blood.jpg"),
                        new GetSpace("Baldur's Gate 3", "bg3", S3_BASE_URL + "bg3.jpg"),
                        new GetSpace("Batman: Arkham Knight", "batmanak", S3_BASE_URL + "batmanak.jpg"),
                        new GetSpace("Battleblock Theater", "battleblock", S3_BASE_URL + "battleblock.jpg"),
                        new GetSpace("Battlefield", "battlefield", S3_BASE_URL + "battlefield.jpg"),
                        new GetSpace("Battletech", "battletech", S3_BASE_URL + "battletech.jpg"),
                        new GetSpace("Beat Saber", "beatsaber", S3_BASE_URL + "beatsaber.jpg"),
                        new GetSpace("Besiege", "besiege", S3_BASE_URL + "besiege.jpg"),
                        new GetSpace("Beyond: Two Souls", "beyondtwosouls", S3_BASE_URL + "beyondtwosouls.jpg"),
                        new GetSpace("Biomutant", "biomutant", S3_BASE_URL + "biomutant.jpg"),
                        new GetSpace("Bioshock", "bioshock", S3_BASE_URL + "bioshock.jpg"),
                        new GetSpace("Black Desert Online", "blackdesert", S3_BASE_URL + "blackdesert.jpg"),
                        new GetSpace("Black Mesa", "blackmesa", S3_BASE_URL + "blackmesa.jpg"),
                        new GetSpace("Blasphemous 2", "blasphemous", S3_BASE_URL + "blasphemous.jpg"),
                        new GetSpace("Bloodborne", "bloodborne", S3_BASE_URL + "bloodborne.jpg"),
                        new GetSpace("Bloons Tower Defense", "btd", S3_BASE_URL + "btd.jpg"),
                        new GetSpace("Borderlands", "borderlands", S3_BASE_URL + "borderlands.jpg"),
                        new GetSpace("Bully", "bully", S3_BASE_URL + "bully.jpg"),
                        new GetSpace("Call of Duty", "cod", S3_BASE_URL + "cod.jpg"),
                        new GetSpace("Car Mechanic Simulator", "carmechsim", S3_BASE_URL + "carmechsim.jpg"),
                        new GetSpace("Castle Crashers", "castlecrashers", S3_BASE_URL + "castlecrashers.jpg"),
                        new GetSpace("Castlevania", "castlevania", S3_BASE_URL + "castlevania.jpg"),
                        new GetSpace("Celeste", "celeste", S3_BASE_URL + "celeste.jpg"),
                        new GetSpace("Children of Morta", "childrenofmorta", S3_BASE_URL + "childrenofmorta.jpg"),
                        new GetSpace("Chivalry 2", "chivalry2", S3_BASE_URL + "chivalry2.jpg"),
                        new GetSpace("Cities Skylines", "citiesskylines", S3_BASE_URL + "citiesskylines.jpg"),
                        new GetSpace("Civilization Series", "civ", S3_BASE_URL + "civ.jpg"),
                        new GetSpace("Clash of Clans", "coc", S3_BASE_URL + "coc.jpg"),
                        new GetSpace("Clash Royale", "clashroyale", S3_BASE_URL + "clashroyale.jpg"),
                        new GetSpace("Company of Heroes", "companyofheroes", S3_BASE_URL + "companyofheroes.jpg"),
                        new GetSpace("Control", "control", S3_BASE_URL + "control.jpg"),
                        new GetSpace("Crash Bandicoot", "crashbandicoot", S3_BASE_URL + "crashbandicoot.jpg"),
                        new GetSpace("Crypt of the NecroDancer", "cryptnecrodancer",
                                        S3_BASE_URL + "cryptnecrodancer.jpg"),
                        new GetSpace("Crysis", "crysis", S3_BASE_URL + "crysis.jpg"),
                        new GetSpace("Cuphead", "cuphead", S3_BASE_URL + "cuphead.jpg"),
                        new GetSpace("Cyberpunk 2077", "cyberpunk2077", S3_BASE_URL + "cyberpunk2077.jpg"),
                        new GetSpace("Dark Souls 1", "darksouls", S3_BASE_URL + "darksouls.jpg"),
                        new GetSpace("Dark Souls 2", "darksouls2", S3_BASE_URL + "darksouls2.jpg"),
                        new GetSpace("Dark Souls 3", "darksouls3", S3_BASE_URL + "darksouls3.jpg"),
                        new GetSpace("Darkest Dungeon", "darkestdungeon", S3_BASE_URL + "darkestdungeon.jpg"),
                        new GetSpace("Darksiders", "darksiders", S3_BASE_URL + "darksiders.jpg"),
                        new GetSpace("Darkwood", "darkwood", S3_BASE_URL + "darkwood.jpg"),
                        new GetSpace("DayZ", "dayz", S3_BASE_URL + "dayz.jpg"),
                        new GetSpace("Dead by Daylight", "dbd", S3_BASE_URL + "dbd.jpg"),
                        new GetSpace("Death Stranding", "deathstranding", S3_BASE_URL + "deathstranding.jpg"),
                        new GetSpace("Deathloop", "deathloop", S3_BASE_URL + "deathloop.jpg"),
                        new GetSpace("Deep Rock Galactic", "deeprockgalactic", S3_BASE_URL + "deeprockgalactic.jpg"),
                        new GetSpace("Demons Souls", "demonssouls", S3_BASE_URL + "demonssouls.jpg"),
                        new GetSpace("Descenders", "descenders", S3_BASE_URL + "descenders.jpg"),
                        new GetSpace("Destiny 2", "destiny2", S3_BASE_URL + "destiny2.jpg"),
                        new GetSpace("Detroit: Become Human", "becomehuman", S3_BASE_URL + "becomehuman.jpg"),
                        new GetSpace("Deus Ex", "deus-ex", S3_BASE_URL + "deus-ex.jpg"),
                        new GetSpace("Devil May Cry", "dmc", S3_BASE_URL + "dmc.jpg"),
                        new GetSpace("Diablo", "diablo", S3_BASE_URL + "diablo.jpg"),
                        new GetSpace("Disco Elysium", "discoelysium", S3_BASE_URL + "discoelysium.jpg"),
                        new GetSpace("Dishonored 2", "dishonored", S3_BASE_URL + "dishonored.jpg"),
                        new GetSpace("Divinity: Original Sin 2", "divinity2", S3_BASE_URL + "divinity2.jpg"),
                        new GetSpace("Don't Starve Together", "dontstarve", S3_BASE_URL + "dontstarve.jpg"),
                        new GetSpace("Doom Eternal", "doom", S3_BASE_URL + "doom.jpg"),
                        new GetSpace("Dota 2", "dota2", S3_BASE_URL + "dota2.jpg"),
                        new GetSpace("Dragon Age", "dragonage", S3_BASE_URL + "dragonage.jpg"),
                        new GetSpace("Dragon Ball FighterZ", "dbfighterz", S3_BASE_URL + "dbfighterz.jpg"),
                        new GetSpace("Dragon Quest", "dragonquest", S3_BASE_URL + "dragonquest.jpg"),
                        new GetSpace("DragonFable", "dragonfable", S3_BASE_URL + "dragonfable.jpg"),
                        new GetSpace("Dragon's Dogma", "dragonsdogma", S3_BASE_URL + "dragonsdogma.jpg"),
                        new GetSpace("Dungeon Defenders", "dungeondefenders", S3_BASE_URL + "dungeondefenders.jpg"),
                        new GetSpace("Dying Light", "dyinglight", S3_BASE_URL + "dyinglight.jpg"),
                        new GetSpace("Dyson Sphere Program", "dysonsphere", S3_BASE_URL + "dysonsphere.jpg"),
                        new GetSpace("EA FC", "eafc", S3_BASE_URL + "eafc.jpg"),
                        new GetSpace("Eco", "eco", S3_BASE_URL + "eco.jpg"),
                        new GetSpace("Elden Ring", "eldenring", S3_BASE_URL + "eldenring.jpg"),
                        new GetSpace("Elex", "elex", S3_BASE_URL + "elex.jpg"),
                        new GetSpace("Elite Dangerous", "elitedangerous", S3_BASE_URL + "elitedangerous.jpg"),
                        new GetSpace("Enderal: Forgotten Stories", "enderal", S3_BASE_URL + "enderal.jpg"),
                        new GetSpace("Endless Legend", "endlesslegend", S3_BASE_URL + "endlesslegend.jpg"),
                        new GetSpace("Endless Space", "endlessspace", S3_BASE_URL + "endlessspace.jpg"),
                        new GetSpace("Enter the Gungeon", "enterthegungeon", S3_BASE_URL + "enterthegungeon.jpg"),
                        new GetSpace("Eternal Return", "eternalreturn", S3_BASE_URL + "eternalreturn.jpg"),
                        new GetSpace("Europa Universalis IV", "eu4", S3_BASE_URL + "eu4.jpg"),
                        new GetSpace("EVE Online", "eveonline", S3_BASE_URL + "eveonline.jpg"),
                        new GetSpace("EverQuest", "everquest", S3_BASE_URL + "everquest.jpg"),
                        new GetSpace("Factorio", "factorio", S3_BASE_URL + "factorio.jpg"),
                        new GetSpace("Fall Guys", "fallguys", S3_BASE_URL + "fallguys.jpg"),
                        new GetSpace("Fallout", "fallout", S3_BASE_URL + "fallout.jpg"),
                        new GetSpace("Far Cry", "farcry", S3_BASE_URL + "farcry.jpg"),
                        new GetSpace("Fate", "fate", S3_BASE_URL + "fate.jpg"),
                        new GetSpace("Final Fantasy", "ff", S3_BASE_URL + "ff.jpg"),
                        new GetSpace("Fire Emblem", "fireemblem", S3_BASE_URL + "fireemblem.jpg"),
                        new GetSpace("Five Nights at Freddy's", "fnaf", S3_BASE_URL + "fnaf.jpg"),
                        new GetSpace("For Honor", "forhonor", S3_BASE_URL + "forhonor.jpg"),
                        new GetSpace("Forager", "forager", S3_BASE_URL + "forager.jpg"),
                        new GetSpace("Fortnite", "fortnite", S3_BASE_URL + "fortnite.jpg"),
                        new GetSpace("Forza", "forza", S3_BASE_URL + "forza.jpg"),
                        new GetSpace("Frostpunk", "frostpunk", S3_BASE_URL + "frostpunk.jpg"),
                        new GetSpace("FTL: Faster Than Light", "ftl", S3_BASE_URL + "ftl.jpg"),
                        new GetSpace("Galaga", "galaga", S3_BASE_URL + "galaga.jpg"),
                        new GetSpace("Gang Beasts", "gangbeasts", S3_BASE_URL + "gangbeasts.jpg"),
                        new GetSpace("Garry's Mod", "gmod", S3_BASE_URL + "gmod.jpg"),
                        new GetSpace("Genshin Impact", "genshinimpact", S3_BASE_URL + "genshinimpact.jpg"),
                        new GetSpace("Geometry Dash", "geometrydash", S3_BASE_URL + "geometrydash.jpg"),
                        new GetSpace("Getting Over It", "gettingoverit", S3_BASE_URL + "gettingoverit.jpg"),
                        new GetSpace("Ghost of Tsushima", "tsushima", S3_BASE_URL + "tsushima.jpg"),
                        new GetSpace("Ghostwire: Tokyo", "ghostwiretokyo", S3_BASE_URL + "ghostwiretokyo.jpg"),
                        new GetSpace("Goat Simulator", "goatsim", S3_BASE_URL + "goatsim.jpg"),
                        new GetSpace("God of War", "gow", S3_BASE_URL + "gow.jpg"),
                        new GetSpace("GoldenEye 007", "goldeneye007", S3_BASE_URL + "goldeneye007.jpg"),
                        new GetSpace("Grand Theft Auto", "gta", S3_BASE_URL + "gta.jpg"),
                        new GetSpace("Graveyard Keeper", "graveyardkeeper", S3_BASE_URL + "graveyardkeeper.jpg"),
                        new GetSpace("Grim Dawn", "grimdawn", S3_BASE_URL + "grimdawn.jpg"),
                        new GetSpace("Gris", "gris", S3_BASE_URL + "gris.jpg"),
                        new GetSpace("Guild Wars", "guildwars", S3_BASE_URL + "guildwars.jpg"),
                        new GetSpace("Guilty Gear", "guiltygear", S3_BASE_URL + "guiltygear.jpg"),
                        new GetSpace("Guitar Hero", "guitarhero", S3_BASE_URL + "guitarhero.jpg"),
                        new GetSpace("Gunfire Reborn", "gunfirereborn", S3_BASE_URL + "gunfirereborn.jpg"),
                        new GetSpace("Hades", "hades", S3_BASE_URL + "hades.jpg"),
                        new GetSpace("Half-Life", "halflife", S3_BASE_URL + "halflife.jpg"),
                        new GetSpace("Halo", "halo", S3_BASE_URL + "halo.jpg"),
                        new GetSpace("Hearthstone", "hearthstone", S3_BASE_URL + "hearthstone.jpg"),
                        new GetSpace("Hearts of Iron", "heartsofiron", S3_BASE_URL + "heartsofiron.jpg"),
                        new GetSpace("Heavy Rain", "heavyrain", S3_BASE_URL + "heavyrain.jpg"),
                        new GetSpace("Hellblade: Senua's Sacrifice", "hellblade", S3_BASE_URL + "hellblade.jpg"),
                        new GetSpace("Helldivers", "helldivers", S3_BASE_URL + "helldivers.jpg"),
                        new GetSpace("Hero Siege", "herosiege", S3_BASE_URL + "herosiege.jpg"),
                        new GetSpace("Heroes of Hammerwatch", "heroeshammerwatch",
                                        S3_BASE_URL + "heroeshammerwatch.jpg"),
                        new GetSpace("Hero's Land", "herosland", S3_BASE_URL + "herosland.jpg"),
                        new GetSpace("Heroes of Might and Magic III", "homm3", S3_BASE_URL + "homm3.jpg"),
                        new GetSpace("Heroes of the Storm", "hots", S3_BASE_URL + "hots.jpg"),
                        new GetSpace("Hexcells", "hexcells", S3_BASE_URL + "hexcells.jpg"),
                        new GetSpace("Hitman", "hitman", S3_BASE_URL + "hitman.jpg"),
                        new GetSpace("Hollow Knight", "hk", S3_BASE_URL + "hk.jpg"),
                        new GetSpace("Horizon Forbidden West", "hfw", S3_BASE_URL + "hfw.jpg"),
                        new GetSpace("Horizon Zero Dawn", "hzd", S3_BASE_URL + "hzd.jpg"),
                        new GetSpace("Hotline Miami", "hotlinemiami", S3_BASE_URL + "hotlinemiami.jpg"),
                        new GetSpace("House Flipper", "houseflipper", S3_BASE_URL + "houseflipper.jpg"),
                        new GetSpace("Human: Fall Flat", "humanfallflat", S3_BASE_URL + "humanfallflat.jpg"),
                        new GetSpace("Humankind", "humankind", S3_BASE_URL + "humankind.jpg"),
                        new GetSpace("Hunt: Showdown 1896", "huntshowdown", S3_BASE_URL + "huntshowdown.jpg"),
                        new GetSpace("Imperator: Rome", "imperatorrome", S3_BASE_URL + "imperatorrome.jpg"),
                        new GetSpace("Injustice", "injustice", S3_BASE_URL + "injustice.jpg"),
                        new GetSpace("Inscryption", "inscryption", S3_BASE_URL + "inscryption.jpg"),
                        new GetSpace("Inside the Backrooms", "insidethebackrooms",
                                        S3_BASE_URL + "insidethebackrooms.jpg"),
                        new GetSpace("It Takes Two", "itt", S3_BASE_URL + "itt.jpg"),
                        new GetSpace("Katamari Series", "katamari", S3_BASE_URL + "katamari.jpg"),
                        new GetSpace("Kenshi", "kenshi", S3_BASE_URL + "kenshi.jpg"),
                        new GetSpace("Kerbal Space Program", "ksp", S3_BASE_URL + "ksp.jpg"),
                        new GetSpace("Kingdom Hearts", "kingdomhearts", S3_BASE_URL + "kingdomhearts.jpg"),
                        new GetSpace("Kingdoms and Castles", "kingdomscastles", S3_BASE_URL + "kingdomscastles.jpg"),
                        new GetSpace("Kirby", "kirby", S3_BASE_URL + "kirby.jpg"),
                        new GetSpace("Knockout City", "knockoutcity", S3_BASE_URL + "knockoutcity.jpg"),
                        new GetSpace("L.A. Noire", "lanoire", S3_BASE_URL + "lanoire.jpg"),
                        new GetSpace("League of Legends", "lol", S3_BASE_URL + "lol.jpg"),
                        new GetSpace("Left 4 Dead", "l4d", S3_BASE_URL + "l4d.jpg"),
                        new GetSpace("Legend of Zelda: Breath of the Wild", "botw", S3_BASE_URL + "botw.jpg"),
                        new GetSpace("Legend of Zelda: Tears of the Kingdom", "totk", S3_BASE_URL + "totk.jpg"),
                        new GetSpace("LEGO Star Wars", "legostarwars", S3_BASE_URL + "legostarwars.jpg"),
                        new GetSpace("Life is Strange", "lifeisstrange", S3_BASE_URL + "lifeisstrange.jpg"),
                        new GetSpace("Little Nightmares II", "littlenightmares2",
                                        S3_BASE_URL + "littlenightmares2.jpg"),
                        new GetSpace("LittleBigPlanet", "littlebigplanet", S3_BASE_URL + "littlebigplanet.jpg"),
                        new GetSpace("Lobotomy Corporation", "lobotomycorp", S3_BASE_URL + "lobotomycorp.jpg"),
                        new GetSpace("Loop Hero", "loophero", S3_BASE_URL + "loophero.jpg"),
                        new GetSpace("Madden", "madden", S3_BASE_URL + "madden.jpg"),
                        new GetSpace("Mafia", "mafia", S3_BASE_URL + "mafia.jpg"),
                        new GetSpace("Mario", "mario", S3_BASE_URL + "mario.jpg"),
                        new GetSpace("Mass Effect", "masseffect", S3_BASE_URL + "masseffect.jpg"),
                        new GetSpace("Max Payne", "maxpayne", S3_BASE_URL + "maxpayne.jpg"),
                        new GetSpace("Mechwarrior", "mechwarrior", S3_BASE_URL + "mechwarrior.jpg"),
                        new GetSpace("Medieval Dynasty", "medievaldynasty", S3_BASE_URL + "medievaldynasty.jpg"),
                        new GetSpace("Mega Man", "megaman", S3_BASE_URL + "megaman.jpg"),
                        new GetSpace("Metal Gear", "metalgear", S3_BASE_URL + "metalgear.jpg"),
                        new GetSpace("Metal Slug", "metalslug", S3_BASE_URL + "metalslug.jpg"),
                        new GetSpace("Metro Exodus", "metroexodus", S3_BASE_URL + "metroexodus.jpg"),
                        new GetSpace("Microsoft Flight Simulator", "msflightsim", S3_BASE_URL + "msflightsim.jpg"),
                        new GetSpace("Minecraft", "minecraft", S3_BASE_URL + "minecraft.jpg"),
                        new GetSpace("Mirror's Edge", "mirrorsedge", S3_BASE_URL + "mirrorsedge.jpg"),
                        new GetSpace("MLB The Show", "theshow", S3_BASE_URL + "theshow.jpg"),
                        new GetSpace("Monster Hunter", "monsterhunter", S3_BASE_URL + "monsterhunter.jpg"),
                        new GetSpace("Monster Train", "monstertrain", S3_BASE_URL + "monstertrain.jpg"),
                        new GetSpace("Mordhau", "mordhau", S3_BASE_URL + "mordhau.jpg"),
                        new GetSpace("Mortal Kombat", "mk", S3_BASE_URL + "mk.jpg"),
                        new GetSpace("Mount and Blade", "mnb", S3_BASE_URL + "mnb.jpg"),
                        new GetSpace("Mudrunner", "mudrunner", S3_BASE_URL + "mudrunner.jpg"),
                        new GetSpace("My Summer Car", "mysummercar", S3_BASE_URL + "mysummercar.jpg"),
                        new GetSpace("My Time at Portia", "mytimeatportia", S3_BASE_URL + "mytimeatportia.jpg"),
                        new GetSpace("NBA2K", "nba2k", S3_BASE_URL + "nba2k.jpg"),
                        new GetSpace("New World: Aeternum", "newworld", S3_BASE_URL + "newworld.jpg"),
                        new GetSpace("NHL", "eanhl", S3_BASE_URL + "eanhl.jpg"),
                        new GetSpace("NieR Replicant", "nierreplicant", S3_BASE_URL + "nierreplicant.jpg"),
                        new GetSpace("NieR: Automata", "nierautomata", S3_BASE_URL + "nierautomata.jpg"),
                        new GetSpace("Nioh", "nioh", S3_BASE_URL + "nioh.jpg"),
                        new GetSpace("No Man's Sky", "nms", S3_BASE_URL + "nms.jpg"),
                        new GetSpace("Noita", "noita", S3_BASE_URL + "noita.jpg"),
                        new GetSpace("Okami", "okami", S3_BASE_URL + "okami.jpg"),
                        new GetSpace("Ori", "ori", S3_BASE_URL + "ori.jpg"),
                        new GetSpace("Outer Wilds", "outerwilds", S3_BASE_URL + "outerwilds.jpg"),
                        new GetSpace("Outer Worlds", "outerworlds", S3_BASE_URL + "outerworlds.jpg"),
                        new GetSpace("Outlast", "outlast", S3_BASE_URL + "outlast.jpg"),
                        new GetSpace("Overcooked", "overcooked", S3_BASE_URL + "overcooked.jpg"),
                        new GetSpace("Overwatch", "overwatch", S3_BASE_URL + "overwatch.jpg"),
                        new GetSpace("Papers, Please", "papersplease", S3_BASE_URL + "papersplease.jpg"),
                        new GetSpace("Path of Exile", "pathofexile", S3_BASE_URL + "pathofexile.jpg"),
                        new GetSpace("Payday", "payday", S3_BASE_URL + "payday.jpg"),
                        new GetSpace("Persona", "persona", S3_BASE_URL + "persona.jpg"),
                        new GetSpace("Pillars of Eternity", "pillarsofeternity", S3_BASE_URL + "pillarsofeternity.jpg"),
                        new GetSpace("Plague Inc.", "plagueinc", S3_BASE_URL + "plagueinc.jpg"),
                        new GetSpace("Planetside 2", "planetside", S3_BASE_URL + "planetside.jpg"),
                        new GetSpace("Plants vs. Zombies", "pvz", S3_BASE_URL + "pvz.jpg"),
                        new GetSpace("Pokemon", "pokemon", S3_BASE_URL + "pokemon.jpg"),
                        new GetSpace("Portal", "portal", S3_BASE_URL + "portal.jpg"),
                        new GetSpace("Prey", "prey", S3_BASE_URL + "prey.jpg"),
                        new GetSpace("Prison Architect", "prisonarchitect", S3_BASE_URL + "prisonarchitect.jpg"),
                        new GetSpace("PUBG", "pubg", S3_BASE_URL + "pubg.jpg"),
                        new GetSpace("Quake", "quake", S3_BASE_URL + "quake.jpg"),
                        new GetSpace("Quiplash", "quiplash", S3_BASE_URL + "quiplash.jpg"),
                        new GetSpace("Rainbow Six Siege", "r6", S3_BASE_URL + "r6.jpg"),
                        new GetSpace("Realm of the Mad God", "rotmg", S3_BASE_URL + "rotmg.jpg"),
                        new GetSpace("Red Dead Redemption", "rdr", S3_BASE_URL + "rdr.jpg"),
                        new GetSpace("Resident Evil", "residentevil", S3_BASE_URL + "residentevil.jpg"),
                        new GetSpace("Rimworld", "rimworld", S3_BASE_URL + "rimworld.jpg"),
                        new GetSpace("Risk of Rain", "riskofrain", S3_BASE_URL + "riskofrain.jpg"),
                        new GetSpace("Roblox", "roblox", S3_BASE_URL + "roblox.jpg"),
                        new GetSpace("Rock Band", "rockband", S3_BASE_URL + "rockband.jpg"),
                        new GetSpace("Rocket League", "rocketleague", S3_BASE_URL + "rocketleague.jpg"),
                        new GetSpace("Rogue Legacy", "roguelegacy", S3_BASE_URL + "roguelegacy.jpg"),
                        new GetSpace("Roller Coaster Tycoon", "rct", S3_BASE_URL + "rct.jpg"),
                        new GetSpace("Rounds", "rounds", S3_BASE_URL + "rounds.jpg"),
                        new GetSpace("Runescape", "runescape", S3_BASE_URL + "runescape.jpg"),
                        new GetSpace("Rust", "rust", S3_BASE_URL + "rust.jpg"),
                        new GetSpace("S.T.A.L.K.E.R.", "stalker", S3_BASE_URL + "stalker.jpg"),
                        new GetSpace("Saint's Row", "saintsrow", S3_BASE_URL + "saintsrow.jpg"),
                        new GetSpace("Satisfactory", "satisfactory", S3_BASE_URL + "satisfactory.jpg"),
                        new GetSpace("Sea of Thieves", "seaofthieves", S3_BASE_URL + "seaofthieves.jpg"),
                        new GetSpace("Sekiro", "sekiro", S3_BASE_URL + "sekiro.jpg"),
                        new GetSpace("Shadow of the Colossus", "sotc", S3_BASE_URL + "sotc.jpg"),
                        new GetSpace("Shadow of Mordor", "shadowofmordor", S3_BASE_URL + "shadowofmordor.jpg"),
                        new GetSpace("Skyrim", "skyrim", S3_BASE_URL + "skyrim.jpg"),
                        new GetSpace("Slay the Spire", "slaythespire", S3_BASE_URL + "slaythespire.jpg"),
                        new GetSpace("Sleeping Dogs", "sleepingdogs", S3_BASE_URL + "sleepingdogs.jpg"),
                        new GetSpace("Slime Rancher", "slimerancher", S3_BASE_URL + "slimerancher.jpg"),
                        new GetSpace("Super Smash Bros", "smash", S3_BASE_URL + "smash.jpg"),
                        new GetSpace("Smite", "smite", S3_BASE_URL + "smite.jpg"),
                        new GetSpace("Sniper Elite", "sniperelite", S3_BASE_URL + "sniperelite.jpg"),
                        new GetSpace("Sonic the Hedgehog", "sonic", S3_BASE_URL + "sonic.jpg"),
                        new GetSpace("Spider-Man", "spiderman", S3_BASE_URL + "spiderman.jpg"),
                        new GetSpace("Splitgate", "splitgate", S3_BASE_URL + "splitgate.jpg"),
                        new GetSpace("Spore", "spore", S3_BASE_URL + "spore.jpg"),
                        new GetSpace("Star Citizen", "starcitizen", S3_BASE_URL + "starcitizen.jpg"),
                        new GetSpace("Star Wars Battlefront", "swbattlefront", S3_BASE_URL + "swbattlefront.jpg"),
                        new GetSpace("StarCraft", "starcraft", S3_BASE_URL + "starcraft.jpg"),
                        new GetSpace("Stardew Valley", "stardewvalley", S3_BASE_URL + "stardewvalley.jpg"),
                        new GetSpace("Stellar Blade", "stellarblade", S3_BASE_URL + "stellarblade.jpg"),
                        new GetSpace("Stellaris", "stellaris", S3_BASE_URL + "stellaris.jpg"),
                        new GetSpace("Stray", "stray", S3_BASE_URL + "stray.jpg"),
                        new GetSpace("Street Fighter", "streetfighter", S3_BASE_URL + "streetfighter.jpg"),
                        new GetSpace("Subnautica", "subnautica", S3_BASE_URL + "subnautica.jpg"),
                        new GetSpace("Sun Haven", "sunhaven", S3_BASE_URL + "sunhaven.jpg"),
                        new GetSpace("Tale of Immortal", "taleofimmortal", S3_BASE_URL + "taleofimmortal.jpg"),
                        new GetSpace("Tales of Arise", "talesofarise", S3_BASE_URL + "talesofarise.jpg"),
                        new GetSpace("Team Fortress 2", "tf2", S3_BASE_URL + "tf2.jpg"),
                        new GetSpace("Teardown", "teardown", S3_BASE_URL + "teardown.jpg"),
                        new GetSpace("Tekken", "tekken", S3_BASE_URL + "tekken.jpg"),
                        new GetSpace("Temtem", "temtem", S3_BASE_URL + "temtem.jpg"),
                        new GetSpace("Terraria", "terraria", S3_BASE_URL + "terraria.jpg"),
                        new GetSpace("Tetris", "tetris", S3_BASE_URL + "tetris.jpg"),
                        new GetSpace("The Binding of Isaac", "bindingofisaac", S3_BASE_URL + "bindingofisaac.jpg"),
                        new GetSpace("The Escapists", "escapists", S3_BASE_URL + "escapists.jpg"),
                        new GetSpace("The Evil Within", "evilwithin", S3_BASE_URL + "evilwithin.jpg"),
                        new GetSpace("The First Descendant", "firstdescendant", S3_BASE_URL + "firstdescendant.jpg"),
                        new GetSpace("The Forest", "theforest", S3_BASE_URL + "theforest.jpg"),
                        new GetSpace("The Last of Us", "tlou", S3_BASE_URL + "tlou.jpg"),
                        new GetSpace("The Long Dark", "longdark", S3_BASE_URL + "longdark.jpg"),
                        new GetSpace("The Lord of the Rings: Return to Moria", "lotrmoria",
                                        S3_BASE_URL + "lotrmoria.jpg"),
                        new GetSpace("The Outlast Trials", "outlasttrials", S3_BASE_URL + "outlasttrials.jpg"),
                        new GetSpace("The Pedestrian", "pedestrian", S3_BASE_URL + "pedestrian.jpg"),
                        new GetSpace("The Sims", "sims", S3_BASE_URL + "sims.jpg"),
                        new GetSpace("The Stanley Parable", "stanleyparable", S3_BASE_URL + "stanleyparable.jpg"),
                        new GetSpace("The Talos Principle", "talosprinciple", S3_BASE_URL + "talosprinciple.jpg"),
                        new GetSpace("The Witcher", "witcher", S3_BASE_URL + "witcher.jpg"),
                        new GetSpace("The Witcher II", "witcher2", S3_BASE_URL + "witcher2.jpg"),
                        new GetSpace("The Witcher III", "witcher3", S3_BASE_URL + "witcher3.jpg"),
                        new GetSpace("The Witness", "witness", S3_BASE_URL + "witness.jpg"),
                        new GetSpace("This War of Mine", "thiswarofmine", S3_BASE_URL + "thiswarofmine.jpg"),
                        new GetSpace("Timberborn", "timberborn", S3_BASE_URL + "timberborn.jpg"),
                        new GetSpace("Titanfall 2", "titanfall", S3_BASE_URL + "titanfall.jpg"),
                        new GetSpace("Torchlight", "torchlight", S3_BASE_URL + "torchlight.jpg"),
                        new GetSpace("Total War", "totalwar", S3_BASE_URL + "totalwar.jpg"),
                        new GetSpace("Tunic", "tunic", S3_BASE_URL + "tunic.jpg"),
                        new GetSpace("Uncharted", "uncharted", S3_BASE_URL + "uncharted.jpg"),
                        new GetSpace("Uncharted Waters Origin", "unchartedwaters", S3_BASE_URL + "unchartedwaters.jpg"),
                        new GetSpace("Undertale", "undertale", S3_BASE_URL + "undertale.jpg"),
                        new GetSpace("Untitled Goose Game", "goosegame", S3_BASE_URL + "goosegame.jpg"),
                        new GetSpace("Valheim", "valheim", S3_BASE_URL + "valheim.jpg"),
                        new GetSpace("Valorant", "valorant", S3_BASE_URL + "valorant.jpg"),
                        new GetSpace("Vampire Survivors", "vampiresurvivors", S3_BASE_URL + "vampiresurvivors.jpg"),
                        new GetSpace("Warframe", "warframe", S3_BASE_URL + "warframe.jpg"),
                        new GetSpace("Warhammer 4000: Space Marine", "wh4k", S3_BASE_URL + "wh4k.jpg"),
                        new GetSpace("Wasteland", "wasteland", S3_BASE_URL + "wasteland.jpg"),
                        new GetSpace("What Remains of Edith Finch", "edithfinch", S3_BASE_URL + "edithfinch.jpg"),
                        new GetSpace("Wingspan", "wingspan", S3_BASE_URL + "wingspan.jpg"),
                        new GetSpace("World of Warcraft", "wow", S3_BASE_URL + "wow.jpg"),
                        new GetSpace("XCOM 2", "xcom2", S3_BASE_URL + "xcom2.jpg"),
                        new GetSpace("Project Zomboid", "zomboid", S3_BASE_URL + "zomboid.jpg"),
                        new GetSpace("Morrowind", "morrowind", S3_BASE_URL + "morrowind.jpg"),
                        new GetSpace("Oblivion", "oblivion", S3_BASE_URL + "oblivion.jpg"),
                        new GetSpace("Elder Scrolls Online", "tesonline", S3_BASE_URL + "tesonline.jpg"),
                        new GetSpace("Dragon Ball Sparking Zero", "sparkingzero", S3_BASE_URL + "sparkingzero.jpg"),
                        new GetSpace("Black Myth: Wukong", "wukong", S3_BASE_URL + "wukong.jpg"),
                        new GetSpace("Balatro", "balatro", S3_BASE_URL + "balatro.jpg"),
                        new GetSpace("Metaphor: ReFantazio", "refantazio", S3_BASE_URL + "refantazio.jpg"),
                        new GetSpace("Like a Dragon: Infinite Wealth", "likeadragon", S3_BASE_URL + "likeadragon.jpg"),
                        new GetSpace("Silent Hill 2", "silenthill", S3_BASE_URL + "silenthill.jpg"),
                        new GetSpace("Neva", "neva", S3_BASE_URL + "neva.jpg"),
                        new GetSpace("Banana", "banana", S3_BASE_URL + "banana.jpg"),
                        new GetSpace("League of Legends Esports", "lolesports", S3_BASE_URL + "lolesports.jpg"),
                        new GetSpace("Valorant Esports", "valorantesports", S3_BASE_URL + "valorantesports.jpg"));

        public static Map<String, GetSpace> SPACE_MAP = SPACES.stream()
                        .collect(Collectors.toMap(space -> space.id, space -> space));
}