package com.apollo.backendapi;

import com.apollo.backendapi.pojos.GetSpace;

import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class ApolloSpaces {
        private static final String S3_BASE_URL = "https://yoapollo.s3.us-east-2.amazonaws.com/spaces/";

        public static final List<GetSpace> SPACES = Arrays.asList(
                        new GetSpace("League of Legends", "lol", S3_BASE_URL + "lol.jpg"),
                        new GetSpace("Elden Ring", "eldenring", S3_BASE_URL + "eldenring.jpg"),
                        new GetSpace("Valorant", "valorant", S3_BASE_URL + "valorant.jpg"),
                        new GetSpace("Dota 2", "dota2", S3_BASE_URL + "dota2.jpg"),
                        new GetSpace("Counter Strike", "counterstrike", S3_BASE_URL + "counterstrike.jpg"),
                        new GetSpace("Overwatch", "overwatch", S3_BASE_URL + "overwatch.jpg"),
                        new GetSpace("Rocket League", "rocketleague", S3_BASE_URL + "rocketleague.jpg"),
                        new GetSpace("Fortnite", "fortnite", S3_BASE_URL + "fortnite.jpg"),
                        new GetSpace("Team Fortress 2", "tf2", S3_BASE_URL + "tf2.jpg"),
                        new GetSpace("Street Fighter", "streetfighter", S3_BASE_URL + "streetfighter.jpg"),
                        new GetSpace("Dark Souls 1", "darksouls", S3_BASE_URL + "darksouls.jpg"),
                        new GetSpace("Dark Souls 2", "darksouls2", S3_BASE_URL + "darksouls2.jpg"),
                        new GetSpace("Dark Souls 3", "darksouls3", S3_BASE_URL + "darksouls3.jpg"),
                        new GetSpace("Bloodborne", "bloodborne", S3_BASE_URL + "bloodborne.jpg"),
                        new GetSpace("Sekiro", "sekiro", S3_BASE_URL + "sekiro.jpg"),
                        new GetSpace("Demon's Souls", "demonssouls", S3_BASE_URL + "demonssouls.jpg"),
                        new GetSpace("PUBG", "pubg", S3_BASE_URL + "pubg.jpg"),
                        new GetSpace("Guilty Gear", "guiltygear", S3_BASE_URL + "guiltygear.jpg"),
                        new GetSpace("Tekken", "tekken", S3_BASE_URL + "tekken.jpg"),
                        new GetSpace("Smash Bros", "smash", S3_BASE_URL + "smash.jpg"),
                        new GetSpace("Mario", "mario", S3_BASE_URL + "mario.jpg"),
                        new GetSpace("Breath of the Wild", "botw", S3_BASE_URL + "botw.jpg"),
                        new GetSpace("Tears of the Kingdom", "totk", S3_BASE_URL + "totk.jpg"),
                        new GetSpace("World of Warcraft", "wow", S3_BASE_URL + "wow.jpg"),
                        new GetSpace("Hearthstone", "hearthstone", S3_BASE_URL + "hearthstone.jpg"),
                        new GetSpace("Skyrim", "skyrim", S3_BASE_URL + "skyrim.jpg"),
                        new GetSpace("Destiny 2", "destiny2", S3_BASE_URL + "destiny2.jpg"),
                        new GetSpace("Titanfall", "titanfall", S3_BASE_URL + "titanfall.jpg"),
                        new GetSpace("Pokemon", "pokemon", S3_BASE_URL + "pokemon.jpg"),
                        new GetSpace("Diablo 1-4", "diablo", S3_BASE_URL + "diablo.jpg"),
                        new GetSpace("Civilization Series", "civilization", S3_BASE_URL + "civilization.jpg"),
                        new GetSpace("Path of Exile", "pathofexile", S3_BASE_URL + "pathofexile.jpg"),
                        new GetSpace("Hearts of Iron IV", "heartsofiron", S3_BASE_URL + "heartsofiron.jpg"),
                        new GetSpace("Smite", "smite", S3_BASE_URL + "smite.jpg"),
                        new GetSpace("Heroes of the Storm", "hots", S3_BASE_URL + "hots.jpg"),
                        new GetSpace("Elite Dangerous", "elitedangerous", S3_BASE_URL + "elitedangerous.jpg"),
                        new GetSpace("Final Fantasy", "finalfantasy", S3_BASE_URL + "finalfantasy.jpg"),
                        new GetSpace("Runescape", "runescape", S3_BASE_URL + "runescape.jpg"),
                        new GetSpace("No Man's Sky", "nms", S3_BASE_URL + "nms.jpg"),
                        new GetSpace("Undertale", "undertale", S3_BASE_URL + "undertale.jpg"),
                        new GetSpace("Terraria", "terraria", S3_BASE_URL + "terraria.jpg"),
                        new GetSpace("Minecraft", "minecraft", S3_BASE_URL + "minecraft.jpg"),
                        new GetSpace("Cuphead", "cuphead", S3_BASE_URL + "cuphead.jpg"),
                        new GetSpace("Fallout", "fallout", S3_BASE_URL + "fallout.jpg"),
                        new GetSpace("Call of Duty", "callofduty", S3_BASE_URL + "callofduty.jpg"),
                        new GetSpace("Monster Hunter", "monsterhunter", S3_BASE_URL + "monsterhunter.jpg"),
                        new GetSpace("EA FC", "eafc", S3_BASE_URL + "eafc.jpg"),
                        new GetSpace("Madden", "madden", S3_BASE_URL + "madden.jpg"),
                        new GetSpace("NBA 2K", "nba2k", S3_BASE_URL + "nba2k.jpg"),
                        new GetSpace("NHL 24", "eanhl", S3_BASE_URL + "eanhl.jpg"),
                        new GetSpace("DayZ", "dayz", S3_BASE_URL + "dayz.jpg"),
                        new GetSpace("Clash of Clans", "clashofclans", S3_BASE_URL + "clashofclans.jpg"),
                        new GetSpace("Rust", "rust", S3_BASE_URL + "rust.jpg"),
                        new GetSpace("Kingdom Hearts", "kingdomhearts", S3_BASE_URL + "kingdomhearts.jpg"),
                        new GetSpace("Warframe", "warframe", S3_BASE_URL + "warframe.jpg"),
                        new GetSpace("Guild Wars", "guildwars", S3_BASE_URL + "guildwars.jpg"),
                        new GetSpace("Star Citizen", "starcitizen", S3_BASE_URL + "starcitizen.jpg"),
                        new GetSpace("Halo", "halo", S3_BASE_URL + "halo.jpg"),
                        new GetSpace("The First Descendant", "firstdescendant", S3_BASE_URL + "firstdescendant.jpg"),
                        new GetSpace("Stellar Blade", "stellarblade", S3_BASE_URL + "stellarblade.jpg"),
                        new GetSpace("FNAF", "fnaf", S3_BASE_URL + "fnaf.jpg"),
                        new GetSpace("Cities Skylines", "citiesskylines", S3_BASE_URL + "citiesskylines.jpg"),
                        new GetSpace("Mount and Blade", "mountandblade", S3_BASE_URL + "mountandblade.jpg"),
                        new GetSpace("Battlefront", "battlefront", S3_BASE_URL + "battlefront.jpg"),
                        new GetSpace("Battlefield", "battlefield", S3_BASE_URL + "battlefield.jpg"),
                        new GetSpace("Arma", "arma", S3_BASE_URL + "arma.jpg"),
                        new GetSpace("Dragon Age", "dragonage", S3_BASE_URL + "dragonage.jpg"),
                        new GetSpace("DragonFable", "dragonfable", S3_BASE_URL + "dragonfable.jpg"),
                        new GetSpace("Assassin's Creed", "assassinscreed", S3_BASE_URL + "assassinscreed.jpg"),
                        new GetSpace("Ghost of Tsushima", "ghostoftsushima", S3_BASE_URL + "ghostoftsushima.jpg"),
                        new GetSpace("Red Dead Redemption", "rdr", S3_BASE_URL + "rdr.jpg"),
                        new GetSpace("Grand Theft Auto", "gta", S3_BASE_URL + "gta.jpg"),
                        new GetSpace("Saint's Row", "saintsrow", S3_BASE_URL + "saintsrow.jpg"),
                        new GetSpace("Dishonored", "dishonored", S3_BASE_URL + "dishonored.jpg"),
                        new GetSpace("Guitar Hero", "guitarhero", S3_BASE_URL + "guitarhero.jpg"),
                        new GetSpace("Rock Band", "rockband", S3_BASE_URL + "rockband.jpg"),
                        new GetSpace("Borderlands", "borderlands", S3_BASE_URL + "borderlands.jpg"),
                        new GetSpace("The Witcher III", "thewitcher3", S3_BASE_URL + "thewitcher3.jpg"),
                        new GetSpace("MLB The Show", "mlbtheshow", S3_BASE_URL + "mlbtheshow.jpg"),
                        new GetSpace("Animal Crossing", "animalcrossing", S3_BASE_URL + "animalcrossing.jpg"),
                        new GetSpace("Deus Ex", "deusex", S3_BASE_URL + "deusex.jpg"),
                        new GetSpace("Cyberpunk 2077", "cyberpunk2077", S3_BASE_URL + "cyberpunk2077.jpg"),
                        new GetSpace("Mortal Kombat", "mortalkombat", S3_BASE_URL + "mortalkombat.jpg"),
                        new GetSpace("Baldur's Gate 3", "baldursgate", S3_BASE_URL + "baldursgate.jpg"));

        public static Map<String, GetSpace> SPACE_MAP = SPACES.stream()
                        .collect(Collectors.toMap(space -> space.id, space -> space));
}