server.address=0.0.0.0
server.port=${PORT:8080}
aws.access-key=${AWS_ACCESS_KEY_ID}
aws.secret-key=${AWS_SECRET_ACCESS_KEY}
aws.region=us-east-2
abios.secret=${ABIOS_SECRET}

# Apollo Config properties
backend.api.url=https://apollo-backend-dev-67f2c629cfb2.herokuapp.com
backend.api.web.socket.url=wss://apollo-backend-dev-67f2c629cfb2.herokuapp.com
backend.api.domain=apollo-backend-dev-67f2c629cfb2.herokuapp.com
backend.frontend.url=https://your-vercel-app.vercel.app