server.address=0.0.0.0
server.port=8080
aws.access-key=${AWS_ACCESS_KEY_ID}
aws.secret-key=${AWS_SECRET_ACCESS_KEY}
aws.region=us-east-2
abios.secret=${ABIOS_SECRET}

# Apollo Config properties
backend.api.url=http://localhost:8080
backend.api.web.socket.url=ws://localhost:8080
backend.api.domain=localhost
backend.frontend.url=http://localhost:5173