server.address=0.0.0.0
server.port=8080
aws.access-key=${AWS_ACCESS_KEY_ID}
aws.secret-key=${AWS_SECRET_ACCESS_KEY}
aws.region=us-east-2
abios.secret=${ABIOS_SECRET}

# Apollo Config properties
backend.api.url=${BACKEND_URL}
backend.api.web.socket.url=${WEBSOCKET_URL}
backend.api.domain=${DOMAIN}
backend.frontend.url=${FRONTEND_URL}