/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.apollo.backend.data;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class Age implements org.apache.thrift.TBase<Age, Age._Fields>, java.io.Serializable, Cloneable, Comparable<Age> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Age");

  private static final org.apache.thrift.protocol.TField PRECISION_FIELD_DESC = new org.apache.thrift.protocol.TField("precision", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField YEARS_FIELD_DESC = new org.apache.thrift.protocol.TField("years", org.apache.thrift.protocol.TType.I32, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new AgeStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new AgeTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String precision; // required
  public int years; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PRECISION((short)1, "precision"),
    YEARS((short)2, "years");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PRECISION
          return PRECISION;
        case 2: // YEARS
          return YEARS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __YEARS_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PRECISION, new org.apache.thrift.meta_data.FieldMetaData("precision", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.YEARS, new org.apache.thrift.meta_data.FieldMetaData("years", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Age.class, metaDataMap);
  }

  public Age() {
  }

  public Age(
    java.lang.String precision,
    int years)
  {
    this();
    this.precision = precision;
    this.years = years;
    setYearsIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Age(Age other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetPrecision()) {
      this.precision = other.precision;
    }
    this.years = other.years;
  }

  @Override
  public Age deepCopy() {
    return new Age(this);
  }

  @Override
  public void clear() {
    this.precision = null;
    setYearsIsSet(false);
    this.years = 0;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getPrecision() {
    return this.precision;
  }

  public Age setPrecision(@org.apache.thrift.annotation.Nullable java.lang.String precision) {
    this.precision = precision;
    return this;
  }

  public void unsetPrecision() {
    this.precision = null;
  }

  /** Returns true if field precision is set (has been assigned a value) and false otherwise */
  public boolean isSetPrecision() {
    return this.precision != null;
  }

  public void setPrecisionIsSet(boolean value) {
    if (!value) {
      this.precision = null;
    }
  }

  public int getYears() {
    return this.years;
  }

  public Age setYears(int years) {
    this.years = years;
    setYearsIsSet(true);
    return this;
  }

  public void unsetYears() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __YEARS_ISSET_ID);
  }

  /** Returns true if field years is set (has been assigned a value) and false otherwise */
  public boolean isSetYears() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __YEARS_ISSET_ID);
  }

  public void setYearsIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __YEARS_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case PRECISION:
      if (value == null) {
        unsetPrecision();
      } else {
        setPrecision((java.lang.String)value);
      }
      break;

    case YEARS:
      if (value == null) {
        unsetYears();
      } else {
        setYears((java.lang.Integer)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case PRECISION:
      return getPrecision();

    case YEARS:
      return getYears();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case PRECISION:
      return isSetPrecision();
    case YEARS:
      return isSetYears();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof Age)
      return this.equals((Age)that);
    return false;
  }

  public boolean equals(Age that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_precision = true && this.isSetPrecision();
    boolean that_present_precision = true && that.isSetPrecision();
    if (this_present_precision || that_present_precision) {
      if (!(this_present_precision && that_present_precision))
        return false;
      if (!this.precision.equals(that.precision))
        return false;
    }

    boolean this_present_years = true;
    boolean that_present_years = true;
    if (this_present_years || that_present_years) {
      if (!(this_present_years && that_present_years))
        return false;
      if (this.years != that.years)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetPrecision()) ? 131071 : 524287);
    if (isSetPrecision())
      hashCode = hashCode * 8191 + precision.hashCode();

    hashCode = hashCode * 8191 + years;

    return hashCode;
  }

  @Override
  public int compareTo(Age other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetPrecision(), other.isSetPrecision());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPrecision()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.precision, other.precision);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetYears(), other.isSetYears());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetYears()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.years, other.years);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Age(");
    boolean first = true;

    sb.append("precision:");
    if (this.precision == null) {
      sb.append("null");
    } else {
      sb.append(this.precision);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("years:");
    sb.append(this.years);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class AgeStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public AgeStandardScheme getScheme() {
      return new AgeStandardScheme();
    }
  }

  private static class AgeStandardScheme extends org.apache.thrift.scheme.StandardScheme<Age> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, Age struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PRECISION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.precision = iprot.readString();
              struct.setPrecisionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // YEARS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.years = iprot.readI32();
              struct.setYearsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, Age struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.precision != null) {
        oprot.writeFieldBegin(PRECISION_FIELD_DESC);
        oprot.writeString(struct.precision);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(YEARS_FIELD_DESC);
      oprot.writeI32(struct.years);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class AgeTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public AgeTupleScheme getScheme() {
      return new AgeTupleScheme();
    }
  }

  private static class AgeTupleScheme extends org.apache.thrift.scheme.TupleScheme<Age> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Age struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetPrecision()) {
        optionals.set(0);
      }
      if (struct.isSetYears()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetPrecision()) {
        oprot.writeString(struct.precision);
      }
      if (struct.isSetYears()) {
        oprot.writeI32(struct.years);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Age struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.precision = iprot.readString();
        struct.setPrecisionIsSet(true);
      }
      if (incoming.get(1)) {
        struct.years = iprot.readI32();
        struct.setYearsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

