/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.apollo.backend.data;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class LolMatchTimeline implements org.apache.thrift.TBase<LolMatchTimeline, LolMatchTimeline._Fields>, java.io.Serializable, Cloneable, Comparable<LolMatchTimeline> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("LolMatchTimeline");

  private static final org.apache.thrift.protocol.TField PHASE_FIELD_DESC = new org.apache.thrift.protocol.TField("phase", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField START_FIELD_DESC = new org.apache.thrift.protocol.TField("start", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField END_FIELD_DESC = new org.apache.thrift.protocol.TField("end", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField CLOCK_FIELD_DESC = new org.apache.thrift.protocol.TField("clock", org.apache.thrift.protocol.TType.STRUCT, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new LolMatchTimelineStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new LolMatchTimelineTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String phase; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String start; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String end; // required
  public @org.apache.thrift.annotation.Nullable LolMatchClock clock; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PHASE((short)1, "phase"),
    START((short)2, "start"),
    END((short)3, "end"),
    CLOCK((short)4, "clock");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PHASE
          return PHASE;
        case 2: // START
          return START;
        case 3: // END
          return END;
        case 4: // CLOCK
          return CLOCK;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PHASE, new org.apache.thrift.meta_data.FieldMetaData("phase", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.START, new org.apache.thrift.meta_data.FieldMetaData("start", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.END, new org.apache.thrift.meta_data.FieldMetaData("end", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CLOCK, new org.apache.thrift.meta_data.FieldMetaData("clock", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, LolMatchClock.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(LolMatchTimeline.class, metaDataMap);
  }

  public LolMatchTimeline() {
  }

  public LolMatchTimeline(
    java.lang.String phase,
    java.lang.String start,
    java.lang.String end,
    LolMatchClock clock)
  {
    this();
    this.phase = phase;
    this.start = start;
    this.end = end;
    this.clock = clock;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public LolMatchTimeline(LolMatchTimeline other) {
    if (other.isSetPhase()) {
      this.phase = other.phase;
    }
    if (other.isSetStart()) {
      this.start = other.start;
    }
    if (other.isSetEnd()) {
      this.end = other.end;
    }
    if (other.isSetClock()) {
      this.clock = new LolMatchClock(other.clock);
    }
  }

  @Override
  public LolMatchTimeline deepCopy() {
    return new LolMatchTimeline(this);
  }

  @Override
  public void clear() {
    this.phase = null;
    this.start = null;
    this.end = null;
    this.clock = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getPhase() {
    return this.phase;
  }

  public LolMatchTimeline setPhase(@org.apache.thrift.annotation.Nullable java.lang.String phase) {
    this.phase = phase;
    return this;
  }

  public void unsetPhase() {
    this.phase = null;
  }

  /** Returns true if field phase is set (has been assigned a value) and false otherwise */
  public boolean isSetPhase() {
    return this.phase != null;
  }

  public void setPhaseIsSet(boolean value) {
    if (!value) {
      this.phase = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getStart() {
    return this.start;
  }

  public LolMatchTimeline setStart(@org.apache.thrift.annotation.Nullable java.lang.String start) {
    this.start = start;
    return this;
  }

  public void unsetStart() {
    this.start = null;
  }

  /** Returns true if field start is set (has been assigned a value) and false otherwise */
  public boolean isSetStart() {
    return this.start != null;
  }

  public void setStartIsSet(boolean value) {
    if (!value) {
      this.start = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getEnd() {
    return this.end;
  }

  public LolMatchTimeline setEnd(@org.apache.thrift.annotation.Nullable java.lang.String end) {
    this.end = end;
    return this;
  }

  public void unsetEnd() {
    this.end = null;
  }

  /** Returns true if field end is set (has been assigned a value) and false otherwise */
  public boolean isSetEnd() {
    return this.end != null;
  }

  public void setEndIsSet(boolean value) {
    if (!value) {
      this.end = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public LolMatchClock getClock() {
    return this.clock;
  }

  public LolMatchTimeline setClock(@org.apache.thrift.annotation.Nullable LolMatchClock clock) {
    this.clock = clock;
    return this;
  }

  public void unsetClock() {
    this.clock = null;
  }

  /** Returns true if field clock is set (has been assigned a value) and false otherwise */
  public boolean isSetClock() {
    return this.clock != null;
  }

  public void setClockIsSet(boolean value) {
    if (!value) {
      this.clock = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case PHASE:
      if (value == null) {
        unsetPhase();
      } else {
        setPhase((java.lang.String)value);
      }
      break;

    case START:
      if (value == null) {
        unsetStart();
      } else {
        setStart((java.lang.String)value);
      }
      break;

    case END:
      if (value == null) {
        unsetEnd();
      } else {
        setEnd((java.lang.String)value);
      }
      break;

    case CLOCK:
      if (value == null) {
        unsetClock();
      } else {
        setClock((LolMatchClock)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case PHASE:
      return getPhase();

    case START:
      return getStart();

    case END:
      return getEnd();

    case CLOCK:
      return getClock();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case PHASE:
      return isSetPhase();
    case START:
      return isSetStart();
    case END:
      return isSetEnd();
    case CLOCK:
      return isSetClock();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof LolMatchTimeline)
      return this.equals((LolMatchTimeline)that);
    return false;
  }

  public boolean equals(LolMatchTimeline that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_phase = true && this.isSetPhase();
    boolean that_present_phase = true && that.isSetPhase();
    if (this_present_phase || that_present_phase) {
      if (!(this_present_phase && that_present_phase))
        return false;
      if (!this.phase.equals(that.phase))
        return false;
    }

    boolean this_present_start = true && this.isSetStart();
    boolean that_present_start = true && that.isSetStart();
    if (this_present_start || that_present_start) {
      if (!(this_present_start && that_present_start))
        return false;
      if (!this.start.equals(that.start))
        return false;
    }

    boolean this_present_end = true && this.isSetEnd();
    boolean that_present_end = true && that.isSetEnd();
    if (this_present_end || that_present_end) {
      if (!(this_present_end && that_present_end))
        return false;
      if (!this.end.equals(that.end))
        return false;
    }

    boolean this_present_clock = true && this.isSetClock();
    boolean that_present_clock = true && that.isSetClock();
    if (this_present_clock || that_present_clock) {
      if (!(this_present_clock && that_present_clock))
        return false;
      if (!this.clock.equals(that.clock))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetPhase()) ? 131071 : 524287);
    if (isSetPhase())
      hashCode = hashCode * 8191 + phase.hashCode();

    hashCode = hashCode * 8191 + ((isSetStart()) ? 131071 : 524287);
    if (isSetStart())
      hashCode = hashCode * 8191 + start.hashCode();

    hashCode = hashCode * 8191 + ((isSetEnd()) ? 131071 : 524287);
    if (isSetEnd())
      hashCode = hashCode * 8191 + end.hashCode();

    hashCode = hashCode * 8191 + ((isSetClock()) ? 131071 : 524287);
    if (isSetClock())
      hashCode = hashCode * 8191 + clock.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(LolMatchTimeline other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetPhase(), other.isSetPhase());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPhase()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.phase, other.phase);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetStart(), other.isSetStart());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStart()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.start, other.start);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetEnd(), other.isSetEnd());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEnd()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.end, other.end);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetClock(), other.isSetClock());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetClock()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.clock, other.clock);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("LolMatchTimeline(");
    boolean first = true;

    sb.append("phase:");
    if (this.phase == null) {
      sb.append("null");
    } else {
      sb.append(this.phase);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("start:");
    if (this.start == null) {
      sb.append("null");
    } else {
      sb.append(this.start);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("end:");
    if (this.end == null) {
      sb.append("null");
    } else {
      sb.append(this.end);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("clock:");
    if (this.clock == null) {
      sb.append("null");
    } else {
      sb.append(this.clock);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (clock != null) {
      clock.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class LolMatchTimelineStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public LolMatchTimelineStandardScheme getScheme() {
      return new LolMatchTimelineStandardScheme();
    }
  }

  private static class LolMatchTimelineStandardScheme extends org.apache.thrift.scheme.StandardScheme<LolMatchTimeline> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, LolMatchTimeline struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PHASE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.phase = iprot.readString();
              struct.setPhaseIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // START
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.start = iprot.readString();
              struct.setStartIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // END
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.end = iprot.readString();
              struct.setEndIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // CLOCK
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.clock = new LolMatchClock();
              struct.clock.read(iprot);
              struct.setClockIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, LolMatchTimeline struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.phase != null) {
        oprot.writeFieldBegin(PHASE_FIELD_DESC);
        oprot.writeString(struct.phase);
        oprot.writeFieldEnd();
      }
      if (struct.start != null) {
        oprot.writeFieldBegin(START_FIELD_DESC);
        oprot.writeString(struct.start);
        oprot.writeFieldEnd();
      }
      if (struct.end != null) {
        oprot.writeFieldBegin(END_FIELD_DESC);
        oprot.writeString(struct.end);
        oprot.writeFieldEnd();
      }
      if (struct.clock != null) {
        oprot.writeFieldBegin(CLOCK_FIELD_DESC);
        struct.clock.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class LolMatchTimelineTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public LolMatchTimelineTupleScheme getScheme() {
      return new LolMatchTimelineTupleScheme();
    }
  }

  private static class LolMatchTimelineTupleScheme extends org.apache.thrift.scheme.TupleScheme<LolMatchTimeline> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, LolMatchTimeline struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetPhase()) {
        optionals.set(0);
      }
      if (struct.isSetStart()) {
        optionals.set(1);
      }
      if (struct.isSetEnd()) {
        optionals.set(2);
      }
      if (struct.isSetClock()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetPhase()) {
        oprot.writeString(struct.phase);
      }
      if (struct.isSetStart()) {
        oprot.writeString(struct.start);
      }
      if (struct.isSetEnd()) {
        oprot.writeString(struct.end);
      }
      if (struct.isSetClock()) {
        struct.clock.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, LolMatchTimeline struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.phase = iprot.readString();
        struct.setPhaseIsSet(true);
      }
      if (incoming.get(1)) {
        struct.start = iprot.readString();
        struct.setStartIsSet(true);
      }
      if (incoming.get(2)) {
        struct.end = iprot.readString();
        struct.setEndIsSet(true);
      }
      if (incoming.get(3)) {
        struct.clock = new LolMatchClock();
        struct.clock.read(iprot);
        struct.setClockIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

