/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.apollo.backend.data;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class LolNeutralCreepKills implements org.apache.thrift.TBase<LolNeutralCreepKills, LolNeutralCreepKills._Fields>, java.io.Serializable, Cloneable, Comparable<LolNeutralCreepKills> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("LolNeutralCreepKills");

  private static final org.apache.thrift.protocol.TField PER_ELITE_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("perEliteType", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new LolNeutralCreepKillsStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new LolNeutralCreepKillsTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.util.List<LolEliteCreepKills> perEliteType; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PER_ELITE_TYPE((short)1, "perEliteType");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PER_ELITE_TYPE
          return PER_ELITE_TYPE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PER_ELITE_TYPE, new org.apache.thrift.meta_data.FieldMetaData("perEliteType", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, LolEliteCreepKills.class))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(LolNeutralCreepKills.class, metaDataMap);
  }

  public LolNeutralCreepKills() {
  }

  public LolNeutralCreepKills(
    java.util.List<LolEliteCreepKills> perEliteType)
  {
    this();
    this.perEliteType = perEliteType;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public LolNeutralCreepKills(LolNeutralCreepKills other) {
    if (other.isSetPerEliteType()) {
      java.util.List<LolEliteCreepKills> __this__perEliteType = new java.util.ArrayList<LolEliteCreepKills>(other.perEliteType.size());
      for (LolEliteCreepKills other_element : other.perEliteType) {
        __this__perEliteType.add(new LolEliteCreepKills(other_element));
      }
      this.perEliteType = __this__perEliteType;
    }
  }

  @Override
  public LolNeutralCreepKills deepCopy() {
    return new LolNeutralCreepKills(this);
  }

  @Override
  public void clear() {
    this.perEliteType = null;
  }

  public int getPerEliteTypeSize() {
    return (this.perEliteType == null) ? 0 : this.perEliteType.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<LolEliteCreepKills> getPerEliteTypeIterator() {
    return (this.perEliteType == null) ? null : this.perEliteType.iterator();
  }

  public void addToPerEliteType(LolEliteCreepKills elem) {
    if (this.perEliteType == null) {
      this.perEliteType = new java.util.ArrayList<LolEliteCreepKills>();
    }
    this.perEliteType.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<LolEliteCreepKills> getPerEliteType() {
    return this.perEliteType;
  }

  public LolNeutralCreepKills setPerEliteType(@org.apache.thrift.annotation.Nullable java.util.List<LolEliteCreepKills> perEliteType) {
    this.perEliteType = perEliteType;
    return this;
  }

  public void unsetPerEliteType() {
    this.perEliteType = null;
  }

  /** Returns true if field perEliteType is set (has been assigned a value) and false otherwise */
  public boolean isSetPerEliteType() {
    return this.perEliteType != null;
  }

  public void setPerEliteTypeIsSet(boolean value) {
    if (!value) {
      this.perEliteType = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case PER_ELITE_TYPE:
      if (value == null) {
        unsetPerEliteType();
      } else {
        setPerEliteType((java.util.List<LolEliteCreepKills>)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case PER_ELITE_TYPE:
      return getPerEliteType();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case PER_ELITE_TYPE:
      return isSetPerEliteType();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof LolNeutralCreepKills)
      return this.equals((LolNeutralCreepKills)that);
    return false;
  }

  public boolean equals(LolNeutralCreepKills that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_perEliteType = true && this.isSetPerEliteType();
    boolean that_present_perEliteType = true && that.isSetPerEliteType();
    if (this_present_perEliteType || that_present_perEliteType) {
      if (!(this_present_perEliteType && that_present_perEliteType))
        return false;
      if (!this.perEliteType.equals(that.perEliteType))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetPerEliteType()) ? 131071 : 524287);
    if (isSetPerEliteType())
      hashCode = hashCode * 8191 + perEliteType.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(LolNeutralCreepKills other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetPerEliteType(), other.isSetPerEliteType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPerEliteType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.perEliteType, other.perEliteType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("LolNeutralCreepKills(");
    boolean first = true;

    sb.append("perEliteType:");
    if (this.perEliteType == null) {
      sb.append("null");
    } else {
      sb.append(this.perEliteType);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class LolNeutralCreepKillsStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public LolNeutralCreepKillsStandardScheme getScheme() {
      return new LolNeutralCreepKillsStandardScheme();
    }
  }

  private static class LolNeutralCreepKillsStandardScheme extends org.apache.thrift.scheme.StandardScheme<LolNeutralCreepKills> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, LolNeutralCreepKills struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PER_ELITE_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list408 = iprot.readListBegin();
                struct.perEliteType = new java.util.ArrayList<LolEliteCreepKills>(_list408.size);
                @org.apache.thrift.annotation.Nullable LolEliteCreepKills _elem409;
                for (int _i410 = 0; _i410 < _list408.size; ++_i410)
                {
                  _elem409 = new LolEliteCreepKills();
                  _elem409.read(iprot);
                  struct.perEliteType.add(_elem409);
                }
                iprot.readListEnd();
              }
              struct.setPerEliteTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, LolNeutralCreepKills struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.perEliteType != null) {
        oprot.writeFieldBegin(PER_ELITE_TYPE_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.perEliteType.size()));
          for (LolEliteCreepKills _iter411 : struct.perEliteType)
          {
            _iter411.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class LolNeutralCreepKillsTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public LolNeutralCreepKillsTupleScheme getScheme() {
      return new LolNeutralCreepKillsTupleScheme();
    }
  }

  private static class LolNeutralCreepKillsTupleScheme extends org.apache.thrift.scheme.TupleScheme<LolNeutralCreepKills> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, LolNeutralCreepKills struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetPerEliteType()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetPerEliteType()) {
        {
          oprot.writeI32(struct.perEliteType.size());
          for (LolEliteCreepKills _iter412 : struct.perEliteType)
          {
            _iter412.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, LolNeutralCreepKills struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list413 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
          struct.perEliteType = new java.util.ArrayList<LolEliteCreepKills>(_list413.size);
          @org.apache.thrift.annotation.Nullable LolEliteCreepKills _elem414;
          for (int _i415 = 0; _i415 < _list413.size; ++_i415)
          {
            _elem414 = new LolEliteCreepKills();
            _elem414.read(iprot);
            struct.perEliteType.add(_elem414);
          }
        }
        struct.setPerEliteTypeIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

