/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.apollo.backend.data;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class LolPits implements org.apache.thrift.TBase<LolPits, LolPits._Fields>, java.io.Serializable, Cloneable, Comparable<LolPits> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("LolPits");

  private static final org.apache.thrift.protocol.TField DRAGON_PIT_FIELD_DESC = new org.apache.thrift.protocol.TField("dragonPit", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField BARON_PIT_FIELD_DESC = new org.apache.thrift.protocol.TField("baronPit", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new LolPitsStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new LolPitsTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable LolPit dragonPit; // required
  public @org.apache.thrift.annotation.Nullable LolPit baronPit; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    DRAGON_PIT((short)1, "dragonPit"),
    BARON_PIT((short)2, "baronPit");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // DRAGON_PIT
          return DRAGON_PIT;
        case 2: // BARON_PIT
          return BARON_PIT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.DRAGON_PIT, new org.apache.thrift.meta_data.FieldMetaData("dragonPit", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, LolPit.class)));
    tmpMap.put(_Fields.BARON_PIT, new org.apache.thrift.meta_data.FieldMetaData("baronPit", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, LolPit.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(LolPits.class, metaDataMap);
  }

  public LolPits() {
  }

  public LolPits(
    LolPit dragonPit,
    LolPit baronPit)
  {
    this();
    this.dragonPit = dragonPit;
    this.baronPit = baronPit;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public LolPits(LolPits other) {
    if (other.isSetDragonPit()) {
      this.dragonPit = new LolPit(other.dragonPit);
    }
    if (other.isSetBaronPit()) {
      this.baronPit = new LolPit(other.baronPit);
    }
  }

  @Override
  public LolPits deepCopy() {
    return new LolPits(this);
  }

  @Override
  public void clear() {
    this.dragonPit = null;
    this.baronPit = null;
  }

  @org.apache.thrift.annotation.Nullable
  public LolPit getDragonPit() {
    return this.dragonPit;
  }

  public LolPits setDragonPit(@org.apache.thrift.annotation.Nullable LolPit dragonPit) {
    this.dragonPit = dragonPit;
    return this;
  }

  public void unsetDragonPit() {
    this.dragonPit = null;
  }

  /** Returns true if field dragonPit is set (has been assigned a value) and false otherwise */
  public boolean isSetDragonPit() {
    return this.dragonPit != null;
  }

  public void setDragonPitIsSet(boolean value) {
    if (!value) {
      this.dragonPit = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public LolPit getBaronPit() {
    return this.baronPit;
  }

  public LolPits setBaronPit(@org.apache.thrift.annotation.Nullable LolPit baronPit) {
    this.baronPit = baronPit;
    return this;
  }

  public void unsetBaronPit() {
    this.baronPit = null;
  }

  /** Returns true if field baronPit is set (has been assigned a value) and false otherwise */
  public boolean isSetBaronPit() {
    return this.baronPit != null;
  }

  public void setBaronPitIsSet(boolean value) {
    if (!value) {
      this.baronPit = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case DRAGON_PIT:
      if (value == null) {
        unsetDragonPit();
      } else {
        setDragonPit((LolPit)value);
      }
      break;

    case BARON_PIT:
      if (value == null) {
        unsetBaronPit();
      } else {
        setBaronPit((LolPit)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case DRAGON_PIT:
      return getDragonPit();

    case BARON_PIT:
      return getBaronPit();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case DRAGON_PIT:
      return isSetDragonPit();
    case BARON_PIT:
      return isSetBaronPit();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof LolPits)
      return this.equals((LolPits)that);
    return false;
  }

  public boolean equals(LolPits that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_dragonPit = true && this.isSetDragonPit();
    boolean that_present_dragonPit = true && that.isSetDragonPit();
    if (this_present_dragonPit || that_present_dragonPit) {
      if (!(this_present_dragonPit && that_present_dragonPit))
        return false;
      if (!this.dragonPit.equals(that.dragonPit))
        return false;
    }

    boolean this_present_baronPit = true && this.isSetBaronPit();
    boolean that_present_baronPit = true && that.isSetBaronPit();
    if (this_present_baronPit || that_present_baronPit) {
      if (!(this_present_baronPit && that_present_baronPit))
        return false;
      if (!this.baronPit.equals(that.baronPit))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetDragonPit()) ? 131071 : 524287);
    if (isSetDragonPit())
      hashCode = hashCode * 8191 + dragonPit.hashCode();

    hashCode = hashCode * 8191 + ((isSetBaronPit()) ? 131071 : 524287);
    if (isSetBaronPit())
      hashCode = hashCode * 8191 + baronPit.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(LolPits other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetDragonPit(), other.isSetDragonPit());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDragonPit()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dragonPit, other.dragonPit);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetBaronPit(), other.isSetBaronPit());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBaronPit()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.baronPit, other.baronPit);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("LolPits(");
    boolean first = true;

    sb.append("dragonPit:");
    if (this.dragonPit == null) {
      sb.append("null");
    } else {
      sb.append(this.dragonPit);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("baronPit:");
    if (this.baronPit == null) {
      sb.append("null");
    } else {
      sb.append(this.baronPit);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (dragonPit != null) {
      dragonPit.validate();
    }
    if (baronPit != null) {
      baronPit.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class LolPitsStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public LolPitsStandardScheme getScheme() {
      return new LolPitsStandardScheme();
    }
  }

  private static class LolPitsStandardScheme extends org.apache.thrift.scheme.StandardScheme<LolPits> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, LolPits struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // DRAGON_PIT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.dragonPit = new LolPit();
              struct.dragonPit.read(iprot);
              struct.setDragonPitIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // BARON_PIT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.baronPit = new LolPit();
              struct.baronPit.read(iprot);
              struct.setBaronPitIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, LolPits struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.dragonPit != null) {
        oprot.writeFieldBegin(DRAGON_PIT_FIELD_DESC);
        struct.dragonPit.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.baronPit != null) {
        oprot.writeFieldBegin(BARON_PIT_FIELD_DESC);
        struct.baronPit.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class LolPitsTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public LolPitsTupleScheme getScheme() {
      return new LolPitsTupleScheme();
    }
  }

  private static class LolPitsTupleScheme extends org.apache.thrift.scheme.TupleScheme<LolPits> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, LolPits struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetDragonPit()) {
        optionals.set(0);
      }
      if (struct.isSetBaronPit()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetDragonPit()) {
        struct.dragonPit.write(oprot);
      }
      if (struct.isSetBaronPit()) {
        struct.baronPit.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, LolPits struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.dragonPit = new LolPit();
        struct.dragonPit.read(iprot);
        struct.setDragonPitIsSet(true);
      }
      if (incoming.get(1)) {
        struct.baronPit = new LolPit();
        struct.baronPit.read(iprot);
        struct.setBaronPitIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

