/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.apollo.backend.data;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class LolPlayerSummary implements org.apache.thrift.TBase<LolPlayerSummary, LolPlayerSummary._Fields>, java.io.Serializable, Cloneable, Comparable<LolPlayerSummary> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("LolPlayerSummary");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField UI_INDEX_FIELD_DESC = new org.apache.thrift.protocol.TField("uiIndex", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField CHAMPION_FIELD_DESC = new org.apache.thrift.protocol.TField("champion", org.apache.thrift.protocol.TType.STRUCT, (short)3);
  private static final org.apache.thrift.protocol.TField KILLS_FIELD_DESC = new org.apache.thrift.protocol.TField("kills", org.apache.thrift.protocol.TType.STRUCT, (short)4);
  private static final org.apache.thrift.protocol.TField ASSISTS_FIELD_DESC = new org.apache.thrift.protocol.TField("assists", org.apache.thrift.protocol.TType.STRUCT, (short)5);
  private static final org.apache.thrift.protocol.TField DEATHS_FIELD_DESC = new org.apache.thrift.protocol.TField("deaths", org.apache.thrift.protocol.TType.STRUCT, (short)6);
  private static final org.apache.thrift.protocol.TField REVIVES_FIELD_DESC = new org.apache.thrift.protocol.TField("revives", org.apache.thrift.protocol.TType.STRUCT, (short)7);
  private static final org.apache.thrift.protocol.TField MULTI_KILLS_FIELD_DESC = new org.apache.thrift.protocol.TField("multiKills", org.apache.thrift.protocol.TType.LIST, (short)8);
  private static final org.apache.thrift.protocol.TField KILL_STREAKS_FIELD_DESC = new org.apache.thrift.protocol.TField("killStreaks", org.apache.thrift.protocol.TType.LIST, (short)9);
  private static final org.apache.thrift.protocol.TField ITEMS_FIELD_DESC = new org.apache.thrift.protocol.TField("items", org.apache.thrift.protocol.TType.STRUCT, (short)10);
  private static final org.apache.thrift.protocol.TField SUMMONER_SPELLS_FIELD_DESC = new org.apache.thrift.protocol.TField("summonerSpells", org.apache.thrift.protocol.TType.LIST, (short)11);
  private static final org.apache.thrift.protocol.TField CREEPS_FIELD_DESC = new org.apache.thrift.protocol.TField("creeps", org.apache.thrift.protocol.TType.STRUCT, (short)12);
  private static final org.apache.thrift.protocol.TField KEYSTONE_FIELD_DESC = new org.apache.thrift.protocol.TField("keystone", org.apache.thrift.protocol.TType.STRUCT, (short)13);
  private static final org.apache.thrift.protocol.TField POSITION_FIELD_DESC = new org.apache.thrift.protocol.TField("position", org.apache.thrift.protocol.TType.STRUCT, (short)14);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new LolPlayerSummaryStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new LolPlayerSummaryTupleSchemeFactory();

  public int id; // required
  public int uiIndex; // required
  public @org.apache.thrift.annotation.Nullable LolChampion champion; // required
  public @org.apache.thrift.annotation.Nullable LolKills kills; // required
  public @org.apache.thrift.annotation.Nullable LolAssists assists; // required
  public @org.apache.thrift.annotation.Nullable LolDeaths deaths; // required
  public @org.apache.thrift.annotation.Nullable LolRevives revives; // required
  public @org.apache.thrift.annotation.Nullable java.util.List<LolMultiKill> multiKills; // optional
  public @org.apache.thrift.annotation.Nullable java.util.List<java.lang.Integer> killStreaks; // required
  public @org.apache.thrift.annotation.Nullable LolItems items; // required
  public @org.apache.thrift.annotation.Nullable java.util.List<LolSummonerSpell> summonerSpells; // required
  public @org.apache.thrift.annotation.Nullable LolCreeps creeps; // required
  public @org.apache.thrift.annotation.Nullable LolKeystone keystone; // optional
  public @org.apache.thrift.annotation.Nullable LolPosition position; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    UI_INDEX((short)2, "uiIndex"),
    CHAMPION((short)3, "champion"),
    KILLS((short)4, "kills"),
    ASSISTS((short)5, "assists"),
    DEATHS((short)6, "deaths"),
    REVIVES((short)7, "revives"),
    MULTI_KILLS((short)8, "multiKills"),
    KILL_STREAKS((short)9, "killStreaks"),
    ITEMS((short)10, "items"),
    SUMMONER_SPELLS((short)11, "summonerSpells"),
    CREEPS((short)12, "creeps"),
    KEYSTONE((short)13, "keystone"),
    POSITION((short)14, "position");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // UI_INDEX
          return UI_INDEX;
        case 3: // CHAMPION
          return CHAMPION;
        case 4: // KILLS
          return KILLS;
        case 5: // ASSISTS
          return ASSISTS;
        case 6: // DEATHS
          return DEATHS;
        case 7: // REVIVES
          return REVIVES;
        case 8: // MULTI_KILLS
          return MULTI_KILLS;
        case 9: // KILL_STREAKS
          return KILL_STREAKS;
        case 10: // ITEMS
          return ITEMS;
        case 11: // SUMMONER_SPELLS
          return SUMMONER_SPELLS;
        case 12: // CREEPS
          return CREEPS;
        case 13: // KEYSTONE
          return KEYSTONE;
        case 14: // POSITION
          return POSITION;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ID_ISSET_ID = 0;
  private static final int __UIINDEX_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.MULTI_KILLS,_Fields.KEYSTONE,_Fields.POSITION};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.UI_INDEX, new org.apache.thrift.meta_data.FieldMetaData("uiIndex", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.CHAMPION, new org.apache.thrift.meta_data.FieldMetaData("champion", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, LolChampion.class)));
    tmpMap.put(_Fields.KILLS, new org.apache.thrift.meta_data.FieldMetaData("kills", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, LolKills.class)));
    tmpMap.put(_Fields.ASSISTS, new org.apache.thrift.meta_data.FieldMetaData("assists", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, LolAssists.class)));
    tmpMap.put(_Fields.DEATHS, new org.apache.thrift.meta_data.FieldMetaData("deaths", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, LolDeaths.class)));
    tmpMap.put(_Fields.REVIVES, new org.apache.thrift.meta_data.FieldMetaData("revives", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, LolRevives.class)));
    tmpMap.put(_Fields.MULTI_KILLS, new org.apache.thrift.meta_data.FieldMetaData("multiKills", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, LolMultiKill.class))));
    tmpMap.put(_Fields.KILL_STREAKS, new org.apache.thrift.meta_data.FieldMetaData("killStreaks", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32))));
    tmpMap.put(_Fields.ITEMS, new org.apache.thrift.meta_data.FieldMetaData("items", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, LolItems.class)));
    tmpMap.put(_Fields.SUMMONER_SPELLS, new org.apache.thrift.meta_data.FieldMetaData("summonerSpells", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, LolSummonerSpell.class))));
    tmpMap.put(_Fields.CREEPS, new org.apache.thrift.meta_data.FieldMetaData("creeps", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, LolCreeps.class)));
    tmpMap.put(_Fields.KEYSTONE, new org.apache.thrift.meta_data.FieldMetaData("keystone", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, LolKeystone.class)));
    tmpMap.put(_Fields.POSITION, new org.apache.thrift.meta_data.FieldMetaData("position", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, LolPosition.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(LolPlayerSummary.class, metaDataMap);
  }

  public LolPlayerSummary() {
  }

  public LolPlayerSummary(
    int id,
    int uiIndex,
    LolChampion champion,
    LolKills kills,
    LolAssists assists,
    LolDeaths deaths,
    LolRevives revives,
    java.util.List<java.lang.Integer> killStreaks,
    LolItems items,
    java.util.List<LolSummonerSpell> summonerSpells,
    LolCreeps creeps)
  {
    this();
    this.id = id;
    setIdIsSet(true);
    this.uiIndex = uiIndex;
    setUiIndexIsSet(true);
    this.champion = champion;
    this.kills = kills;
    this.assists = assists;
    this.deaths = deaths;
    this.revives = revives;
    this.killStreaks = killStreaks;
    this.items = items;
    this.summonerSpells = summonerSpells;
    this.creeps = creeps;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public LolPlayerSummary(LolPlayerSummary other) {
    __isset_bitfield = other.__isset_bitfield;
    this.id = other.id;
    this.uiIndex = other.uiIndex;
    if (other.isSetChampion()) {
      this.champion = new LolChampion(other.champion);
    }
    if (other.isSetKills()) {
      this.kills = new LolKills(other.kills);
    }
    if (other.isSetAssists()) {
      this.assists = new LolAssists(other.assists);
    }
    if (other.isSetDeaths()) {
      this.deaths = new LolDeaths(other.deaths);
    }
    if (other.isSetRevives()) {
      this.revives = new LolRevives(other.revives);
    }
    if (other.isSetMultiKills()) {
      java.util.List<LolMultiKill> __this__multiKills = new java.util.ArrayList<LolMultiKill>(other.multiKills.size());
      for (LolMultiKill other_element : other.multiKills) {
        __this__multiKills.add(new LolMultiKill(other_element));
      }
      this.multiKills = __this__multiKills;
    }
    if (other.isSetKillStreaks()) {
      java.util.List<java.lang.Integer> __this__killStreaks = new java.util.ArrayList<java.lang.Integer>(other.killStreaks);
      this.killStreaks = __this__killStreaks;
    }
    if (other.isSetItems()) {
      this.items = new LolItems(other.items);
    }
    if (other.isSetSummonerSpells()) {
      java.util.List<LolSummonerSpell> __this__summonerSpells = new java.util.ArrayList<LolSummonerSpell>(other.summonerSpells.size());
      for (LolSummonerSpell other_element : other.summonerSpells) {
        __this__summonerSpells.add(new LolSummonerSpell(other_element));
      }
      this.summonerSpells = __this__summonerSpells;
    }
    if (other.isSetCreeps()) {
      this.creeps = new LolCreeps(other.creeps);
    }
    if (other.isSetKeystone()) {
      this.keystone = new LolKeystone(other.keystone);
    }
    if (other.isSetPosition()) {
      this.position = new LolPosition(other.position);
    }
  }

  @Override
  public LolPlayerSummary deepCopy() {
    return new LolPlayerSummary(this);
  }

  @Override
  public void clear() {
    setIdIsSet(false);
    this.id = 0;
    setUiIndexIsSet(false);
    this.uiIndex = 0;
    this.champion = null;
    this.kills = null;
    this.assists = null;
    this.deaths = null;
    this.revives = null;
    this.multiKills = null;
    this.killStreaks = null;
    this.items = null;
    this.summonerSpells = null;
    this.creeps = null;
    this.keystone = null;
    this.position = null;
  }

  public int getId() {
    return this.id;
  }

  public LolPlayerSummary setId(int id) {
    this.id = id;
    setIdIsSet(true);
    return this;
  }

  public void unsetId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ID_ISSET_ID);
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ID_ISSET_ID);
  }

  public void setIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ID_ISSET_ID, value);
  }

  public int getUiIndex() {
    return this.uiIndex;
  }

  public LolPlayerSummary setUiIndex(int uiIndex) {
    this.uiIndex = uiIndex;
    setUiIndexIsSet(true);
    return this;
  }

  public void unsetUiIndex() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __UIINDEX_ISSET_ID);
  }

  /** Returns true if field uiIndex is set (has been assigned a value) and false otherwise */
  public boolean isSetUiIndex() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __UIINDEX_ISSET_ID);
  }

  public void setUiIndexIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __UIINDEX_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public LolChampion getChampion() {
    return this.champion;
  }

  public LolPlayerSummary setChampion(@org.apache.thrift.annotation.Nullable LolChampion champion) {
    this.champion = champion;
    return this;
  }

  public void unsetChampion() {
    this.champion = null;
  }

  /** Returns true if field champion is set (has been assigned a value) and false otherwise */
  public boolean isSetChampion() {
    return this.champion != null;
  }

  public void setChampionIsSet(boolean value) {
    if (!value) {
      this.champion = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public LolKills getKills() {
    return this.kills;
  }

  public LolPlayerSummary setKills(@org.apache.thrift.annotation.Nullable LolKills kills) {
    this.kills = kills;
    return this;
  }

  public void unsetKills() {
    this.kills = null;
  }

  /** Returns true if field kills is set (has been assigned a value) and false otherwise */
  public boolean isSetKills() {
    return this.kills != null;
  }

  public void setKillsIsSet(boolean value) {
    if (!value) {
      this.kills = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public LolAssists getAssists() {
    return this.assists;
  }

  public LolPlayerSummary setAssists(@org.apache.thrift.annotation.Nullable LolAssists assists) {
    this.assists = assists;
    return this;
  }

  public void unsetAssists() {
    this.assists = null;
  }

  /** Returns true if field assists is set (has been assigned a value) and false otherwise */
  public boolean isSetAssists() {
    return this.assists != null;
  }

  public void setAssistsIsSet(boolean value) {
    if (!value) {
      this.assists = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public LolDeaths getDeaths() {
    return this.deaths;
  }

  public LolPlayerSummary setDeaths(@org.apache.thrift.annotation.Nullable LolDeaths deaths) {
    this.deaths = deaths;
    return this;
  }

  public void unsetDeaths() {
    this.deaths = null;
  }

  /** Returns true if field deaths is set (has been assigned a value) and false otherwise */
  public boolean isSetDeaths() {
    return this.deaths != null;
  }

  public void setDeathsIsSet(boolean value) {
    if (!value) {
      this.deaths = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public LolRevives getRevives() {
    return this.revives;
  }

  public LolPlayerSummary setRevives(@org.apache.thrift.annotation.Nullable LolRevives revives) {
    this.revives = revives;
    return this;
  }

  public void unsetRevives() {
    this.revives = null;
  }

  /** Returns true if field revives is set (has been assigned a value) and false otherwise */
  public boolean isSetRevives() {
    return this.revives != null;
  }

  public void setRevivesIsSet(boolean value) {
    if (!value) {
      this.revives = null;
    }
  }

  public int getMultiKillsSize() {
    return (this.multiKills == null) ? 0 : this.multiKills.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<LolMultiKill> getMultiKillsIterator() {
    return (this.multiKills == null) ? null : this.multiKills.iterator();
  }

  public void addToMultiKills(LolMultiKill elem) {
    if (this.multiKills == null) {
      this.multiKills = new java.util.ArrayList<LolMultiKill>();
    }
    this.multiKills.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<LolMultiKill> getMultiKills() {
    return this.multiKills;
  }

  public LolPlayerSummary setMultiKills(@org.apache.thrift.annotation.Nullable java.util.List<LolMultiKill> multiKills) {
    this.multiKills = multiKills;
    return this;
  }

  public void unsetMultiKills() {
    this.multiKills = null;
  }

  /** Returns true if field multiKills is set (has been assigned a value) and false otherwise */
  public boolean isSetMultiKills() {
    return this.multiKills != null;
  }

  public void setMultiKillsIsSet(boolean value) {
    if (!value) {
      this.multiKills = null;
    }
  }

  public int getKillStreaksSize() {
    return (this.killStreaks == null) ? 0 : this.killStreaks.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.lang.Integer> getKillStreaksIterator() {
    return (this.killStreaks == null) ? null : this.killStreaks.iterator();
  }

  public void addToKillStreaks(int elem) {
    if (this.killStreaks == null) {
      this.killStreaks = new java.util.ArrayList<java.lang.Integer>();
    }
    this.killStreaks.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<java.lang.Integer> getKillStreaks() {
    return this.killStreaks;
  }

  public LolPlayerSummary setKillStreaks(@org.apache.thrift.annotation.Nullable java.util.List<java.lang.Integer> killStreaks) {
    this.killStreaks = killStreaks;
    return this;
  }

  public void unsetKillStreaks() {
    this.killStreaks = null;
  }

  /** Returns true if field killStreaks is set (has been assigned a value) and false otherwise */
  public boolean isSetKillStreaks() {
    return this.killStreaks != null;
  }

  public void setKillStreaksIsSet(boolean value) {
    if (!value) {
      this.killStreaks = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public LolItems getItems() {
    return this.items;
  }

  public LolPlayerSummary setItems(@org.apache.thrift.annotation.Nullable LolItems items) {
    this.items = items;
    return this;
  }

  public void unsetItems() {
    this.items = null;
  }

  /** Returns true if field items is set (has been assigned a value) and false otherwise */
  public boolean isSetItems() {
    return this.items != null;
  }

  public void setItemsIsSet(boolean value) {
    if (!value) {
      this.items = null;
    }
  }

  public int getSummonerSpellsSize() {
    return (this.summonerSpells == null) ? 0 : this.summonerSpells.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<LolSummonerSpell> getSummonerSpellsIterator() {
    return (this.summonerSpells == null) ? null : this.summonerSpells.iterator();
  }

  public void addToSummonerSpells(LolSummonerSpell elem) {
    if (this.summonerSpells == null) {
      this.summonerSpells = new java.util.ArrayList<LolSummonerSpell>();
    }
    this.summonerSpells.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<LolSummonerSpell> getSummonerSpells() {
    return this.summonerSpells;
  }

  public LolPlayerSummary setSummonerSpells(@org.apache.thrift.annotation.Nullable java.util.List<LolSummonerSpell> summonerSpells) {
    this.summonerSpells = summonerSpells;
    return this;
  }

  public void unsetSummonerSpells() {
    this.summonerSpells = null;
  }

  /** Returns true if field summonerSpells is set (has been assigned a value) and false otherwise */
  public boolean isSetSummonerSpells() {
    return this.summonerSpells != null;
  }

  public void setSummonerSpellsIsSet(boolean value) {
    if (!value) {
      this.summonerSpells = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public LolCreeps getCreeps() {
    return this.creeps;
  }

  public LolPlayerSummary setCreeps(@org.apache.thrift.annotation.Nullable LolCreeps creeps) {
    this.creeps = creeps;
    return this;
  }

  public void unsetCreeps() {
    this.creeps = null;
  }

  /** Returns true if field creeps is set (has been assigned a value) and false otherwise */
  public boolean isSetCreeps() {
    return this.creeps != null;
  }

  public void setCreepsIsSet(boolean value) {
    if (!value) {
      this.creeps = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public LolKeystone getKeystone() {
    return this.keystone;
  }

  public LolPlayerSummary setKeystone(@org.apache.thrift.annotation.Nullable LolKeystone keystone) {
    this.keystone = keystone;
    return this;
  }

  public void unsetKeystone() {
    this.keystone = null;
  }

  /** Returns true if field keystone is set (has been assigned a value) and false otherwise */
  public boolean isSetKeystone() {
    return this.keystone != null;
  }

  public void setKeystoneIsSet(boolean value) {
    if (!value) {
      this.keystone = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public LolPosition getPosition() {
    return this.position;
  }

  public LolPlayerSummary setPosition(@org.apache.thrift.annotation.Nullable LolPosition position) {
    this.position = position;
    return this;
  }

  public void unsetPosition() {
    this.position = null;
  }

  /** Returns true if field position is set (has been assigned a value) and false otherwise */
  public boolean isSetPosition() {
    return this.position != null;
  }

  public void setPositionIsSet(boolean value) {
    if (!value) {
      this.position = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((java.lang.Integer)value);
      }
      break;

    case UI_INDEX:
      if (value == null) {
        unsetUiIndex();
      } else {
        setUiIndex((java.lang.Integer)value);
      }
      break;

    case CHAMPION:
      if (value == null) {
        unsetChampion();
      } else {
        setChampion((LolChampion)value);
      }
      break;

    case KILLS:
      if (value == null) {
        unsetKills();
      } else {
        setKills((LolKills)value);
      }
      break;

    case ASSISTS:
      if (value == null) {
        unsetAssists();
      } else {
        setAssists((LolAssists)value);
      }
      break;

    case DEATHS:
      if (value == null) {
        unsetDeaths();
      } else {
        setDeaths((LolDeaths)value);
      }
      break;

    case REVIVES:
      if (value == null) {
        unsetRevives();
      } else {
        setRevives((LolRevives)value);
      }
      break;

    case MULTI_KILLS:
      if (value == null) {
        unsetMultiKills();
      } else {
        setMultiKills((java.util.List<LolMultiKill>)value);
      }
      break;

    case KILL_STREAKS:
      if (value == null) {
        unsetKillStreaks();
      } else {
        setKillStreaks((java.util.List<java.lang.Integer>)value);
      }
      break;

    case ITEMS:
      if (value == null) {
        unsetItems();
      } else {
        setItems((LolItems)value);
      }
      break;

    case SUMMONER_SPELLS:
      if (value == null) {
        unsetSummonerSpells();
      } else {
        setSummonerSpells((java.util.List<LolSummonerSpell>)value);
      }
      break;

    case CREEPS:
      if (value == null) {
        unsetCreeps();
      } else {
        setCreeps((LolCreeps)value);
      }
      break;

    case KEYSTONE:
      if (value == null) {
        unsetKeystone();
      } else {
        setKeystone((LolKeystone)value);
      }
      break;

    case POSITION:
      if (value == null) {
        unsetPosition();
      } else {
        setPosition((LolPosition)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return getId();

    case UI_INDEX:
      return getUiIndex();

    case CHAMPION:
      return getChampion();

    case KILLS:
      return getKills();

    case ASSISTS:
      return getAssists();

    case DEATHS:
      return getDeaths();

    case REVIVES:
      return getRevives();

    case MULTI_KILLS:
      return getMultiKills();

    case KILL_STREAKS:
      return getKillStreaks();

    case ITEMS:
      return getItems();

    case SUMMONER_SPELLS:
      return getSummonerSpells();

    case CREEPS:
      return getCreeps();

    case KEYSTONE:
      return getKeystone();

    case POSITION:
      return getPosition();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case UI_INDEX:
      return isSetUiIndex();
    case CHAMPION:
      return isSetChampion();
    case KILLS:
      return isSetKills();
    case ASSISTS:
      return isSetAssists();
    case DEATHS:
      return isSetDeaths();
    case REVIVES:
      return isSetRevives();
    case MULTI_KILLS:
      return isSetMultiKills();
    case KILL_STREAKS:
      return isSetKillStreaks();
    case ITEMS:
      return isSetItems();
    case SUMMONER_SPELLS:
      return isSetSummonerSpells();
    case CREEPS:
      return isSetCreeps();
    case KEYSTONE:
      return isSetKeystone();
    case POSITION:
      return isSetPosition();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof LolPlayerSummary)
      return this.equals((LolPlayerSummary)that);
    return false;
  }

  public boolean equals(LolPlayerSummary that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_id = true;
    boolean that_present_id = true;
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (this.id != that.id)
        return false;
    }

    boolean this_present_uiIndex = true;
    boolean that_present_uiIndex = true;
    if (this_present_uiIndex || that_present_uiIndex) {
      if (!(this_present_uiIndex && that_present_uiIndex))
        return false;
      if (this.uiIndex != that.uiIndex)
        return false;
    }

    boolean this_present_champion = true && this.isSetChampion();
    boolean that_present_champion = true && that.isSetChampion();
    if (this_present_champion || that_present_champion) {
      if (!(this_present_champion && that_present_champion))
        return false;
      if (!this.champion.equals(that.champion))
        return false;
    }

    boolean this_present_kills = true && this.isSetKills();
    boolean that_present_kills = true && that.isSetKills();
    if (this_present_kills || that_present_kills) {
      if (!(this_present_kills && that_present_kills))
        return false;
      if (!this.kills.equals(that.kills))
        return false;
    }

    boolean this_present_assists = true && this.isSetAssists();
    boolean that_present_assists = true && that.isSetAssists();
    if (this_present_assists || that_present_assists) {
      if (!(this_present_assists && that_present_assists))
        return false;
      if (!this.assists.equals(that.assists))
        return false;
    }

    boolean this_present_deaths = true && this.isSetDeaths();
    boolean that_present_deaths = true && that.isSetDeaths();
    if (this_present_deaths || that_present_deaths) {
      if (!(this_present_deaths && that_present_deaths))
        return false;
      if (!this.deaths.equals(that.deaths))
        return false;
    }

    boolean this_present_revives = true && this.isSetRevives();
    boolean that_present_revives = true && that.isSetRevives();
    if (this_present_revives || that_present_revives) {
      if (!(this_present_revives && that_present_revives))
        return false;
      if (!this.revives.equals(that.revives))
        return false;
    }

    boolean this_present_multiKills = true && this.isSetMultiKills();
    boolean that_present_multiKills = true && that.isSetMultiKills();
    if (this_present_multiKills || that_present_multiKills) {
      if (!(this_present_multiKills && that_present_multiKills))
        return false;
      if (!this.multiKills.equals(that.multiKills))
        return false;
    }

    boolean this_present_killStreaks = true && this.isSetKillStreaks();
    boolean that_present_killStreaks = true && that.isSetKillStreaks();
    if (this_present_killStreaks || that_present_killStreaks) {
      if (!(this_present_killStreaks && that_present_killStreaks))
        return false;
      if (!this.killStreaks.equals(that.killStreaks))
        return false;
    }

    boolean this_present_items = true && this.isSetItems();
    boolean that_present_items = true && that.isSetItems();
    if (this_present_items || that_present_items) {
      if (!(this_present_items && that_present_items))
        return false;
      if (!this.items.equals(that.items))
        return false;
    }

    boolean this_present_summonerSpells = true && this.isSetSummonerSpells();
    boolean that_present_summonerSpells = true && that.isSetSummonerSpells();
    if (this_present_summonerSpells || that_present_summonerSpells) {
      if (!(this_present_summonerSpells && that_present_summonerSpells))
        return false;
      if (!this.summonerSpells.equals(that.summonerSpells))
        return false;
    }

    boolean this_present_creeps = true && this.isSetCreeps();
    boolean that_present_creeps = true && that.isSetCreeps();
    if (this_present_creeps || that_present_creeps) {
      if (!(this_present_creeps && that_present_creeps))
        return false;
      if (!this.creeps.equals(that.creeps))
        return false;
    }

    boolean this_present_keystone = true && this.isSetKeystone();
    boolean that_present_keystone = true && that.isSetKeystone();
    if (this_present_keystone || that_present_keystone) {
      if (!(this_present_keystone && that_present_keystone))
        return false;
      if (!this.keystone.equals(that.keystone))
        return false;
    }

    boolean this_present_position = true && this.isSetPosition();
    boolean that_present_position = true && that.isSetPosition();
    if (this_present_position || that_present_position) {
      if (!(this_present_position && that_present_position))
        return false;
      if (!this.position.equals(that.position))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + id;

    hashCode = hashCode * 8191 + uiIndex;

    hashCode = hashCode * 8191 + ((isSetChampion()) ? 131071 : 524287);
    if (isSetChampion())
      hashCode = hashCode * 8191 + champion.hashCode();

    hashCode = hashCode * 8191 + ((isSetKills()) ? 131071 : 524287);
    if (isSetKills())
      hashCode = hashCode * 8191 + kills.hashCode();

    hashCode = hashCode * 8191 + ((isSetAssists()) ? 131071 : 524287);
    if (isSetAssists())
      hashCode = hashCode * 8191 + assists.hashCode();

    hashCode = hashCode * 8191 + ((isSetDeaths()) ? 131071 : 524287);
    if (isSetDeaths())
      hashCode = hashCode * 8191 + deaths.hashCode();

    hashCode = hashCode * 8191 + ((isSetRevives()) ? 131071 : 524287);
    if (isSetRevives())
      hashCode = hashCode * 8191 + revives.hashCode();

    hashCode = hashCode * 8191 + ((isSetMultiKills()) ? 131071 : 524287);
    if (isSetMultiKills())
      hashCode = hashCode * 8191 + multiKills.hashCode();

    hashCode = hashCode * 8191 + ((isSetKillStreaks()) ? 131071 : 524287);
    if (isSetKillStreaks())
      hashCode = hashCode * 8191 + killStreaks.hashCode();

    hashCode = hashCode * 8191 + ((isSetItems()) ? 131071 : 524287);
    if (isSetItems())
      hashCode = hashCode * 8191 + items.hashCode();

    hashCode = hashCode * 8191 + ((isSetSummonerSpells()) ? 131071 : 524287);
    if (isSetSummonerSpells())
      hashCode = hashCode * 8191 + summonerSpells.hashCode();

    hashCode = hashCode * 8191 + ((isSetCreeps()) ? 131071 : 524287);
    if (isSetCreeps())
      hashCode = hashCode * 8191 + creeps.hashCode();

    hashCode = hashCode * 8191 + ((isSetKeystone()) ? 131071 : 524287);
    if (isSetKeystone())
      hashCode = hashCode * 8191 + keystone.hashCode();

    hashCode = hashCode * 8191 + ((isSetPosition()) ? 131071 : 524287);
    if (isSetPosition())
      hashCode = hashCode * 8191 + position.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(LolPlayerSummary other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetId(), other.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetUiIndex(), other.isSetUiIndex());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUiIndex()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.uiIndex, other.uiIndex);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetChampion(), other.isSetChampion());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetChampion()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.champion, other.champion);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetKills(), other.isSetKills());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetKills()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.kills, other.kills);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetAssists(), other.isSetAssists());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAssists()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.assists, other.assists);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetDeaths(), other.isSetDeaths());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDeaths()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.deaths, other.deaths);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetRevives(), other.isSetRevives());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRevives()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.revives, other.revives);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetMultiKills(), other.isSetMultiKills());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMultiKills()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.multiKills, other.multiKills);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetKillStreaks(), other.isSetKillStreaks());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetKillStreaks()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.killStreaks, other.killStreaks);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetItems(), other.isSetItems());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetItems()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.items, other.items);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetSummonerSpells(), other.isSetSummonerSpells());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSummonerSpells()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.summonerSpells, other.summonerSpells);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetCreeps(), other.isSetCreeps());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreeps()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.creeps, other.creeps);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetKeystone(), other.isSetKeystone());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetKeystone()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.keystone, other.keystone);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetPosition(), other.isSetPosition());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPosition()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.position, other.position);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("LolPlayerSummary(");
    boolean first = true;

    sb.append("id:");
    sb.append(this.id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("uiIndex:");
    sb.append(this.uiIndex);
    first = false;
    if (!first) sb.append(", ");
    sb.append("champion:");
    if (this.champion == null) {
      sb.append("null");
    } else {
      sb.append(this.champion);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("kills:");
    if (this.kills == null) {
      sb.append("null");
    } else {
      sb.append(this.kills);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("assists:");
    if (this.assists == null) {
      sb.append("null");
    } else {
      sb.append(this.assists);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("deaths:");
    if (this.deaths == null) {
      sb.append("null");
    } else {
      sb.append(this.deaths);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("revives:");
    if (this.revives == null) {
      sb.append("null");
    } else {
      sb.append(this.revives);
    }
    first = false;
    if (isSetMultiKills()) {
      if (!first) sb.append(", ");
      sb.append("multiKills:");
      if (this.multiKills == null) {
        sb.append("null");
      } else {
        sb.append(this.multiKills);
      }
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("killStreaks:");
    if (this.killStreaks == null) {
      sb.append("null");
    } else {
      sb.append(this.killStreaks);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("items:");
    if (this.items == null) {
      sb.append("null");
    } else {
      sb.append(this.items);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("summonerSpells:");
    if (this.summonerSpells == null) {
      sb.append("null");
    } else {
      sb.append(this.summonerSpells);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("creeps:");
    if (this.creeps == null) {
      sb.append("null");
    } else {
      sb.append(this.creeps);
    }
    first = false;
    if (isSetKeystone()) {
      if (!first) sb.append(", ");
      sb.append("keystone:");
      if (this.keystone == null) {
        sb.append("null");
      } else {
        sb.append(this.keystone);
      }
      first = false;
    }
    if (isSetPosition()) {
      if (!first) sb.append(", ");
      sb.append("position:");
      if (this.position == null) {
        sb.append("null");
      } else {
        sb.append(this.position);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (champion != null) {
      champion.validate();
    }
    if (kills != null) {
      kills.validate();
    }
    if (assists != null) {
      assists.validate();
    }
    if (deaths != null) {
      deaths.validate();
    }
    if (revives != null) {
      revives.validate();
    }
    if (items != null) {
      items.validate();
    }
    if (creeps != null) {
      creeps.validate();
    }
    if (keystone != null) {
      keystone.validate();
    }
    if (position != null) {
      position.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class LolPlayerSummaryStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public LolPlayerSummaryStandardScheme getScheme() {
      return new LolPlayerSummaryStandardScheme();
    }
  }

  private static class LolPlayerSummaryStandardScheme extends org.apache.thrift.scheme.StandardScheme<LolPlayerSummary> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, LolPlayerSummary struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.id = iprot.readI32();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // UI_INDEX
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.uiIndex = iprot.readI32();
              struct.setUiIndexIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // CHAMPION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.champion = new LolChampion();
              struct.champion.read(iprot);
              struct.setChampionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // KILLS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.kills = new LolKills();
              struct.kills.read(iprot);
              struct.setKillsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // ASSISTS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.assists = new LolAssists();
              struct.assists.read(iprot);
              struct.setAssistsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // DEATHS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.deaths = new LolDeaths();
              struct.deaths.read(iprot);
              struct.setDeathsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // REVIVES
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.revives = new LolRevives();
              struct.revives.read(iprot);
              struct.setRevivesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // MULTI_KILLS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list408 = iprot.readListBegin();
                struct.multiKills = new java.util.ArrayList<LolMultiKill>(_list408.size);
                @org.apache.thrift.annotation.Nullable LolMultiKill _elem409;
                for (int _i410 = 0; _i410 < _list408.size; ++_i410)
                {
                  _elem409 = new LolMultiKill();
                  _elem409.read(iprot);
                  struct.multiKills.add(_elem409);
                }
                iprot.readListEnd();
              }
              struct.setMultiKillsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // KILL_STREAKS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list411 = iprot.readListBegin();
                struct.killStreaks = new java.util.ArrayList<java.lang.Integer>(_list411.size);
                int _elem412;
                for (int _i413 = 0; _i413 < _list411.size; ++_i413)
                {
                  _elem412 = iprot.readI32();
                  struct.killStreaks.add(_elem412);
                }
                iprot.readListEnd();
              }
              struct.setKillStreaksIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // ITEMS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.items = new LolItems();
              struct.items.read(iprot);
              struct.setItemsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // SUMMONER_SPELLS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list414 = iprot.readListBegin();
                struct.summonerSpells = new java.util.ArrayList<LolSummonerSpell>(_list414.size);
                @org.apache.thrift.annotation.Nullable LolSummonerSpell _elem415;
                for (int _i416 = 0; _i416 < _list414.size; ++_i416)
                {
                  _elem415 = new LolSummonerSpell();
                  _elem415.read(iprot);
                  struct.summonerSpells.add(_elem415);
                }
                iprot.readListEnd();
              }
              struct.setSummonerSpellsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 12: // CREEPS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.creeps = new LolCreeps();
              struct.creeps.read(iprot);
              struct.setCreepsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 13: // KEYSTONE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.keystone = new LolKeystone();
              struct.keystone.read(iprot);
              struct.setKeystoneIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 14: // POSITION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.position = new LolPosition();
              struct.position.read(iprot);
              struct.setPositionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, LolPlayerSummary struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ID_FIELD_DESC);
      oprot.writeI32(struct.id);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(UI_INDEX_FIELD_DESC);
      oprot.writeI32(struct.uiIndex);
      oprot.writeFieldEnd();
      if (struct.champion != null) {
        oprot.writeFieldBegin(CHAMPION_FIELD_DESC);
        struct.champion.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.kills != null) {
        oprot.writeFieldBegin(KILLS_FIELD_DESC);
        struct.kills.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.assists != null) {
        oprot.writeFieldBegin(ASSISTS_FIELD_DESC);
        struct.assists.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.deaths != null) {
        oprot.writeFieldBegin(DEATHS_FIELD_DESC);
        struct.deaths.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.revives != null) {
        oprot.writeFieldBegin(REVIVES_FIELD_DESC);
        struct.revives.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.multiKills != null) {
        if (struct.isSetMultiKills()) {
          oprot.writeFieldBegin(MULTI_KILLS_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.multiKills.size()));
            for (LolMultiKill _iter417 : struct.multiKills)
            {
              _iter417.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.killStreaks != null) {
        oprot.writeFieldBegin(KILL_STREAKS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, struct.killStreaks.size()));
          for (int _iter418 : struct.killStreaks)
          {
            oprot.writeI32(_iter418);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.items != null) {
        oprot.writeFieldBegin(ITEMS_FIELD_DESC);
        struct.items.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.summonerSpells != null) {
        oprot.writeFieldBegin(SUMMONER_SPELLS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.summonerSpells.size()));
          for (LolSummonerSpell _iter419 : struct.summonerSpells)
          {
            _iter419.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.creeps != null) {
        oprot.writeFieldBegin(CREEPS_FIELD_DESC);
        struct.creeps.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.keystone != null) {
        if (struct.isSetKeystone()) {
          oprot.writeFieldBegin(KEYSTONE_FIELD_DESC);
          struct.keystone.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      if (struct.position != null) {
        if (struct.isSetPosition()) {
          oprot.writeFieldBegin(POSITION_FIELD_DESC);
          struct.position.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class LolPlayerSummaryTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public LolPlayerSummaryTupleScheme getScheme() {
      return new LolPlayerSummaryTupleScheme();
    }
  }

  private static class LolPlayerSummaryTupleScheme extends org.apache.thrift.scheme.TupleScheme<LolPlayerSummary> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, LolPlayerSummary struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetId()) {
        optionals.set(0);
      }
      if (struct.isSetUiIndex()) {
        optionals.set(1);
      }
      if (struct.isSetChampion()) {
        optionals.set(2);
      }
      if (struct.isSetKills()) {
        optionals.set(3);
      }
      if (struct.isSetAssists()) {
        optionals.set(4);
      }
      if (struct.isSetDeaths()) {
        optionals.set(5);
      }
      if (struct.isSetRevives()) {
        optionals.set(6);
      }
      if (struct.isSetMultiKills()) {
        optionals.set(7);
      }
      if (struct.isSetKillStreaks()) {
        optionals.set(8);
      }
      if (struct.isSetItems()) {
        optionals.set(9);
      }
      if (struct.isSetSummonerSpells()) {
        optionals.set(10);
      }
      if (struct.isSetCreeps()) {
        optionals.set(11);
      }
      if (struct.isSetKeystone()) {
        optionals.set(12);
      }
      if (struct.isSetPosition()) {
        optionals.set(13);
      }
      oprot.writeBitSet(optionals, 14);
      if (struct.isSetId()) {
        oprot.writeI32(struct.id);
      }
      if (struct.isSetUiIndex()) {
        oprot.writeI32(struct.uiIndex);
      }
      if (struct.isSetChampion()) {
        struct.champion.write(oprot);
      }
      if (struct.isSetKills()) {
        struct.kills.write(oprot);
      }
      if (struct.isSetAssists()) {
        struct.assists.write(oprot);
      }
      if (struct.isSetDeaths()) {
        struct.deaths.write(oprot);
      }
      if (struct.isSetRevives()) {
        struct.revives.write(oprot);
      }
      if (struct.isSetMultiKills()) {
        {
          oprot.writeI32(struct.multiKills.size());
          for (LolMultiKill _iter420 : struct.multiKills)
          {
            _iter420.write(oprot);
          }
        }
      }
      if (struct.isSetKillStreaks()) {
        {
          oprot.writeI32(struct.killStreaks.size());
          for (int _iter421 : struct.killStreaks)
          {
            oprot.writeI32(_iter421);
          }
        }
      }
      if (struct.isSetItems()) {
        struct.items.write(oprot);
      }
      if (struct.isSetSummonerSpells()) {
        {
          oprot.writeI32(struct.summonerSpells.size());
          for (LolSummonerSpell _iter422 : struct.summonerSpells)
          {
            _iter422.write(oprot);
          }
        }
      }
      if (struct.isSetCreeps()) {
        struct.creeps.write(oprot);
      }
      if (struct.isSetKeystone()) {
        struct.keystone.write(oprot);
      }
      if (struct.isSetPosition()) {
        struct.position.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, LolPlayerSummary struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(14);
      if (incoming.get(0)) {
        struct.id = iprot.readI32();
        struct.setIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.uiIndex = iprot.readI32();
        struct.setUiIndexIsSet(true);
      }
      if (incoming.get(2)) {
        struct.champion = new LolChampion();
        struct.champion.read(iprot);
        struct.setChampionIsSet(true);
      }
      if (incoming.get(3)) {
        struct.kills = new LolKills();
        struct.kills.read(iprot);
        struct.setKillsIsSet(true);
      }
      if (incoming.get(4)) {
        struct.assists = new LolAssists();
        struct.assists.read(iprot);
        struct.setAssistsIsSet(true);
      }
      if (incoming.get(5)) {
        struct.deaths = new LolDeaths();
        struct.deaths.read(iprot);
        struct.setDeathsIsSet(true);
      }
      if (incoming.get(6)) {
        struct.revives = new LolRevives();
        struct.revives.read(iprot);
        struct.setRevivesIsSet(true);
      }
      if (incoming.get(7)) {
        {
          org.apache.thrift.protocol.TList _list423 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
          struct.multiKills = new java.util.ArrayList<LolMultiKill>(_list423.size);
          @org.apache.thrift.annotation.Nullable LolMultiKill _elem424;
          for (int _i425 = 0; _i425 < _list423.size; ++_i425)
          {
            _elem424 = new LolMultiKill();
            _elem424.read(iprot);
            struct.multiKills.add(_elem424);
          }
        }
        struct.setMultiKillsIsSet(true);
      }
      if (incoming.get(8)) {
        {
          org.apache.thrift.protocol.TList _list426 = iprot.readListBegin(org.apache.thrift.protocol.TType.I32);
          struct.killStreaks = new java.util.ArrayList<java.lang.Integer>(_list426.size);
          int _elem427;
          for (int _i428 = 0; _i428 < _list426.size; ++_i428)
          {
            _elem427 = iprot.readI32();
            struct.killStreaks.add(_elem427);
          }
        }
        struct.setKillStreaksIsSet(true);
      }
      if (incoming.get(9)) {
        struct.items = new LolItems();
        struct.items.read(iprot);
        struct.setItemsIsSet(true);
      }
      if (incoming.get(10)) {
        {
          org.apache.thrift.protocol.TList _list429 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
          struct.summonerSpells = new java.util.ArrayList<LolSummonerSpell>(_list429.size);
          @org.apache.thrift.annotation.Nullable LolSummonerSpell _elem430;
          for (int _i431 = 0; _i431 < _list429.size; ++_i431)
          {
            _elem430 = new LolSummonerSpell();
            _elem430.read(iprot);
            struct.summonerSpells.add(_elem430);
          }
        }
        struct.setSummonerSpellsIsSet(true);
      }
      if (incoming.get(11)) {
        struct.creeps = new LolCreeps();
        struct.creeps.read(iprot);
        struct.setCreepsIsSet(true);
      }
      if (incoming.get(12)) {
        struct.keystone = new LolKeystone();
        struct.keystone.read(iprot);
        struct.setKeystoneIsSet(true);
      }
      if (incoming.get(13)) {
        struct.position = new LolPosition();
        struct.position.read(iprot);
        struct.setPositionIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

