/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.apollo.backend.data;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class LolPit implements org.apache.thrift.TBase<LolPit, LolPit._Fields>, java.io.Serializable, Cloneable, Comparable<LolPit> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("LolPit");

  private static final org.apache.thrift.protocol.TField NPC_FIELD_DESC = new org.apache.thrift.protocol.TField("npc", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField NPC_STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("npcStatus", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField EMPTY_SINCE_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("emptySinceTime", org.apache.thrift.protocol.TType.STRUCT, (short)3);
  private static final org.apache.thrift.protocol.TField SPAWN_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("spawnTime", org.apache.thrift.protocol.TType.STRUCT, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new LolPitStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new LolPitTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable LolNpc npc; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String npcStatus; // required
  public @org.apache.thrift.annotation.Nullable LolMatchClock emptySinceTime; // optional
  public @org.apache.thrift.annotation.Nullable LolMatchClock spawnTime; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    NPC((short)1, "npc"),
    NPC_STATUS((short)2, "npcStatus"),
    EMPTY_SINCE_TIME((short)3, "emptySinceTime"),
    SPAWN_TIME((short)4, "spawnTime");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // NPC
          return NPC;
        case 2: // NPC_STATUS
          return NPC_STATUS;
        case 3: // EMPTY_SINCE_TIME
          return EMPTY_SINCE_TIME;
        case 4: // SPAWN_TIME
          return SPAWN_TIME;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields optionals[] = {_Fields.NPC,_Fields.EMPTY_SINCE_TIME,_Fields.SPAWN_TIME};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.NPC, new org.apache.thrift.meta_data.FieldMetaData("npc", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, LolNpc.class)));
    tmpMap.put(_Fields.NPC_STATUS, new org.apache.thrift.meta_data.FieldMetaData("npcStatus", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.EMPTY_SINCE_TIME, new org.apache.thrift.meta_data.FieldMetaData("emptySinceTime", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, LolMatchClock.class)));
    tmpMap.put(_Fields.SPAWN_TIME, new org.apache.thrift.meta_data.FieldMetaData("spawnTime", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, LolMatchClock.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(LolPit.class, metaDataMap);
  }

  public LolPit() {
  }

  public LolPit(
    java.lang.String npcStatus)
  {
    this();
    this.npcStatus = npcStatus;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public LolPit(LolPit other) {
    if (other.isSetNpc()) {
      this.npc = new LolNpc(other.npc);
    }
    if (other.isSetNpcStatus()) {
      this.npcStatus = other.npcStatus;
    }
    if (other.isSetEmptySinceTime()) {
      this.emptySinceTime = new LolMatchClock(other.emptySinceTime);
    }
    if (other.isSetSpawnTime()) {
      this.spawnTime = new LolMatchClock(other.spawnTime);
    }
  }

  @Override
  public LolPit deepCopy() {
    return new LolPit(this);
  }

  @Override
  public void clear() {
    this.npc = null;
    this.npcStatus = null;
    this.emptySinceTime = null;
    this.spawnTime = null;
  }

  @org.apache.thrift.annotation.Nullable
  public LolNpc getNpc() {
    return this.npc;
  }

  public LolPit setNpc(@org.apache.thrift.annotation.Nullable LolNpc npc) {
    this.npc = npc;
    return this;
  }

  public void unsetNpc() {
    this.npc = null;
  }

  /** Returns true if field npc is set (has been assigned a value) and false otherwise */
  public boolean isSetNpc() {
    return this.npc != null;
  }

  public void setNpcIsSet(boolean value) {
    if (!value) {
      this.npc = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getNpcStatus() {
    return this.npcStatus;
  }

  public LolPit setNpcStatus(@org.apache.thrift.annotation.Nullable java.lang.String npcStatus) {
    this.npcStatus = npcStatus;
    return this;
  }

  public void unsetNpcStatus() {
    this.npcStatus = null;
  }

  /** Returns true if field npcStatus is set (has been assigned a value) and false otherwise */
  public boolean isSetNpcStatus() {
    return this.npcStatus != null;
  }

  public void setNpcStatusIsSet(boolean value) {
    if (!value) {
      this.npcStatus = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public LolMatchClock getEmptySinceTime() {
    return this.emptySinceTime;
  }

  public LolPit setEmptySinceTime(@org.apache.thrift.annotation.Nullable LolMatchClock emptySinceTime) {
    this.emptySinceTime = emptySinceTime;
    return this;
  }

  public void unsetEmptySinceTime() {
    this.emptySinceTime = null;
  }

  /** Returns true if field emptySinceTime is set (has been assigned a value) and false otherwise */
  public boolean isSetEmptySinceTime() {
    return this.emptySinceTime != null;
  }

  public void setEmptySinceTimeIsSet(boolean value) {
    if (!value) {
      this.emptySinceTime = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public LolMatchClock getSpawnTime() {
    return this.spawnTime;
  }

  public LolPit setSpawnTime(@org.apache.thrift.annotation.Nullable LolMatchClock spawnTime) {
    this.spawnTime = spawnTime;
    return this;
  }

  public void unsetSpawnTime() {
    this.spawnTime = null;
  }

  /** Returns true if field spawnTime is set (has been assigned a value) and false otherwise */
  public boolean isSetSpawnTime() {
    return this.spawnTime != null;
  }

  public void setSpawnTimeIsSet(boolean value) {
    if (!value) {
      this.spawnTime = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case NPC:
      if (value == null) {
        unsetNpc();
      } else {
        setNpc((LolNpc)value);
      }
      break;

    case NPC_STATUS:
      if (value == null) {
        unsetNpcStatus();
      } else {
        setNpcStatus((java.lang.String)value);
      }
      break;

    case EMPTY_SINCE_TIME:
      if (value == null) {
        unsetEmptySinceTime();
      } else {
        setEmptySinceTime((LolMatchClock)value);
      }
      break;

    case SPAWN_TIME:
      if (value == null) {
        unsetSpawnTime();
      } else {
        setSpawnTime((LolMatchClock)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case NPC:
      return getNpc();

    case NPC_STATUS:
      return getNpcStatus();

    case EMPTY_SINCE_TIME:
      return getEmptySinceTime();

    case SPAWN_TIME:
      return getSpawnTime();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case NPC:
      return isSetNpc();
    case NPC_STATUS:
      return isSetNpcStatus();
    case EMPTY_SINCE_TIME:
      return isSetEmptySinceTime();
    case SPAWN_TIME:
      return isSetSpawnTime();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof LolPit)
      return this.equals((LolPit)that);
    return false;
  }

  public boolean equals(LolPit that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_npc = true && this.isSetNpc();
    boolean that_present_npc = true && that.isSetNpc();
    if (this_present_npc || that_present_npc) {
      if (!(this_present_npc && that_present_npc))
        return false;
      if (!this.npc.equals(that.npc))
        return false;
    }

    boolean this_present_npcStatus = true && this.isSetNpcStatus();
    boolean that_present_npcStatus = true && that.isSetNpcStatus();
    if (this_present_npcStatus || that_present_npcStatus) {
      if (!(this_present_npcStatus && that_present_npcStatus))
        return false;
      if (!this.npcStatus.equals(that.npcStatus))
        return false;
    }

    boolean this_present_emptySinceTime = true && this.isSetEmptySinceTime();
    boolean that_present_emptySinceTime = true && that.isSetEmptySinceTime();
    if (this_present_emptySinceTime || that_present_emptySinceTime) {
      if (!(this_present_emptySinceTime && that_present_emptySinceTime))
        return false;
      if (!this.emptySinceTime.equals(that.emptySinceTime))
        return false;
    }

    boolean this_present_spawnTime = true && this.isSetSpawnTime();
    boolean that_present_spawnTime = true && that.isSetSpawnTime();
    if (this_present_spawnTime || that_present_spawnTime) {
      if (!(this_present_spawnTime && that_present_spawnTime))
        return false;
      if (!this.spawnTime.equals(that.spawnTime))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetNpc()) ? 131071 : 524287);
    if (isSetNpc())
      hashCode = hashCode * 8191 + npc.hashCode();

    hashCode = hashCode * 8191 + ((isSetNpcStatus()) ? 131071 : 524287);
    if (isSetNpcStatus())
      hashCode = hashCode * 8191 + npcStatus.hashCode();

    hashCode = hashCode * 8191 + ((isSetEmptySinceTime()) ? 131071 : 524287);
    if (isSetEmptySinceTime())
      hashCode = hashCode * 8191 + emptySinceTime.hashCode();

    hashCode = hashCode * 8191 + ((isSetSpawnTime()) ? 131071 : 524287);
    if (isSetSpawnTime())
      hashCode = hashCode * 8191 + spawnTime.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(LolPit other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetNpc(), other.isSetNpc());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNpc()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.npc, other.npc);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetNpcStatus(), other.isSetNpcStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNpcStatus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.npcStatus, other.npcStatus);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetEmptySinceTime(), other.isSetEmptySinceTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEmptySinceTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.emptySinceTime, other.emptySinceTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetSpawnTime(), other.isSetSpawnTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSpawnTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.spawnTime, other.spawnTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("LolPit(");
    boolean first = true;

    if (isSetNpc()) {
      sb.append("npc:");
      if (this.npc == null) {
        sb.append("null");
      } else {
        sb.append(this.npc);
      }
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("npcStatus:");
    if (this.npcStatus == null) {
      sb.append("null");
    } else {
      sb.append(this.npcStatus);
    }
    first = false;
    if (isSetEmptySinceTime()) {
      if (!first) sb.append(", ");
      sb.append("emptySinceTime:");
      if (this.emptySinceTime == null) {
        sb.append("null");
      } else {
        sb.append(this.emptySinceTime);
      }
      first = false;
    }
    if (isSetSpawnTime()) {
      if (!first) sb.append(", ");
      sb.append("spawnTime:");
      if (this.spawnTime == null) {
        sb.append("null");
      } else {
        sb.append(this.spawnTime);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (npc != null) {
      npc.validate();
    }
    if (emptySinceTime != null) {
      emptySinceTime.validate();
    }
    if (spawnTime != null) {
      spawnTime.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class LolPitStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public LolPitStandardScheme getScheme() {
      return new LolPitStandardScheme();
    }
  }

  private static class LolPitStandardScheme extends org.apache.thrift.scheme.StandardScheme<LolPit> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, LolPit struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // NPC
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.npc = new LolNpc();
              struct.npc.read(iprot);
              struct.setNpcIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // NPC_STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.npcStatus = iprot.readString();
              struct.setNpcStatusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // EMPTY_SINCE_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.emptySinceTime = new LolMatchClock();
              struct.emptySinceTime.read(iprot);
              struct.setEmptySinceTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // SPAWN_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.spawnTime = new LolMatchClock();
              struct.spawnTime.read(iprot);
              struct.setSpawnTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, LolPit struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.npc != null) {
        if (struct.isSetNpc()) {
          oprot.writeFieldBegin(NPC_FIELD_DESC);
          struct.npc.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      if (struct.npcStatus != null) {
        oprot.writeFieldBegin(NPC_STATUS_FIELD_DESC);
        oprot.writeString(struct.npcStatus);
        oprot.writeFieldEnd();
      }
      if (struct.emptySinceTime != null) {
        if (struct.isSetEmptySinceTime()) {
          oprot.writeFieldBegin(EMPTY_SINCE_TIME_FIELD_DESC);
          struct.emptySinceTime.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      if (struct.spawnTime != null) {
        if (struct.isSetSpawnTime()) {
          oprot.writeFieldBegin(SPAWN_TIME_FIELD_DESC);
          struct.spawnTime.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class LolPitTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public LolPitTupleScheme getScheme() {
      return new LolPitTupleScheme();
    }
  }

  private static class LolPitTupleScheme extends org.apache.thrift.scheme.TupleScheme<LolPit> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, LolPit struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetNpc()) {
        optionals.set(0);
      }
      if (struct.isSetNpcStatus()) {
        optionals.set(1);
      }
      if (struct.isSetEmptySinceTime()) {
        optionals.set(2);
      }
      if (struct.isSetSpawnTime()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetNpc()) {
        struct.npc.write(oprot);
      }
      if (struct.isSetNpcStatus()) {
        oprot.writeString(struct.npcStatus);
      }
      if (struct.isSetEmptySinceTime()) {
        struct.emptySinceTime.write(oprot);
      }
      if (struct.isSetSpawnTime()) {
        struct.spawnTime.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, LolPit struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.npc = new LolNpc();
        struct.npc.read(iprot);
        struct.setNpcIsSet(true);
      }
      if (incoming.get(1)) {
        struct.npcStatus = iprot.readString();
        struct.setNpcStatusIsSet(true);
      }
      if (incoming.get(2)) {
        struct.emptySinceTime = new LolMatchClock();
        struct.emptySinceTime.read(iprot);
        struct.setEmptySinceTimeIsSet(true);
      }
      if (incoming.get(3)) {
        struct.spawnTime = new LolMatchClock();
        struct.spawnTime.read(iprot);
        struct.setSpawnTimeIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

