/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.apollo.backend.data;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class Match implements org.apache.thrift.TBase<Match, Match._Fields>, java.io.Serializable, Cloneable, Comparable<Match> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Match");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField MAP_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("mapId", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField LIFECYCLE_FIELD_DESC = new org.apache.thrift.protocol.TField("lifecycle", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField ORDER_FIELD_DESC = new org.apache.thrift.protocol.TField("order", org.apache.thrift.protocol.TType.I32, (short)4);
  private static final org.apache.thrift.protocol.TField SERIES_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("seriesId", org.apache.thrift.protocol.TType.I32, (short)5);
  private static final org.apache.thrift.protocol.TField DELETED_AT_FIELD_DESC = new org.apache.thrift.protocol.TField("deletedAt", org.apache.thrift.protocol.TType.I64, (short)6);
  private static final org.apache.thrift.protocol.TField GAME_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("gameId", org.apache.thrift.protocol.TType.I32, (short)7);
  private static final org.apache.thrift.protocol.TField PARTICIPANTS_FIELD_DESC = new org.apache.thrift.protocol.TField("participants", org.apache.thrift.protocol.TType.LIST, (short)8);
  private static final org.apache.thrift.protocol.TField COVERAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("coverage", org.apache.thrift.protocol.TType.STRUCT, (short)9);
  private static final org.apache.thrift.protocol.TField RESOURCE_VERSION_FIELD_DESC = new org.apache.thrift.protocol.TField("resourceVersion", org.apache.thrift.protocol.TType.I64, (short)10);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new MatchStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new MatchTupleSchemeFactory();

  public int id; // required
  public int mapId; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String lifecycle; // required
  public int order; // required
  public int seriesId; // required
  public long deletedAt; // optional
  public int gameId; // required
  public @org.apache.thrift.annotation.Nullable java.util.List<Participant> participants; // required
  public @org.apache.thrift.annotation.Nullable Coverage coverage; // required
  public long resourceVersion; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    MAP_ID((short)2, "mapId"),
    LIFECYCLE((short)3, "lifecycle"),
    ORDER((short)4, "order"),
    SERIES_ID((short)5, "seriesId"),
    DELETED_AT((short)6, "deletedAt"),
    GAME_ID((short)7, "gameId"),
    PARTICIPANTS((short)8, "participants"),
    COVERAGE((short)9, "coverage"),
    RESOURCE_VERSION((short)10, "resourceVersion");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // MAP_ID
          return MAP_ID;
        case 3: // LIFECYCLE
          return LIFECYCLE;
        case 4: // ORDER
          return ORDER;
        case 5: // SERIES_ID
          return SERIES_ID;
        case 6: // DELETED_AT
          return DELETED_AT;
        case 7: // GAME_ID
          return GAME_ID;
        case 8: // PARTICIPANTS
          return PARTICIPANTS;
        case 9: // COVERAGE
          return COVERAGE;
        case 10: // RESOURCE_VERSION
          return RESOURCE_VERSION;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ID_ISSET_ID = 0;
  private static final int __MAPID_ISSET_ID = 1;
  private static final int __ORDER_ISSET_ID = 2;
  private static final int __SERIESID_ISSET_ID = 3;
  private static final int __DELETEDAT_ISSET_ID = 4;
  private static final int __GAMEID_ISSET_ID = 5;
  private static final int __RESOURCEVERSION_ISSET_ID = 6;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.DELETED_AT};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.MAP_ID, new org.apache.thrift.meta_data.FieldMetaData("mapId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.LIFECYCLE, new org.apache.thrift.meta_data.FieldMetaData("lifecycle", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ORDER, new org.apache.thrift.meta_data.FieldMetaData("order", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.SERIES_ID, new org.apache.thrift.meta_data.FieldMetaData("seriesId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.DELETED_AT, new org.apache.thrift.meta_data.FieldMetaData("deletedAt", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.GAME_ID, new org.apache.thrift.meta_data.FieldMetaData("gameId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.PARTICIPANTS, new org.apache.thrift.meta_data.FieldMetaData("participants", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Participant.class))));
    tmpMap.put(_Fields.COVERAGE, new org.apache.thrift.meta_data.FieldMetaData("coverage", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Coverage.class)));
    tmpMap.put(_Fields.RESOURCE_VERSION, new org.apache.thrift.meta_data.FieldMetaData("resourceVersion", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Match.class, metaDataMap);
  }

  public Match() {
  }

  public Match(
    int id,
    int mapId,
    java.lang.String lifecycle,
    int order,
    int seriesId,
    int gameId,
    java.util.List<Participant> participants,
    Coverage coverage,
    long resourceVersion)
  {
    this();
    this.id = id;
    setIdIsSet(true);
    this.mapId = mapId;
    setMapIdIsSet(true);
    this.lifecycle = lifecycle;
    this.order = order;
    setOrderIsSet(true);
    this.seriesId = seriesId;
    setSeriesIdIsSet(true);
    this.gameId = gameId;
    setGameIdIsSet(true);
    this.participants = participants;
    this.coverage = coverage;
    this.resourceVersion = resourceVersion;
    setResourceVersionIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Match(Match other) {
    __isset_bitfield = other.__isset_bitfield;
    this.id = other.id;
    this.mapId = other.mapId;
    if (other.isSetLifecycle()) {
      this.lifecycle = other.lifecycle;
    }
    this.order = other.order;
    this.seriesId = other.seriesId;
    this.deletedAt = other.deletedAt;
    this.gameId = other.gameId;
    if (other.isSetParticipants()) {
      java.util.List<Participant> __this__participants = new java.util.ArrayList<Participant>(other.participants.size());
      for (Participant other_element : other.participants) {
        __this__participants.add(new Participant(other_element));
      }
      this.participants = __this__participants;
    }
    if (other.isSetCoverage()) {
      this.coverage = new Coverage(other.coverage);
    }
    this.resourceVersion = other.resourceVersion;
  }

  @Override
  public Match deepCopy() {
    return new Match(this);
  }

  @Override
  public void clear() {
    setIdIsSet(false);
    this.id = 0;
    setMapIdIsSet(false);
    this.mapId = 0;
    this.lifecycle = null;
    setOrderIsSet(false);
    this.order = 0;
    setSeriesIdIsSet(false);
    this.seriesId = 0;
    setDeletedAtIsSet(false);
    this.deletedAt = 0;
    setGameIdIsSet(false);
    this.gameId = 0;
    this.participants = null;
    this.coverage = null;
    setResourceVersionIsSet(false);
    this.resourceVersion = 0;
  }

  public int getId() {
    return this.id;
  }

  public Match setId(int id) {
    this.id = id;
    setIdIsSet(true);
    return this;
  }

  public void unsetId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ID_ISSET_ID);
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ID_ISSET_ID);
  }

  public void setIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ID_ISSET_ID, value);
  }

  public int getMapId() {
    return this.mapId;
  }

  public Match setMapId(int mapId) {
    this.mapId = mapId;
    setMapIdIsSet(true);
    return this;
  }

  public void unsetMapId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __MAPID_ISSET_ID);
  }

  /** Returns true if field mapId is set (has been assigned a value) and false otherwise */
  public boolean isSetMapId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __MAPID_ISSET_ID);
  }

  public void setMapIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __MAPID_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getLifecycle() {
    return this.lifecycle;
  }

  public Match setLifecycle(@org.apache.thrift.annotation.Nullable java.lang.String lifecycle) {
    this.lifecycle = lifecycle;
    return this;
  }

  public void unsetLifecycle() {
    this.lifecycle = null;
  }

  /** Returns true if field lifecycle is set (has been assigned a value) and false otherwise */
  public boolean isSetLifecycle() {
    return this.lifecycle != null;
  }

  public void setLifecycleIsSet(boolean value) {
    if (!value) {
      this.lifecycle = null;
    }
  }

  public int getOrder() {
    return this.order;
  }

  public Match setOrder(int order) {
    this.order = order;
    setOrderIsSet(true);
    return this;
  }

  public void unsetOrder() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ORDER_ISSET_ID);
  }

  /** Returns true if field order is set (has been assigned a value) and false otherwise */
  public boolean isSetOrder() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ORDER_ISSET_ID);
  }

  public void setOrderIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ORDER_ISSET_ID, value);
  }

  public int getSeriesId() {
    return this.seriesId;
  }

  public Match setSeriesId(int seriesId) {
    this.seriesId = seriesId;
    setSeriesIdIsSet(true);
    return this;
  }

  public void unsetSeriesId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SERIESID_ISSET_ID);
  }

  /** Returns true if field seriesId is set (has been assigned a value) and false otherwise */
  public boolean isSetSeriesId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SERIESID_ISSET_ID);
  }

  public void setSeriesIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SERIESID_ISSET_ID, value);
  }

  public long getDeletedAt() {
    return this.deletedAt;
  }

  public Match setDeletedAt(long deletedAt) {
    this.deletedAt = deletedAt;
    setDeletedAtIsSet(true);
    return this;
  }

  public void unsetDeletedAt() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __DELETEDAT_ISSET_ID);
  }

  /** Returns true if field deletedAt is set (has been assigned a value) and false otherwise */
  public boolean isSetDeletedAt() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __DELETEDAT_ISSET_ID);
  }

  public void setDeletedAtIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __DELETEDAT_ISSET_ID, value);
  }

  public int getGameId() {
    return this.gameId;
  }

  public Match setGameId(int gameId) {
    this.gameId = gameId;
    setGameIdIsSet(true);
    return this;
  }

  public void unsetGameId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __GAMEID_ISSET_ID);
  }

  /** Returns true if field gameId is set (has been assigned a value) and false otherwise */
  public boolean isSetGameId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __GAMEID_ISSET_ID);
  }

  public void setGameIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __GAMEID_ISSET_ID, value);
  }

  public int getParticipantsSize() {
    return (this.participants == null) ? 0 : this.participants.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<Participant> getParticipantsIterator() {
    return (this.participants == null) ? null : this.participants.iterator();
  }

  public void addToParticipants(Participant elem) {
    if (this.participants == null) {
      this.participants = new java.util.ArrayList<Participant>();
    }
    this.participants.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<Participant> getParticipants() {
    return this.participants;
  }

  public Match setParticipants(@org.apache.thrift.annotation.Nullable java.util.List<Participant> participants) {
    this.participants = participants;
    return this;
  }

  public void unsetParticipants() {
    this.participants = null;
  }

  /** Returns true if field participants is set (has been assigned a value) and false otherwise */
  public boolean isSetParticipants() {
    return this.participants != null;
  }

  public void setParticipantsIsSet(boolean value) {
    if (!value) {
      this.participants = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public Coverage getCoverage() {
    return this.coverage;
  }

  public Match setCoverage(@org.apache.thrift.annotation.Nullable Coverage coverage) {
    this.coverage = coverage;
    return this;
  }

  public void unsetCoverage() {
    this.coverage = null;
  }

  /** Returns true if field coverage is set (has been assigned a value) and false otherwise */
  public boolean isSetCoverage() {
    return this.coverage != null;
  }

  public void setCoverageIsSet(boolean value) {
    if (!value) {
      this.coverage = null;
    }
  }

  public long getResourceVersion() {
    return this.resourceVersion;
  }

  public Match setResourceVersion(long resourceVersion) {
    this.resourceVersion = resourceVersion;
    setResourceVersionIsSet(true);
    return this;
  }

  public void unsetResourceVersion() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __RESOURCEVERSION_ISSET_ID);
  }

  /** Returns true if field resourceVersion is set (has been assigned a value) and false otherwise */
  public boolean isSetResourceVersion() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __RESOURCEVERSION_ISSET_ID);
  }

  public void setResourceVersionIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __RESOURCEVERSION_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((java.lang.Integer)value);
      }
      break;

    case MAP_ID:
      if (value == null) {
        unsetMapId();
      } else {
        setMapId((java.lang.Integer)value);
      }
      break;

    case LIFECYCLE:
      if (value == null) {
        unsetLifecycle();
      } else {
        setLifecycle((java.lang.String)value);
      }
      break;

    case ORDER:
      if (value == null) {
        unsetOrder();
      } else {
        setOrder((java.lang.Integer)value);
      }
      break;

    case SERIES_ID:
      if (value == null) {
        unsetSeriesId();
      } else {
        setSeriesId((java.lang.Integer)value);
      }
      break;

    case DELETED_AT:
      if (value == null) {
        unsetDeletedAt();
      } else {
        setDeletedAt((java.lang.Long)value);
      }
      break;

    case GAME_ID:
      if (value == null) {
        unsetGameId();
      } else {
        setGameId((java.lang.Integer)value);
      }
      break;

    case PARTICIPANTS:
      if (value == null) {
        unsetParticipants();
      } else {
        setParticipants((java.util.List<Participant>)value);
      }
      break;

    case COVERAGE:
      if (value == null) {
        unsetCoverage();
      } else {
        setCoverage((Coverage)value);
      }
      break;

    case RESOURCE_VERSION:
      if (value == null) {
        unsetResourceVersion();
      } else {
        setResourceVersion((java.lang.Long)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return getId();

    case MAP_ID:
      return getMapId();

    case LIFECYCLE:
      return getLifecycle();

    case ORDER:
      return getOrder();

    case SERIES_ID:
      return getSeriesId();

    case DELETED_AT:
      return getDeletedAt();

    case GAME_ID:
      return getGameId();

    case PARTICIPANTS:
      return getParticipants();

    case COVERAGE:
      return getCoverage();

    case RESOURCE_VERSION:
      return getResourceVersion();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case MAP_ID:
      return isSetMapId();
    case LIFECYCLE:
      return isSetLifecycle();
    case ORDER:
      return isSetOrder();
    case SERIES_ID:
      return isSetSeriesId();
    case DELETED_AT:
      return isSetDeletedAt();
    case GAME_ID:
      return isSetGameId();
    case PARTICIPANTS:
      return isSetParticipants();
    case COVERAGE:
      return isSetCoverage();
    case RESOURCE_VERSION:
      return isSetResourceVersion();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof Match)
      return this.equals((Match)that);
    return false;
  }

  public boolean equals(Match that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_id = true;
    boolean that_present_id = true;
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (this.id != that.id)
        return false;
    }

    boolean this_present_mapId = true;
    boolean that_present_mapId = true;
    if (this_present_mapId || that_present_mapId) {
      if (!(this_present_mapId && that_present_mapId))
        return false;
      if (this.mapId != that.mapId)
        return false;
    }

    boolean this_present_lifecycle = true && this.isSetLifecycle();
    boolean that_present_lifecycle = true && that.isSetLifecycle();
    if (this_present_lifecycle || that_present_lifecycle) {
      if (!(this_present_lifecycle && that_present_lifecycle))
        return false;
      if (!this.lifecycle.equals(that.lifecycle))
        return false;
    }

    boolean this_present_order = true;
    boolean that_present_order = true;
    if (this_present_order || that_present_order) {
      if (!(this_present_order && that_present_order))
        return false;
      if (this.order != that.order)
        return false;
    }

    boolean this_present_seriesId = true;
    boolean that_present_seriesId = true;
    if (this_present_seriesId || that_present_seriesId) {
      if (!(this_present_seriesId && that_present_seriesId))
        return false;
      if (this.seriesId != that.seriesId)
        return false;
    }

    boolean this_present_deletedAt = true && this.isSetDeletedAt();
    boolean that_present_deletedAt = true && that.isSetDeletedAt();
    if (this_present_deletedAt || that_present_deletedAt) {
      if (!(this_present_deletedAt && that_present_deletedAt))
        return false;
      if (this.deletedAt != that.deletedAt)
        return false;
    }

    boolean this_present_gameId = true;
    boolean that_present_gameId = true;
    if (this_present_gameId || that_present_gameId) {
      if (!(this_present_gameId && that_present_gameId))
        return false;
      if (this.gameId != that.gameId)
        return false;
    }

    boolean this_present_participants = true && this.isSetParticipants();
    boolean that_present_participants = true && that.isSetParticipants();
    if (this_present_participants || that_present_participants) {
      if (!(this_present_participants && that_present_participants))
        return false;
      if (!this.participants.equals(that.participants))
        return false;
    }

    boolean this_present_coverage = true && this.isSetCoverage();
    boolean that_present_coverage = true && that.isSetCoverage();
    if (this_present_coverage || that_present_coverage) {
      if (!(this_present_coverage && that_present_coverage))
        return false;
      if (!this.coverage.equals(that.coverage))
        return false;
    }

    boolean this_present_resourceVersion = true;
    boolean that_present_resourceVersion = true;
    if (this_present_resourceVersion || that_present_resourceVersion) {
      if (!(this_present_resourceVersion && that_present_resourceVersion))
        return false;
      if (this.resourceVersion != that.resourceVersion)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + id;

    hashCode = hashCode * 8191 + mapId;

    hashCode = hashCode * 8191 + ((isSetLifecycle()) ? 131071 : 524287);
    if (isSetLifecycle())
      hashCode = hashCode * 8191 + lifecycle.hashCode();

    hashCode = hashCode * 8191 + order;

    hashCode = hashCode * 8191 + seriesId;

    hashCode = hashCode * 8191 + ((isSetDeletedAt()) ? 131071 : 524287);
    if (isSetDeletedAt())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(deletedAt);

    hashCode = hashCode * 8191 + gameId;

    hashCode = hashCode * 8191 + ((isSetParticipants()) ? 131071 : 524287);
    if (isSetParticipants())
      hashCode = hashCode * 8191 + participants.hashCode();

    hashCode = hashCode * 8191 + ((isSetCoverage()) ? 131071 : 524287);
    if (isSetCoverage())
      hashCode = hashCode * 8191 + coverage.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(resourceVersion);

    return hashCode;
  }

  @Override
  public int compareTo(Match other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetId(), other.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetMapId(), other.isSetMapId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMapId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mapId, other.mapId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetLifecycle(), other.isSetLifecycle());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLifecycle()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lifecycle, other.lifecycle);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetOrder(), other.isSetOrder());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOrder()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.order, other.order);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetSeriesId(), other.isSetSeriesId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSeriesId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.seriesId, other.seriesId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetDeletedAt(), other.isSetDeletedAt());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDeletedAt()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.deletedAt, other.deletedAt);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetGameId(), other.isSetGameId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGameId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.gameId, other.gameId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetParticipants(), other.isSetParticipants());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetParticipants()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.participants, other.participants);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetCoverage(), other.isSetCoverage());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCoverage()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.coverage, other.coverage);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetResourceVersion(), other.isSetResourceVersion());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResourceVersion()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.resourceVersion, other.resourceVersion);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Match(");
    boolean first = true;

    sb.append("id:");
    sb.append(this.id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("mapId:");
    sb.append(this.mapId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("lifecycle:");
    if (this.lifecycle == null) {
      sb.append("null");
    } else {
      sb.append(this.lifecycle);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("order:");
    sb.append(this.order);
    first = false;
    if (!first) sb.append(", ");
    sb.append("seriesId:");
    sb.append(this.seriesId);
    first = false;
    if (isSetDeletedAt()) {
      if (!first) sb.append(", ");
      sb.append("deletedAt:");
      sb.append(this.deletedAt);
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("gameId:");
    sb.append(this.gameId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("participants:");
    if (this.participants == null) {
      sb.append("null");
    } else {
      sb.append(this.participants);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("coverage:");
    if (this.coverage == null) {
      sb.append("null");
    } else {
      sb.append(this.coverage);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("resourceVersion:");
    sb.append(this.resourceVersion);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (coverage != null) {
      coverage.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MatchStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public MatchStandardScheme getScheme() {
      return new MatchStandardScheme();
    }
  }

  private static class MatchStandardScheme extends org.apache.thrift.scheme.StandardScheme<Match> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, Match struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.id = iprot.readI32();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // MAP_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.mapId = iprot.readI32();
              struct.setMapIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // LIFECYCLE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.lifecycle = iprot.readString();
              struct.setLifecycleIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // ORDER
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.order = iprot.readI32();
              struct.setOrderIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // SERIES_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.seriesId = iprot.readI32();
              struct.setSeriesIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // DELETED_AT
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.deletedAt = iprot.readI64();
              struct.setDeletedAtIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // GAME_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.gameId = iprot.readI32();
              struct.setGameIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // PARTICIPANTS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list312 = iprot.readListBegin();
                struct.participants = new java.util.ArrayList<Participant>(_list312.size);
                @org.apache.thrift.annotation.Nullable Participant _elem313;
                for (int _i314 = 0; _i314 < _list312.size; ++_i314)
                {
                  _elem313 = new Participant();
                  _elem313.read(iprot);
                  struct.participants.add(_elem313);
                }
                iprot.readListEnd();
              }
              struct.setParticipantsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // COVERAGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.coverage = new Coverage();
              struct.coverage.read(iprot);
              struct.setCoverageIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // RESOURCE_VERSION
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.resourceVersion = iprot.readI64();
              struct.setResourceVersionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, Match struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ID_FIELD_DESC);
      oprot.writeI32(struct.id);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(MAP_ID_FIELD_DESC);
      oprot.writeI32(struct.mapId);
      oprot.writeFieldEnd();
      if (struct.lifecycle != null) {
        oprot.writeFieldBegin(LIFECYCLE_FIELD_DESC);
        oprot.writeString(struct.lifecycle);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(ORDER_FIELD_DESC);
      oprot.writeI32(struct.order);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(SERIES_ID_FIELD_DESC);
      oprot.writeI32(struct.seriesId);
      oprot.writeFieldEnd();
      if (struct.isSetDeletedAt()) {
        oprot.writeFieldBegin(DELETED_AT_FIELD_DESC);
        oprot.writeI64(struct.deletedAt);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(GAME_ID_FIELD_DESC);
      oprot.writeI32(struct.gameId);
      oprot.writeFieldEnd();
      if (struct.participants != null) {
        oprot.writeFieldBegin(PARTICIPANTS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.participants.size()));
          for (Participant _iter315 : struct.participants)
          {
            _iter315.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.coverage != null) {
        oprot.writeFieldBegin(COVERAGE_FIELD_DESC);
        struct.coverage.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(RESOURCE_VERSION_FIELD_DESC);
      oprot.writeI64(struct.resourceVersion);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MatchTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public MatchTupleScheme getScheme() {
      return new MatchTupleScheme();
    }
  }

  private static class MatchTupleScheme extends org.apache.thrift.scheme.TupleScheme<Match> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Match struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetId()) {
        optionals.set(0);
      }
      if (struct.isSetMapId()) {
        optionals.set(1);
      }
      if (struct.isSetLifecycle()) {
        optionals.set(2);
      }
      if (struct.isSetOrder()) {
        optionals.set(3);
      }
      if (struct.isSetSeriesId()) {
        optionals.set(4);
      }
      if (struct.isSetDeletedAt()) {
        optionals.set(5);
      }
      if (struct.isSetGameId()) {
        optionals.set(6);
      }
      if (struct.isSetParticipants()) {
        optionals.set(7);
      }
      if (struct.isSetCoverage()) {
        optionals.set(8);
      }
      if (struct.isSetResourceVersion()) {
        optionals.set(9);
      }
      oprot.writeBitSet(optionals, 10);
      if (struct.isSetId()) {
        oprot.writeI32(struct.id);
      }
      if (struct.isSetMapId()) {
        oprot.writeI32(struct.mapId);
      }
      if (struct.isSetLifecycle()) {
        oprot.writeString(struct.lifecycle);
      }
      if (struct.isSetOrder()) {
        oprot.writeI32(struct.order);
      }
      if (struct.isSetSeriesId()) {
        oprot.writeI32(struct.seriesId);
      }
      if (struct.isSetDeletedAt()) {
        oprot.writeI64(struct.deletedAt);
      }
      if (struct.isSetGameId()) {
        oprot.writeI32(struct.gameId);
      }
      if (struct.isSetParticipants()) {
        {
          oprot.writeI32(struct.participants.size());
          for (Participant _iter316 : struct.participants)
          {
            _iter316.write(oprot);
          }
        }
      }
      if (struct.isSetCoverage()) {
        struct.coverage.write(oprot);
      }
      if (struct.isSetResourceVersion()) {
        oprot.writeI64(struct.resourceVersion);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Match struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(10);
      if (incoming.get(0)) {
        struct.id = iprot.readI32();
        struct.setIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.mapId = iprot.readI32();
        struct.setMapIdIsSet(true);
      }
      if (incoming.get(2)) {
        struct.lifecycle = iprot.readString();
        struct.setLifecycleIsSet(true);
      }
      if (incoming.get(3)) {
        struct.order = iprot.readI32();
        struct.setOrderIsSet(true);
      }
      if (incoming.get(4)) {
        struct.seriesId = iprot.readI32();
        struct.setSeriesIdIsSet(true);
      }
      if (incoming.get(5)) {
        struct.deletedAt = iprot.readI64();
        struct.setDeletedAtIsSet(true);
      }
      if (incoming.get(6)) {
        struct.gameId = iprot.readI32();
        struct.setGameIdIsSet(true);
      }
      if (incoming.get(7)) {
        {
          org.apache.thrift.protocol.TList _list317 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
          struct.participants = new java.util.ArrayList<Participant>(_list317.size);
          @org.apache.thrift.annotation.Nullable Participant _elem318;
          for (int _i319 = 0; _i319 < _list317.size; ++_i319)
          {
            _elem318 = new Participant();
            _elem318.read(iprot);
            struct.participants.add(_elem318);
          }
        }
        struct.setParticipantsIsSet(true);
      }
      if (incoming.get(8)) {
        struct.coverage = new Coverage();
        struct.coverage.read(iprot);
        struct.setCoverageIsSet(true);
      }
      if (incoming.get(9)) {
        struct.resourceVersion = iprot.readI64();
        struct.setResourceVersionIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

