/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.apollo.backend.data;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class PointsRule implements org.apache.thrift.TBase<PointsRule, PointsRule._Fields>, java.io.Serializable, Cloneable, Comparable<PointsRule> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PointsRule");

  private static final org.apache.thrift.protocol.TField WIN_FIELD_DESC = new org.apache.thrift.protocol.TField("win", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField DRAW_FIELD_DESC = new org.apache.thrift.protocol.TField("draw", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField LOSS_FIELD_DESC = new org.apache.thrift.protocol.TField("loss", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField SCOPE_FIELD_DESC = new org.apache.thrift.protocol.TField("scope", org.apache.thrift.protocol.TType.STRING, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new PointsRuleStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new PointsRuleTupleSchemeFactory();

  public int win; // required
  public int draw; // required
  public int loss; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String scope; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    WIN((short)1, "win"),
    DRAW((short)2, "draw"),
    LOSS((short)3, "loss"),
    SCOPE((short)4, "scope");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // WIN
          return WIN;
        case 2: // DRAW
          return DRAW;
        case 3: // LOSS
          return LOSS;
        case 4: // SCOPE
          return SCOPE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __WIN_ISSET_ID = 0;
  private static final int __DRAW_ISSET_ID = 1;
  private static final int __LOSS_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.WIN, new org.apache.thrift.meta_data.FieldMetaData("win", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.DRAW, new org.apache.thrift.meta_data.FieldMetaData("draw", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.LOSS, new org.apache.thrift.meta_data.FieldMetaData("loss", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.SCOPE, new org.apache.thrift.meta_data.FieldMetaData("scope", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PointsRule.class, metaDataMap);
  }

  public PointsRule() {
  }

  public PointsRule(
    int win,
    int draw,
    int loss,
    java.lang.String scope)
  {
    this();
    this.win = win;
    setWinIsSet(true);
    this.draw = draw;
    setDrawIsSet(true);
    this.loss = loss;
    setLossIsSet(true);
    this.scope = scope;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PointsRule(PointsRule other) {
    __isset_bitfield = other.__isset_bitfield;
    this.win = other.win;
    this.draw = other.draw;
    this.loss = other.loss;
    if (other.isSetScope()) {
      this.scope = other.scope;
    }
  }

  @Override
  public PointsRule deepCopy() {
    return new PointsRule(this);
  }

  @Override
  public void clear() {
    setWinIsSet(false);
    this.win = 0;
    setDrawIsSet(false);
    this.draw = 0;
    setLossIsSet(false);
    this.loss = 0;
    this.scope = null;
  }

  public int getWin() {
    return this.win;
  }

  public PointsRule setWin(int win) {
    this.win = win;
    setWinIsSet(true);
    return this;
  }

  public void unsetWin() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __WIN_ISSET_ID);
  }

  /** Returns true if field win is set (has been assigned a value) and false otherwise */
  public boolean isSetWin() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __WIN_ISSET_ID);
  }

  public void setWinIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __WIN_ISSET_ID, value);
  }

  public int getDraw() {
    return this.draw;
  }

  public PointsRule setDraw(int draw) {
    this.draw = draw;
    setDrawIsSet(true);
    return this;
  }

  public void unsetDraw() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __DRAW_ISSET_ID);
  }

  /** Returns true if field draw is set (has been assigned a value) and false otherwise */
  public boolean isSetDraw() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __DRAW_ISSET_ID);
  }

  public void setDrawIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __DRAW_ISSET_ID, value);
  }

  public int getLoss() {
    return this.loss;
  }

  public PointsRule setLoss(int loss) {
    this.loss = loss;
    setLossIsSet(true);
    return this;
  }

  public void unsetLoss() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __LOSS_ISSET_ID);
  }

  /** Returns true if field loss is set (has been assigned a value) and false otherwise */
  public boolean isSetLoss() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __LOSS_ISSET_ID);
  }

  public void setLossIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __LOSS_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getScope() {
    return this.scope;
  }

  public PointsRule setScope(@org.apache.thrift.annotation.Nullable java.lang.String scope) {
    this.scope = scope;
    return this;
  }

  public void unsetScope() {
    this.scope = null;
  }

  /** Returns true if field scope is set (has been assigned a value) and false otherwise */
  public boolean isSetScope() {
    return this.scope != null;
  }

  public void setScopeIsSet(boolean value) {
    if (!value) {
      this.scope = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case WIN:
      if (value == null) {
        unsetWin();
      } else {
        setWin((java.lang.Integer)value);
      }
      break;

    case DRAW:
      if (value == null) {
        unsetDraw();
      } else {
        setDraw((java.lang.Integer)value);
      }
      break;

    case LOSS:
      if (value == null) {
        unsetLoss();
      } else {
        setLoss((java.lang.Integer)value);
      }
      break;

    case SCOPE:
      if (value == null) {
        unsetScope();
      } else {
        setScope((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case WIN:
      return getWin();

    case DRAW:
      return getDraw();

    case LOSS:
      return getLoss();

    case SCOPE:
      return getScope();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case WIN:
      return isSetWin();
    case DRAW:
      return isSetDraw();
    case LOSS:
      return isSetLoss();
    case SCOPE:
      return isSetScope();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof PointsRule)
      return this.equals((PointsRule)that);
    return false;
  }

  public boolean equals(PointsRule that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_win = true;
    boolean that_present_win = true;
    if (this_present_win || that_present_win) {
      if (!(this_present_win && that_present_win))
        return false;
      if (this.win != that.win)
        return false;
    }

    boolean this_present_draw = true;
    boolean that_present_draw = true;
    if (this_present_draw || that_present_draw) {
      if (!(this_present_draw && that_present_draw))
        return false;
      if (this.draw != that.draw)
        return false;
    }

    boolean this_present_loss = true;
    boolean that_present_loss = true;
    if (this_present_loss || that_present_loss) {
      if (!(this_present_loss && that_present_loss))
        return false;
      if (this.loss != that.loss)
        return false;
    }

    boolean this_present_scope = true && this.isSetScope();
    boolean that_present_scope = true && that.isSetScope();
    if (this_present_scope || that_present_scope) {
      if (!(this_present_scope && that_present_scope))
        return false;
      if (!this.scope.equals(that.scope))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + win;

    hashCode = hashCode * 8191 + draw;

    hashCode = hashCode * 8191 + loss;

    hashCode = hashCode * 8191 + ((isSetScope()) ? 131071 : 524287);
    if (isSetScope())
      hashCode = hashCode * 8191 + scope.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(PointsRule other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetWin(), other.isSetWin());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetWin()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.win, other.win);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetDraw(), other.isSetDraw());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDraw()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.draw, other.draw);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetLoss(), other.isSetLoss());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLoss()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.loss, other.loss);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetScope(), other.isSetScope());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetScope()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.scope, other.scope);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("PointsRule(");
    boolean first = true;

    sb.append("win:");
    sb.append(this.win);
    first = false;
    if (!first) sb.append(", ");
    sb.append("draw:");
    sb.append(this.draw);
    first = false;
    if (!first) sb.append(", ");
    sb.append("loss:");
    sb.append(this.loss);
    first = false;
    if (!first) sb.append(", ");
    sb.append("scope:");
    if (this.scope == null) {
      sb.append("null");
    } else {
      sb.append(this.scope);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PointsRuleStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public PointsRuleStandardScheme getScheme() {
      return new PointsRuleStandardScheme();
    }
  }

  private static class PointsRuleStandardScheme extends org.apache.thrift.scheme.StandardScheme<PointsRule> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, PointsRule struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // WIN
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.win = iprot.readI32();
              struct.setWinIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DRAW
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.draw = iprot.readI32();
              struct.setDrawIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // LOSS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.loss = iprot.readI32();
              struct.setLossIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // SCOPE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.scope = iprot.readString();
              struct.setScopeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, PointsRule struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(WIN_FIELD_DESC);
      oprot.writeI32(struct.win);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(DRAW_FIELD_DESC);
      oprot.writeI32(struct.draw);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(LOSS_FIELD_DESC);
      oprot.writeI32(struct.loss);
      oprot.writeFieldEnd();
      if (struct.scope != null) {
        oprot.writeFieldBegin(SCOPE_FIELD_DESC);
        oprot.writeString(struct.scope);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PointsRuleTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public PointsRuleTupleScheme getScheme() {
      return new PointsRuleTupleScheme();
    }
  }

  private static class PointsRuleTupleScheme extends org.apache.thrift.scheme.TupleScheme<PointsRule> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PointsRule struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetWin()) {
        optionals.set(0);
      }
      if (struct.isSetDraw()) {
        optionals.set(1);
      }
      if (struct.isSetLoss()) {
        optionals.set(2);
      }
      if (struct.isSetScope()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetWin()) {
        oprot.writeI32(struct.win);
      }
      if (struct.isSetDraw()) {
        oprot.writeI32(struct.draw);
      }
      if (struct.isSetLoss()) {
        oprot.writeI32(struct.loss);
      }
      if (struct.isSetScope()) {
        oprot.writeString(struct.scope);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PointsRule struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.win = iprot.readI32();
        struct.setWinIsSet(true);
      }
      if (incoming.get(1)) {
        struct.draw = iprot.readI32();
        struct.setDrawIsSet(true);
      }
      if (incoming.get(2)) {
        struct.loss = iprot.readI32();
        struct.setLossIsSet(true);
      }
      if (incoming.get(3)) {
        struct.scope = iprot.readString();
        struct.setScopeIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

