/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.apollo.backend.data;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class Stream implements org.apache.thrift.TBase<Stream, Stream._Fields>, java.io.Serializable, Cloneable, Comparable<Stream> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Stream");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField USERNAME_FIELD_DESC = new org.apache.thrift.protocol.TField("username", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField DISPLAY_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("displayName", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField STATUS_TEXT_FIELD_DESC = new org.apache.thrift.protocol.TField("statusText", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField VIEWER_COUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("viewerCount", org.apache.thrift.protocol.TType.I32, (short)5);
  private static final org.apache.thrift.protocol.TField ONLINE_FIELD_DESC = new org.apache.thrift.protocol.TField("online", org.apache.thrift.protocol.TType.BOOL, (short)6);
  private static final org.apache.thrift.protocol.TField LAST_ONLINE_FIELD_DESC = new org.apache.thrift.protocol.TField("lastOnline", org.apache.thrift.protocol.TType.I64, (short)7);
  private static final org.apache.thrift.protocol.TField IMAGES_FIELD_DESC = new org.apache.thrift.protocol.TField("images", org.apache.thrift.protocol.TType.LIST, (short)8);
  private static final org.apache.thrift.protocol.TField PLATFORM_FIELD_DESC = new org.apache.thrift.protocol.TField("platform", org.apache.thrift.protocol.TType.STRUCT, (short)9);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new StreamStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new StreamTupleSchemeFactory();

  public int id; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String username; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String displayName; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String statusText; // required
  public int viewerCount; // required
  public boolean online; // required
  public long lastOnline; // required
  public @org.apache.thrift.annotation.Nullable java.util.List<Image> images; // required
  public @org.apache.thrift.annotation.Nullable StreamingPlatform platform; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    USERNAME((short)2, "username"),
    DISPLAY_NAME((short)3, "displayName"),
    STATUS_TEXT((short)4, "statusText"),
    VIEWER_COUNT((short)5, "viewerCount"),
    ONLINE((short)6, "online"),
    LAST_ONLINE((short)7, "lastOnline"),
    IMAGES((short)8, "images"),
    PLATFORM((short)9, "platform");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // USERNAME
          return USERNAME;
        case 3: // DISPLAY_NAME
          return DISPLAY_NAME;
        case 4: // STATUS_TEXT
          return STATUS_TEXT;
        case 5: // VIEWER_COUNT
          return VIEWER_COUNT;
        case 6: // ONLINE
          return ONLINE;
        case 7: // LAST_ONLINE
          return LAST_ONLINE;
        case 8: // IMAGES
          return IMAGES;
        case 9: // PLATFORM
          return PLATFORM;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ID_ISSET_ID = 0;
  private static final int __VIEWERCOUNT_ISSET_ID = 1;
  private static final int __ONLINE_ISSET_ID = 2;
  private static final int __LASTONLINE_ISSET_ID = 3;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.USERNAME, new org.apache.thrift.meta_data.FieldMetaData("username", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DISPLAY_NAME, new org.apache.thrift.meta_data.FieldMetaData("displayName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.STATUS_TEXT, new org.apache.thrift.meta_data.FieldMetaData("statusText", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.VIEWER_COUNT, new org.apache.thrift.meta_data.FieldMetaData("viewerCount", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.ONLINE, new org.apache.thrift.meta_data.FieldMetaData("online", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.LAST_ONLINE, new org.apache.thrift.meta_data.FieldMetaData("lastOnline", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.IMAGES, new org.apache.thrift.meta_data.FieldMetaData("images", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Image.class))));
    tmpMap.put(_Fields.PLATFORM, new org.apache.thrift.meta_data.FieldMetaData("platform", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, StreamingPlatform.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Stream.class, metaDataMap);
  }

  public Stream() {
  }

  public Stream(
    int id,
    java.lang.String username,
    java.lang.String displayName,
    java.lang.String statusText,
    int viewerCount,
    boolean online,
    long lastOnline,
    java.util.List<Image> images,
    StreamingPlatform platform)
  {
    this();
    this.id = id;
    setIdIsSet(true);
    this.username = username;
    this.displayName = displayName;
    this.statusText = statusText;
    this.viewerCount = viewerCount;
    setViewerCountIsSet(true);
    this.online = online;
    setOnlineIsSet(true);
    this.lastOnline = lastOnline;
    setLastOnlineIsSet(true);
    this.images = images;
    this.platform = platform;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Stream(Stream other) {
    __isset_bitfield = other.__isset_bitfield;
    this.id = other.id;
    if (other.isSetUsername()) {
      this.username = other.username;
    }
    if (other.isSetDisplayName()) {
      this.displayName = other.displayName;
    }
    if (other.isSetStatusText()) {
      this.statusText = other.statusText;
    }
    this.viewerCount = other.viewerCount;
    this.online = other.online;
    this.lastOnline = other.lastOnline;
    if (other.isSetImages()) {
      java.util.List<Image> __this__images = new java.util.ArrayList<Image>(other.images.size());
      for (Image other_element : other.images) {
        __this__images.add(new Image(other_element));
      }
      this.images = __this__images;
    }
    if (other.isSetPlatform()) {
      this.platform = new StreamingPlatform(other.platform);
    }
  }

  @Override
  public Stream deepCopy() {
    return new Stream(this);
  }

  @Override
  public void clear() {
    setIdIsSet(false);
    this.id = 0;
    this.username = null;
    this.displayName = null;
    this.statusText = null;
    setViewerCountIsSet(false);
    this.viewerCount = 0;
    setOnlineIsSet(false);
    this.online = false;
    setLastOnlineIsSet(false);
    this.lastOnline = 0;
    this.images = null;
    this.platform = null;
  }

  public int getId() {
    return this.id;
  }

  public Stream setId(int id) {
    this.id = id;
    setIdIsSet(true);
    return this;
  }

  public void unsetId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ID_ISSET_ID);
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ID_ISSET_ID);
  }

  public void setIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ID_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getUsername() {
    return this.username;
  }

  public Stream setUsername(@org.apache.thrift.annotation.Nullable java.lang.String username) {
    this.username = username;
    return this;
  }

  public void unsetUsername() {
    this.username = null;
  }

  /** Returns true if field username is set (has been assigned a value) and false otherwise */
  public boolean isSetUsername() {
    return this.username != null;
  }

  public void setUsernameIsSet(boolean value) {
    if (!value) {
      this.username = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getDisplayName() {
    return this.displayName;
  }

  public Stream setDisplayName(@org.apache.thrift.annotation.Nullable java.lang.String displayName) {
    this.displayName = displayName;
    return this;
  }

  public void unsetDisplayName() {
    this.displayName = null;
  }

  /** Returns true if field displayName is set (has been assigned a value) and false otherwise */
  public boolean isSetDisplayName() {
    return this.displayName != null;
  }

  public void setDisplayNameIsSet(boolean value) {
    if (!value) {
      this.displayName = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getStatusText() {
    return this.statusText;
  }

  public Stream setStatusText(@org.apache.thrift.annotation.Nullable java.lang.String statusText) {
    this.statusText = statusText;
    return this;
  }

  public void unsetStatusText() {
    this.statusText = null;
  }

  /** Returns true if field statusText is set (has been assigned a value) and false otherwise */
  public boolean isSetStatusText() {
    return this.statusText != null;
  }

  public void setStatusTextIsSet(boolean value) {
    if (!value) {
      this.statusText = null;
    }
  }

  public int getViewerCount() {
    return this.viewerCount;
  }

  public Stream setViewerCount(int viewerCount) {
    this.viewerCount = viewerCount;
    setViewerCountIsSet(true);
    return this;
  }

  public void unsetViewerCount() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __VIEWERCOUNT_ISSET_ID);
  }

  /** Returns true if field viewerCount is set (has been assigned a value) and false otherwise */
  public boolean isSetViewerCount() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __VIEWERCOUNT_ISSET_ID);
  }

  public void setViewerCountIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __VIEWERCOUNT_ISSET_ID, value);
  }

  public boolean isOnline() {
    return this.online;
  }

  public Stream setOnline(boolean online) {
    this.online = online;
    setOnlineIsSet(true);
    return this;
  }

  public void unsetOnline() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ONLINE_ISSET_ID);
  }

  /** Returns true if field online is set (has been assigned a value) and false otherwise */
  public boolean isSetOnline() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ONLINE_ISSET_ID);
  }

  public void setOnlineIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ONLINE_ISSET_ID, value);
  }

  public long getLastOnline() {
    return this.lastOnline;
  }

  public Stream setLastOnline(long lastOnline) {
    this.lastOnline = lastOnline;
    setLastOnlineIsSet(true);
    return this;
  }

  public void unsetLastOnline() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __LASTONLINE_ISSET_ID);
  }

  /** Returns true if field lastOnline is set (has been assigned a value) and false otherwise */
  public boolean isSetLastOnline() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __LASTONLINE_ISSET_ID);
  }

  public void setLastOnlineIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __LASTONLINE_ISSET_ID, value);
  }

  public int getImagesSize() {
    return (this.images == null) ? 0 : this.images.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<Image> getImagesIterator() {
    return (this.images == null) ? null : this.images.iterator();
  }

  public void addToImages(Image elem) {
    if (this.images == null) {
      this.images = new java.util.ArrayList<Image>();
    }
    this.images.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<Image> getImages() {
    return this.images;
  }

  public Stream setImages(@org.apache.thrift.annotation.Nullable java.util.List<Image> images) {
    this.images = images;
    return this;
  }

  public void unsetImages() {
    this.images = null;
  }

  /** Returns true if field images is set (has been assigned a value) and false otherwise */
  public boolean isSetImages() {
    return this.images != null;
  }

  public void setImagesIsSet(boolean value) {
    if (!value) {
      this.images = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public StreamingPlatform getPlatform() {
    return this.platform;
  }

  public Stream setPlatform(@org.apache.thrift.annotation.Nullable StreamingPlatform platform) {
    this.platform = platform;
    return this;
  }

  public void unsetPlatform() {
    this.platform = null;
  }

  /** Returns true if field platform is set (has been assigned a value) and false otherwise */
  public boolean isSetPlatform() {
    return this.platform != null;
  }

  public void setPlatformIsSet(boolean value) {
    if (!value) {
      this.platform = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((java.lang.Integer)value);
      }
      break;

    case USERNAME:
      if (value == null) {
        unsetUsername();
      } else {
        setUsername((java.lang.String)value);
      }
      break;

    case DISPLAY_NAME:
      if (value == null) {
        unsetDisplayName();
      } else {
        setDisplayName((java.lang.String)value);
      }
      break;

    case STATUS_TEXT:
      if (value == null) {
        unsetStatusText();
      } else {
        setStatusText((java.lang.String)value);
      }
      break;

    case VIEWER_COUNT:
      if (value == null) {
        unsetViewerCount();
      } else {
        setViewerCount((java.lang.Integer)value);
      }
      break;

    case ONLINE:
      if (value == null) {
        unsetOnline();
      } else {
        setOnline((java.lang.Boolean)value);
      }
      break;

    case LAST_ONLINE:
      if (value == null) {
        unsetLastOnline();
      } else {
        setLastOnline((java.lang.Long)value);
      }
      break;

    case IMAGES:
      if (value == null) {
        unsetImages();
      } else {
        setImages((java.util.List<Image>)value);
      }
      break;

    case PLATFORM:
      if (value == null) {
        unsetPlatform();
      } else {
        setPlatform((StreamingPlatform)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return getId();

    case USERNAME:
      return getUsername();

    case DISPLAY_NAME:
      return getDisplayName();

    case STATUS_TEXT:
      return getStatusText();

    case VIEWER_COUNT:
      return getViewerCount();

    case ONLINE:
      return isOnline();

    case LAST_ONLINE:
      return getLastOnline();

    case IMAGES:
      return getImages();

    case PLATFORM:
      return getPlatform();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case USERNAME:
      return isSetUsername();
    case DISPLAY_NAME:
      return isSetDisplayName();
    case STATUS_TEXT:
      return isSetStatusText();
    case VIEWER_COUNT:
      return isSetViewerCount();
    case ONLINE:
      return isSetOnline();
    case LAST_ONLINE:
      return isSetLastOnline();
    case IMAGES:
      return isSetImages();
    case PLATFORM:
      return isSetPlatform();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof Stream)
      return this.equals((Stream)that);
    return false;
  }

  public boolean equals(Stream that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_id = true;
    boolean that_present_id = true;
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (this.id != that.id)
        return false;
    }

    boolean this_present_username = true && this.isSetUsername();
    boolean that_present_username = true && that.isSetUsername();
    if (this_present_username || that_present_username) {
      if (!(this_present_username && that_present_username))
        return false;
      if (!this.username.equals(that.username))
        return false;
    }

    boolean this_present_displayName = true && this.isSetDisplayName();
    boolean that_present_displayName = true && that.isSetDisplayName();
    if (this_present_displayName || that_present_displayName) {
      if (!(this_present_displayName && that_present_displayName))
        return false;
      if (!this.displayName.equals(that.displayName))
        return false;
    }

    boolean this_present_statusText = true && this.isSetStatusText();
    boolean that_present_statusText = true && that.isSetStatusText();
    if (this_present_statusText || that_present_statusText) {
      if (!(this_present_statusText && that_present_statusText))
        return false;
      if (!this.statusText.equals(that.statusText))
        return false;
    }

    boolean this_present_viewerCount = true;
    boolean that_present_viewerCount = true;
    if (this_present_viewerCount || that_present_viewerCount) {
      if (!(this_present_viewerCount && that_present_viewerCount))
        return false;
      if (this.viewerCount != that.viewerCount)
        return false;
    }

    boolean this_present_online = true;
    boolean that_present_online = true;
    if (this_present_online || that_present_online) {
      if (!(this_present_online && that_present_online))
        return false;
      if (this.online != that.online)
        return false;
    }

    boolean this_present_lastOnline = true;
    boolean that_present_lastOnline = true;
    if (this_present_lastOnline || that_present_lastOnline) {
      if (!(this_present_lastOnline && that_present_lastOnline))
        return false;
      if (this.lastOnline != that.lastOnline)
        return false;
    }

    boolean this_present_images = true && this.isSetImages();
    boolean that_present_images = true && that.isSetImages();
    if (this_present_images || that_present_images) {
      if (!(this_present_images && that_present_images))
        return false;
      if (!this.images.equals(that.images))
        return false;
    }

    boolean this_present_platform = true && this.isSetPlatform();
    boolean that_present_platform = true && that.isSetPlatform();
    if (this_present_platform || that_present_platform) {
      if (!(this_present_platform && that_present_platform))
        return false;
      if (!this.platform.equals(that.platform))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + id;

    hashCode = hashCode * 8191 + ((isSetUsername()) ? 131071 : 524287);
    if (isSetUsername())
      hashCode = hashCode * 8191 + username.hashCode();

    hashCode = hashCode * 8191 + ((isSetDisplayName()) ? 131071 : 524287);
    if (isSetDisplayName())
      hashCode = hashCode * 8191 + displayName.hashCode();

    hashCode = hashCode * 8191 + ((isSetStatusText()) ? 131071 : 524287);
    if (isSetStatusText())
      hashCode = hashCode * 8191 + statusText.hashCode();

    hashCode = hashCode * 8191 + viewerCount;

    hashCode = hashCode * 8191 + ((online) ? 131071 : 524287);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(lastOnline);

    hashCode = hashCode * 8191 + ((isSetImages()) ? 131071 : 524287);
    if (isSetImages())
      hashCode = hashCode * 8191 + images.hashCode();

    hashCode = hashCode * 8191 + ((isSetPlatform()) ? 131071 : 524287);
    if (isSetPlatform())
      hashCode = hashCode * 8191 + platform.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(Stream other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetId(), other.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetUsername(), other.isSetUsername());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUsername()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.username, other.username);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetDisplayName(), other.isSetDisplayName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDisplayName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.displayName, other.displayName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetStatusText(), other.isSetStatusText());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStatusText()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.statusText, other.statusText);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetViewerCount(), other.isSetViewerCount());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetViewerCount()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.viewerCount, other.viewerCount);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetOnline(), other.isSetOnline());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOnline()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.online, other.online);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetLastOnline(), other.isSetLastOnline());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLastOnline()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lastOnline, other.lastOnline);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetImages(), other.isSetImages());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetImages()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.images, other.images);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetPlatform(), other.isSetPlatform());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPlatform()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.platform, other.platform);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Stream(");
    boolean first = true;

    sb.append("id:");
    sb.append(this.id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("username:");
    if (this.username == null) {
      sb.append("null");
    } else {
      sb.append(this.username);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("displayName:");
    if (this.displayName == null) {
      sb.append("null");
    } else {
      sb.append(this.displayName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("statusText:");
    if (this.statusText == null) {
      sb.append("null");
    } else {
      sb.append(this.statusText);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("viewerCount:");
    sb.append(this.viewerCount);
    first = false;
    if (!first) sb.append(", ");
    sb.append("online:");
    sb.append(this.online);
    first = false;
    if (!first) sb.append(", ");
    sb.append("lastOnline:");
    sb.append(this.lastOnline);
    first = false;
    if (!first) sb.append(", ");
    sb.append("images:");
    if (this.images == null) {
      sb.append("null");
    } else {
      sb.append(this.images);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("platform:");
    if (this.platform == null) {
      sb.append("null");
    } else {
      sb.append(this.platform);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (platform != null) {
      platform.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class StreamStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public StreamStandardScheme getScheme() {
      return new StreamStandardScheme();
    }
  }

  private static class StreamStandardScheme extends org.apache.thrift.scheme.StandardScheme<Stream> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, Stream struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.id = iprot.readI32();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // USERNAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.username = iprot.readString();
              struct.setUsernameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // DISPLAY_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.displayName = iprot.readString();
              struct.setDisplayNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // STATUS_TEXT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.statusText = iprot.readString();
              struct.setStatusTextIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // VIEWER_COUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.viewerCount = iprot.readI32();
              struct.setViewerCountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // ONLINE
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.online = iprot.readBool();
              struct.setOnlineIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // LAST_ONLINE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.lastOnline = iprot.readI64();
              struct.setLastOnlineIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // IMAGES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list528 = iprot.readListBegin();
                struct.images = new java.util.ArrayList<Image>(_list528.size);
                @org.apache.thrift.annotation.Nullable Image _elem529;
                for (int _i530 = 0; _i530 < _list528.size; ++_i530)
                {
                  _elem529 = new Image();
                  _elem529.read(iprot);
                  struct.images.add(_elem529);
                }
                iprot.readListEnd();
              }
              struct.setImagesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // PLATFORM
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.platform = new StreamingPlatform();
              struct.platform.read(iprot);
              struct.setPlatformIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, Stream struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ID_FIELD_DESC);
      oprot.writeI32(struct.id);
      oprot.writeFieldEnd();
      if (struct.username != null) {
        oprot.writeFieldBegin(USERNAME_FIELD_DESC);
        oprot.writeString(struct.username);
        oprot.writeFieldEnd();
      }
      if (struct.displayName != null) {
        oprot.writeFieldBegin(DISPLAY_NAME_FIELD_DESC);
        oprot.writeString(struct.displayName);
        oprot.writeFieldEnd();
      }
      if (struct.statusText != null) {
        oprot.writeFieldBegin(STATUS_TEXT_FIELD_DESC);
        oprot.writeString(struct.statusText);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(VIEWER_COUNT_FIELD_DESC);
      oprot.writeI32(struct.viewerCount);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(ONLINE_FIELD_DESC);
      oprot.writeBool(struct.online);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(LAST_ONLINE_FIELD_DESC);
      oprot.writeI64(struct.lastOnline);
      oprot.writeFieldEnd();
      if (struct.images != null) {
        oprot.writeFieldBegin(IMAGES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.images.size()));
          for (Image _iter531 : struct.images)
          {
            _iter531.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.platform != null) {
        oprot.writeFieldBegin(PLATFORM_FIELD_DESC);
        struct.platform.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class StreamTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public StreamTupleScheme getScheme() {
      return new StreamTupleScheme();
    }
  }

  private static class StreamTupleScheme extends org.apache.thrift.scheme.TupleScheme<Stream> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Stream struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetId()) {
        optionals.set(0);
      }
      if (struct.isSetUsername()) {
        optionals.set(1);
      }
      if (struct.isSetDisplayName()) {
        optionals.set(2);
      }
      if (struct.isSetStatusText()) {
        optionals.set(3);
      }
      if (struct.isSetViewerCount()) {
        optionals.set(4);
      }
      if (struct.isSetOnline()) {
        optionals.set(5);
      }
      if (struct.isSetLastOnline()) {
        optionals.set(6);
      }
      if (struct.isSetImages()) {
        optionals.set(7);
      }
      if (struct.isSetPlatform()) {
        optionals.set(8);
      }
      oprot.writeBitSet(optionals, 9);
      if (struct.isSetId()) {
        oprot.writeI32(struct.id);
      }
      if (struct.isSetUsername()) {
        oprot.writeString(struct.username);
      }
      if (struct.isSetDisplayName()) {
        oprot.writeString(struct.displayName);
      }
      if (struct.isSetStatusText()) {
        oprot.writeString(struct.statusText);
      }
      if (struct.isSetViewerCount()) {
        oprot.writeI32(struct.viewerCount);
      }
      if (struct.isSetOnline()) {
        oprot.writeBool(struct.online);
      }
      if (struct.isSetLastOnline()) {
        oprot.writeI64(struct.lastOnline);
      }
      if (struct.isSetImages()) {
        {
          oprot.writeI32(struct.images.size());
          for (Image _iter532 : struct.images)
          {
            _iter532.write(oprot);
          }
        }
      }
      if (struct.isSetPlatform()) {
        struct.platform.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Stream struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(9);
      if (incoming.get(0)) {
        struct.id = iprot.readI32();
        struct.setIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.username = iprot.readString();
        struct.setUsernameIsSet(true);
      }
      if (incoming.get(2)) {
        struct.displayName = iprot.readString();
        struct.setDisplayNameIsSet(true);
      }
      if (incoming.get(3)) {
        struct.statusText = iprot.readString();
        struct.setStatusTextIsSet(true);
      }
      if (incoming.get(4)) {
        struct.viewerCount = iprot.readI32();
        struct.setViewerCountIsSet(true);
      }
      if (incoming.get(5)) {
        struct.online = iprot.readBool();
        struct.setOnlineIsSet(true);
      }
      if (incoming.get(6)) {
        struct.lastOnline = iprot.readI64();
        struct.setLastOnlineIsSet(true);
      }
      if (incoming.get(7)) {
        {
          org.apache.thrift.protocol.TList _list533 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
          struct.images = new java.util.ArrayList<Image>(_list533.size);
          @org.apache.thrift.annotation.Nullable Image _elem534;
          for (int _i535 = 0; _i535 < _list533.size; ++_i535)
          {
            _elem534 = new Image();
            _elem534.read(iprot);
            struct.images.add(_elem534);
          }
        }
        struct.setImagesIsSet(true);
      }
      if (incoming.get(8)) {
        struct.platform = new StreamingPlatform();
        struct.platform.read(iprot);
        struct.setPlatformIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

