/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.apollo.backend.data;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class SubstageFormat implements org.apache.thrift.TBase<SubstageFormat, SubstageFormat._Fields>, java.io.Serializable, Cloneable, Comparable<SubstageFormat> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SubstageFormat");

  private static final org.apache.thrift.protocol.TField POINTS_FIELD_DESC = new org.apache.thrift.protocol.TField("points", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField MOVEMENTS_FIELD_DESC = new org.apache.thrift.protocol.TField("movements", org.apache.thrift.protocol.TType.LIST, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new SubstageFormatStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new SubstageFormatTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable PointsRule points; // required
  public @org.apache.thrift.annotation.Nullable java.util.List<Movement> movements; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    POINTS((short)1, "points"),
    MOVEMENTS((short)2, "movements");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // POINTS
          return POINTS;
        case 2: // MOVEMENTS
          return MOVEMENTS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.POINTS, new org.apache.thrift.meta_data.FieldMetaData("points", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, PointsRule.class)));
    tmpMap.put(_Fields.MOVEMENTS, new org.apache.thrift.meta_data.FieldMetaData("movements", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Movement.class))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SubstageFormat.class, metaDataMap);
  }

  public SubstageFormat() {
  }

  public SubstageFormat(
    PointsRule points,
    java.util.List<Movement> movements)
  {
    this();
    this.points = points;
    this.movements = movements;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SubstageFormat(SubstageFormat other) {
    if (other.isSetPoints()) {
      this.points = new PointsRule(other.points);
    }
    if (other.isSetMovements()) {
      java.util.List<Movement> __this__movements = new java.util.ArrayList<Movement>(other.movements.size());
      for (Movement other_element : other.movements) {
        __this__movements.add(new Movement(other_element));
      }
      this.movements = __this__movements;
    }
  }

  @Override
  public SubstageFormat deepCopy() {
    return new SubstageFormat(this);
  }

  @Override
  public void clear() {
    this.points = null;
    this.movements = null;
  }

  @org.apache.thrift.annotation.Nullable
  public PointsRule getPoints() {
    return this.points;
  }

  public SubstageFormat setPoints(@org.apache.thrift.annotation.Nullable PointsRule points) {
    this.points = points;
    return this;
  }

  public void unsetPoints() {
    this.points = null;
  }

  /** Returns true if field points is set (has been assigned a value) and false otherwise */
  public boolean isSetPoints() {
    return this.points != null;
  }

  public void setPointsIsSet(boolean value) {
    if (!value) {
      this.points = null;
    }
  }

  public int getMovementsSize() {
    return (this.movements == null) ? 0 : this.movements.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<Movement> getMovementsIterator() {
    return (this.movements == null) ? null : this.movements.iterator();
  }

  public void addToMovements(Movement elem) {
    if (this.movements == null) {
      this.movements = new java.util.ArrayList<Movement>();
    }
    this.movements.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<Movement> getMovements() {
    return this.movements;
  }

  public SubstageFormat setMovements(@org.apache.thrift.annotation.Nullable java.util.List<Movement> movements) {
    this.movements = movements;
    return this;
  }

  public void unsetMovements() {
    this.movements = null;
  }

  /** Returns true if field movements is set (has been assigned a value) and false otherwise */
  public boolean isSetMovements() {
    return this.movements != null;
  }

  public void setMovementsIsSet(boolean value) {
    if (!value) {
      this.movements = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case POINTS:
      if (value == null) {
        unsetPoints();
      } else {
        setPoints((PointsRule)value);
      }
      break;

    case MOVEMENTS:
      if (value == null) {
        unsetMovements();
      } else {
        setMovements((java.util.List<Movement>)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case POINTS:
      return getPoints();

    case MOVEMENTS:
      return getMovements();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case POINTS:
      return isSetPoints();
    case MOVEMENTS:
      return isSetMovements();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof SubstageFormat)
      return this.equals((SubstageFormat)that);
    return false;
  }

  public boolean equals(SubstageFormat that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_points = true && this.isSetPoints();
    boolean that_present_points = true && that.isSetPoints();
    if (this_present_points || that_present_points) {
      if (!(this_present_points && that_present_points))
        return false;
      if (!this.points.equals(that.points))
        return false;
    }

    boolean this_present_movements = true && this.isSetMovements();
    boolean that_present_movements = true && that.isSetMovements();
    if (this_present_movements || that_present_movements) {
      if (!(this_present_movements && that_present_movements))
        return false;
      if (!this.movements.equals(that.movements))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetPoints()) ? 131071 : 524287);
    if (isSetPoints())
      hashCode = hashCode * 8191 + points.hashCode();

    hashCode = hashCode * 8191 + ((isSetMovements()) ? 131071 : 524287);
    if (isSetMovements())
      hashCode = hashCode * 8191 + movements.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(SubstageFormat other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetPoints(), other.isSetPoints());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPoints()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.points, other.points);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetMovements(), other.isSetMovements());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMovements()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.movements, other.movements);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("SubstageFormat(");
    boolean first = true;

    sb.append("points:");
    if (this.points == null) {
      sb.append("null");
    } else {
      sb.append(this.points);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("movements:");
    if (this.movements == null) {
      sb.append("null");
    } else {
      sb.append(this.movements);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (points != null) {
      points.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SubstageFormatStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public SubstageFormatStandardScheme getScheme() {
      return new SubstageFormatStandardScheme();
    }
  }

  private static class SubstageFormatStandardScheme extends org.apache.thrift.scheme.StandardScheme<SubstageFormat> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, SubstageFormat struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // POINTS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.points = new PointsRule();
              struct.points.read(iprot);
              struct.setPointsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // MOVEMENTS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list536 = iprot.readListBegin();
                struct.movements = new java.util.ArrayList<Movement>(_list536.size);
                @org.apache.thrift.annotation.Nullable Movement _elem537;
                for (int _i538 = 0; _i538 < _list536.size; ++_i538)
                {
                  _elem537 = new Movement();
                  _elem537.read(iprot);
                  struct.movements.add(_elem537);
                }
                iprot.readListEnd();
              }
              struct.setMovementsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, SubstageFormat struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.points != null) {
        oprot.writeFieldBegin(POINTS_FIELD_DESC);
        struct.points.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.movements != null) {
        oprot.writeFieldBegin(MOVEMENTS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.movements.size()));
          for (Movement _iter539 : struct.movements)
          {
            _iter539.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SubstageFormatTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public SubstageFormatTupleScheme getScheme() {
      return new SubstageFormatTupleScheme();
    }
  }

  private static class SubstageFormatTupleScheme extends org.apache.thrift.scheme.TupleScheme<SubstageFormat> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SubstageFormat struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetPoints()) {
        optionals.set(0);
      }
      if (struct.isSetMovements()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetPoints()) {
        struct.points.write(oprot);
      }
      if (struct.isSetMovements()) {
        {
          oprot.writeI32(struct.movements.size());
          for (Movement _iter540 : struct.movements)
          {
            _iter540.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SubstageFormat struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.points = new PointsRule();
        struct.points.read(iprot);
        struct.setPointsIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list541 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
          struct.movements = new java.util.ArrayList<Movement>(_list541.size);
          @org.apache.thrift.annotation.Nullable Movement _elem542;
          for (int _i543 = 0; _i543 < _list541.size; ++_i543)
          {
            _elem542 = new Movement();
            _elem542.read(iprot);
            struct.movements.add(_elem542);
          }
        }
        struct.setMovementsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

