/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.apollo.backend.data;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class SubstageRules implements org.apache.thrift.TBase<SubstageRules, SubstageRules._Fields>, java.io.Serializable, Cloneable, Comparable<SubstageRules> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SubstageRules");

  private static final org.apache.thrift.protocol.TField ADVANCE_FIELD_DESC = new org.apache.thrift.protocol.TField("advance", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField DESCEND_FIELD_DESC = new org.apache.thrift.protocol.TField("descend", org.apache.thrift.protocol.TType.STRUCT, (short)2);
  private static final org.apache.thrift.protocol.TField POINTS_FIELD_DESC = new org.apache.thrift.protocol.TField("points", org.apache.thrift.protocol.TType.STRUCT, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new SubstageRulesStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new SubstageRulesTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable AdvanceRule advance; // required
  public @org.apache.thrift.annotation.Nullable DescendRule descend; // required
  public @org.apache.thrift.annotation.Nullable PointsRule points; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ADVANCE((short)1, "advance"),
    DESCEND((short)2, "descend"),
    POINTS((short)3, "points");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ADVANCE
          return ADVANCE;
        case 2: // DESCEND
          return DESCEND;
        case 3: // POINTS
          return POINTS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ADVANCE, new org.apache.thrift.meta_data.FieldMetaData("advance", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, AdvanceRule.class)));
    tmpMap.put(_Fields.DESCEND, new org.apache.thrift.meta_data.FieldMetaData("descend", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, DescendRule.class)));
    tmpMap.put(_Fields.POINTS, new org.apache.thrift.meta_data.FieldMetaData("points", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, PointsRule.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SubstageRules.class, metaDataMap);
  }

  public SubstageRules() {
  }

  public SubstageRules(
    AdvanceRule advance,
    DescendRule descend,
    PointsRule points)
  {
    this();
    this.advance = advance;
    this.descend = descend;
    this.points = points;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SubstageRules(SubstageRules other) {
    if (other.isSetAdvance()) {
      this.advance = new AdvanceRule(other.advance);
    }
    if (other.isSetDescend()) {
      this.descend = new DescendRule(other.descend);
    }
    if (other.isSetPoints()) {
      this.points = new PointsRule(other.points);
    }
  }

  @Override
  public SubstageRules deepCopy() {
    return new SubstageRules(this);
  }

  @Override
  public void clear() {
    this.advance = null;
    this.descend = null;
    this.points = null;
  }

  @org.apache.thrift.annotation.Nullable
  public AdvanceRule getAdvance() {
    return this.advance;
  }

  public SubstageRules setAdvance(@org.apache.thrift.annotation.Nullable AdvanceRule advance) {
    this.advance = advance;
    return this;
  }

  public void unsetAdvance() {
    this.advance = null;
  }

  /** Returns true if field advance is set (has been assigned a value) and false otherwise */
  public boolean isSetAdvance() {
    return this.advance != null;
  }

  public void setAdvanceIsSet(boolean value) {
    if (!value) {
      this.advance = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public DescendRule getDescend() {
    return this.descend;
  }

  public SubstageRules setDescend(@org.apache.thrift.annotation.Nullable DescendRule descend) {
    this.descend = descend;
    return this;
  }

  public void unsetDescend() {
    this.descend = null;
  }

  /** Returns true if field descend is set (has been assigned a value) and false otherwise */
  public boolean isSetDescend() {
    return this.descend != null;
  }

  public void setDescendIsSet(boolean value) {
    if (!value) {
      this.descend = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public PointsRule getPoints() {
    return this.points;
  }

  public SubstageRules setPoints(@org.apache.thrift.annotation.Nullable PointsRule points) {
    this.points = points;
    return this;
  }

  public void unsetPoints() {
    this.points = null;
  }

  /** Returns true if field points is set (has been assigned a value) and false otherwise */
  public boolean isSetPoints() {
    return this.points != null;
  }

  public void setPointsIsSet(boolean value) {
    if (!value) {
      this.points = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case ADVANCE:
      if (value == null) {
        unsetAdvance();
      } else {
        setAdvance((AdvanceRule)value);
      }
      break;

    case DESCEND:
      if (value == null) {
        unsetDescend();
      } else {
        setDescend((DescendRule)value);
      }
      break;

    case POINTS:
      if (value == null) {
        unsetPoints();
      } else {
        setPoints((PointsRule)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ADVANCE:
      return getAdvance();

    case DESCEND:
      return getDescend();

    case POINTS:
      return getPoints();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ADVANCE:
      return isSetAdvance();
    case DESCEND:
      return isSetDescend();
    case POINTS:
      return isSetPoints();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof SubstageRules)
      return this.equals((SubstageRules)that);
    return false;
  }

  public boolean equals(SubstageRules that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_advance = true && this.isSetAdvance();
    boolean that_present_advance = true && that.isSetAdvance();
    if (this_present_advance || that_present_advance) {
      if (!(this_present_advance && that_present_advance))
        return false;
      if (!this.advance.equals(that.advance))
        return false;
    }

    boolean this_present_descend = true && this.isSetDescend();
    boolean that_present_descend = true && that.isSetDescend();
    if (this_present_descend || that_present_descend) {
      if (!(this_present_descend && that_present_descend))
        return false;
      if (!this.descend.equals(that.descend))
        return false;
    }

    boolean this_present_points = true && this.isSetPoints();
    boolean that_present_points = true && that.isSetPoints();
    if (this_present_points || that_present_points) {
      if (!(this_present_points && that_present_points))
        return false;
      if (!this.points.equals(that.points))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetAdvance()) ? 131071 : 524287);
    if (isSetAdvance())
      hashCode = hashCode * 8191 + advance.hashCode();

    hashCode = hashCode * 8191 + ((isSetDescend()) ? 131071 : 524287);
    if (isSetDescend())
      hashCode = hashCode * 8191 + descend.hashCode();

    hashCode = hashCode * 8191 + ((isSetPoints()) ? 131071 : 524287);
    if (isSetPoints())
      hashCode = hashCode * 8191 + points.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(SubstageRules other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetAdvance(), other.isSetAdvance());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAdvance()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.advance, other.advance);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetDescend(), other.isSetDescend());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDescend()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.descend, other.descend);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetPoints(), other.isSetPoints());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPoints()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.points, other.points);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("SubstageRules(");
    boolean first = true;

    sb.append("advance:");
    if (this.advance == null) {
      sb.append("null");
    } else {
      sb.append(this.advance);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("descend:");
    if (this.descend == null) {
      sb.append("null");
    } else {
      sb.append(this.descend);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("points:");
    if (this.points == null) {
      sb.append("null");
    } else {
      sb.append(this.points);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (advance != null) {
      advance.validate();
    }
    if (descend != null) {
      descend.validate();
    }
    if (points != null) {
      points.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SubstageRulesStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public SubstageRulesStandardScheme getScheme() {
      return new SubstageRulesStandardScheme();
    }
  }

  private static class SubstageRulesStandardScheme extends org.apache.thrift.scheme.StandardScheme<SubstageRules> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, SubstageRules struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ADVANCE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.advance = new AdvanceRule();
              struct.advance.read(iprot);
              struct.setAdvanceIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DESCEND
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.descend = new DescendRule();
              struct.descend.read(iprot);
              struct.setDescendIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // POINTS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.points = new PointsRule();
              struct.points.read(iprot);
              struct.setPointsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, SubstageRules struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.advance != null) {
        oprot.writeFieldBegin(ADVANCE_FIELD_DESC);
        struct.advance.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.descend != null) {
        oprot.writeFieldBegin(DESCEND_FIELD_DESC);
        struct.descend.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.points != null) {
        oprot.writeFieldBegin(POINTS_FIELD_DESC);
        struct.points.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SubstageRulesTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public SubstageRulesTupleScheme getScheme() {
      return new SubstageRulesTupleScheme();
    }
  }

  private static class SubstageRulesTupleScheme extends org.apache.thrift.scheme.TupleScheme<SubstageRules> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SubstageRules struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetAdvance()) {
        optionals.set(0);
      }
      if (struct.isSetDescend()) {
        optionals.set(1);
      }
      if (struct.isSetPoints()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetAdvance()) {
        struct.advance.write(oprot);
      }
      if (struct.isSetDescend()) {
        struct.descend.write(oprot);
      }
      if (struct.isSetPoints()) {
        struct.points.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SubstageRules struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.advance = new AdvanceRule();
        struct.advance.read(iprot);
        struct.setAdvanceIsSet(true);
      }
      if (incoming.get(1)) {
        struct.descend = new DescendRule();
        struct.descend.read(iprot);
        struct.setDescendIsSet(true);
      }
      if (incoming.get(2)) {
        struct.points = new PointsRule();
        struct.points.read(iprot);
        struct.setPointsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

