/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.apollo.backend.data;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class TournamentDefaults implements org.apache.thrift.TBase<TournamentDefaults, TournamentDefaults._Fields>, java.io.Serializable, Cloneable, Comparable<TournamentDefaults> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TournamentDefaults");

  private static final org.apache.thrift.protocol.TField GAME_VERSION_FIELD_DESC = new org.apache.thrift.protocol.TField("gameVersion", org.apache.thrift.protocol.TType.STRUCT, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TournamentDefaultsStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TournamentDefaultsTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable GameVersion gameVersion; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    GAME_VERSION((short)1, "gameVersion");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // GAME_VERSION
          return GAME_VERSION;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.GAME_VERSION, new org.apache.thrift.meta_data.FieldMetaData("gameVersion", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, GameVersion.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TournamentDefaults.class, metaDataMap);
  }

  public TournamentDefaults() {
  }

  public TournamentDefaults(
    GameVersion gameVersion)
  {
    this();
    this.gameVersion = gameVersion;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TournamentDefaults(TournamentDefaults other) {
    if (other.isSetGameVersion()) {
      this.gameVersion = new GameVersion(other.gameVersion);
    }
  }

  @Override
  public TournamentDefaults deepCopy() {
    return new TournamentDefaults(this);
  }

  @Override
  public void clear() {
    this.gameVersion = null;
  }

  @org.apache.thrift.annotation.Nullable
  public GameVersion getGameVersion() {
    return this.gameVersion;
  }

  public TournamentDefaults setGameVersion(@org.apache.thrift.annotation.Nullable GameVersion gameVersion) {
    this.gameVersion = gameVersion;
    return this;
  }

  public void unsetGameVersion() {
    this.gameVersion = null;
  }

  /** Returns true if field gameVersion is set (has been assigned a value) and false otherwise */
  public boolean isSetGameVersion() {
    return this.gameVersion != null;
  }

  public void setGameVersionIsSet(boolean value) {
    if (!value) {
      this.gameVersion = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case GAME_VERSION:
      if (value == null) {
        unsetGameVersion();
      } else {
        setGameVersion((GameVersion)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case GAME_VERSION:
      return getGameVersion();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case GAME_VERSION:
      return isSetGameVersion();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof TournamentDefaults)
      return this.equals((TournamentDefaults)that);
    return false;
  }

  public boolean equals(TournamentDefaults that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_gameVersion = true && this.isSetGameVersion();
    boolean that_present_gameVersion = true && that.isSetGameVersion();
    if (this_present_gameVersion || that_present_gameVersion) {
      if (!(this_present_gameVersion && that_present_gameVersion))
        return false;
      if (!this.gameVersion.equals(that.gameVersion))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetGameVersion()) ? 131071 : 524287);
    if (isSetGameVersion())
      hashCode = hashCode * 8191 + gameVersion.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(TournamentDefaults other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetGameVersion(), other.isSetGameVersion());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGameVersion()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.gameVersion, other.gameVersion);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TournamentDefaults(");
    boolean first = true;

    sb.append("gameVersion:");
    if (this.gameVersion == null) {
      sb.append("null");
    } else {
      sb.append(this.gameVersion);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (gameVersion != null) {
      gameVersion.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TournamentDefaultsStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public TournamentDefaultsStandardScheme getScheme() {
      return new TournamentDefaultsStandardScheme();
    }
  }

  private static class TournamentDefaultsStandardScheme extends org.apache.thrift.scheme.StandardScheme<TournamentDefaults> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, TournamentDefaults struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // GAME_VERSION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.gameVersion = new GameVersion();
              struct.gameVersion.read(iprot);
              struct.setGameVersionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, TournamentDefaults struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.gameVersion != null) {
        oprot.writeFieldBegin(GAME_VERSION_FIELD_DESC);
        struct.gameVersion.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TournamentDefaultsTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public TournamentDefaultsTupleScheme getScheme() {
      return new TournamentDefaultsTupleScheme();
    }
  }

  private static class TournamentDefaultsTupleScheme extends org.apache.thrift.scheme.TupleScheme<TournamentDefaults> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TournamentDefaults struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetGameVersion()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetGameVersion()) {
        struct.gameVersion.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TournamentDefaults struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.gameVersion = new GameVersion();
        struct.gameVersion.read(iprot);
        struct.setGameVersionIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

